CREATE TYPE core.customer_status AS ENUM ('active', 'churned');

CREATE TABLE core.customers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status core.customer_status NOT NULL DEFAULT 'active',
  name text NOT NULL
);

CREATE INDEX customers_status_idx ON core.customers (status);

CREATE SEQUENCE core.invoice_seq START 1000;

ALTER TABLE core.customers ALTER COLUMN name SET DEFAULT 'unknown';

COMMENT ON TABLE core.customers IS 'Customer registry';
