import type { SchemaObject, TableColumn } from "../core.js";
import { formatQualifiedName, quoteIdent } from "../sql/identifiers.js";
import { makeObject } from "../sql/statements.js";
import type { CatalogQuery } from "./query.js";

export async function collectTables(pool: CatalogQuery): Promise<SchemaObject[]> {
  const tables = await pool.query<Record<string, unknown>>(`
    select c.oid::text as oid, n.nspname as schema, c.relname as name
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
    where c.relkind in ('r', 'p')
      and not c.relispartition
      and n.nspname !~ '^pg_'
      and n.nspname <> 'information_schema'
    order by n.nspname, c.relname
  `);
  if (tables.rows.length === 0) {
    return [];
  }
  const oids = tables.rows.map((row) => stringValue(row.oid));
  const [columns, constraints] = await Promise.all([
    pool.query<Record<string, unknown>>(
      `
        select
          a.attrelid::text as oid,
          a.attname as name,
          format_type(a.atttypid, a.atttypmod) as type,
          a.attnotnull as not_null,
          a.attidentity as identity,
          a.attgenerated as generated,
          pg_get_expr(d.adbin, d.adrelid) as default_expression
        from pg_attribute a
        left join pg_attrdef d on d.adrelid = a.attrelid and d.adnum = a.attnum
        where a.attrelid = any($1::oid[])
          and a.attnum > 0
          and not a.attisdropped
        order by a.attrelid, a.attnum
      `,
      [oids]
    ),
    pool.query<Record<string, unknown>>(
      `
        select conrelid::text as oid, conname as name, pg_get_constraintdef(oid, true) as definition
        from pg_constraint
        where conrelid = any($1::oid[])
          and contype in ('p', 'u', 'f', 'c', 'x')
        order by conrelid, conname
      `,
      [oids]
    ),
  ]);
  const columnsByOid = groupByOid(columns.rows);
  const constraintsByOid = groupByOid(constraints.rows);
  const objects: SchemaObject[] = [];
  for (const table of tables.rows) {
    const oid = stringValue(table.oid);
    const columnDefinitions = (columnsByOid.get(oid) ?? []).map(columnFromRow);
    const lines = columnDefinitions.map(
      (column) => `  ${quoteIdent(column.name)} ${column.definition}`
    );
    const schema = stringValue(table.schema);
    const name = stringValue(table.name);
    const sql = `CREATE TABLE ${formatQualifiedName(schema, name)} (\n${lines.join(",\n")}\n)`;
    objects.push(
      makeObject({ kind: "table", name, schema }, sql, 0, undefined, {
        columns: columnDefinitions,
      })
    );

    for (const constraint of constraintsByOid.get(oid) ?? []) {
      const constraintName = stringValue(constraint.name);
      const constraintObject = makeObject(
        { kind: "constraint", name: constraintName, schema, table: name },
        `ALTER TABLE ONLY ${formatQualifiedName(schema, name)} ADD CONSTRAINT ${quoteIdent(constraintName)} ${stringValue(constraint.definition)}`,
        0,
        undefined
      );
      constraintObject.dependencies.push(`${schema}.${name}`);
      objects.push(constraintObject);
    }
  }
  return objects;
}

function columnFromRow(column: Record<string, unknown>): TableColumn {
  const identity = stringValue(column.identity);
  const generated = stringValue(column.generated);
  const parts = [stringValue(column.type)];
  if (generated === "s" && column.default_expression) {
    parts.push(`GENERATED ALWAYS AS (${stringValue(column.default_expression)}) STORED`);
  } else if (identity === "a") {
    parts.push("GENERATED ALWAYS AS IDENTITY");
  } else if (identity === "d") {
    parts.push("GENERATED BY DEFAULT AS IDENTITY");
  } else if (column.default_expression) {
    parts.push(`DEFAULT ${stringValue(column.default_expression)}`);
  }
  if (column.not_null) {
    parts.push("NOT NULL");
  }
  const facts: TableColumn = {
    definition: parts.join(" "),
    generated: generated === "s",
    hasDefault: Boolean(column.default_expression) && generated !== "s",
    hasInlineConstraint: false,
    identity: identity === "a" || identity === "d",
    name: stringValue(column.name),
    notNull: column.not_null === true,
    type: stringValue(column.type),
  };
  if (facts.hasDefault && !facts.identity) {
    facts.defaultExpression = stringValue(column.default_expression);
  }
  return facts;
}

function groupByOid(rows: Record<string, unknown>[]): Map<string, Record<string, unknown>[]> {
  const groups = new Map<string, Record<string, unknown>[]>();
  for (const row of rows) {
    const oid = stringValue(row.oid);
    const group = groups.get(oid) ?? [];
    group.push(row);
    groups.set(oid, group);
  }
  return groups;
}

function stringValue(value: unknown): string {
  return typeof value === "string" ? value : String(value);
}
