import { execFile } from "node:child_process";
import { mkdtemp, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { basename, dirname, join, sep } from "node:path";
import { promisify } from "node:util";
import { describe, expect, it } from "vitest";

const run = promisify(execFile);

const lineageSql =
  "-- Generated by supaschema.\n-- supaschema: lineage from=abc to=def\nSET lock_timeout = '5s';\n";
const handAuthoredSql = "-- reviewed migration\nINSERT INTO t VALUES (1) ON CONFLICT DO NOTHING;\n";

async function runHook(
  script: string,
  payload: unknown,
): Promise<{ code: number; stderr: string; stdout: string }> {
  return await new Promise((resolvePromise) => {
    const child = execFile("node", [script], (error, stdout, stderr) => {
      const code =
        error && typeof (error as { code?: unknown }).code === "number"
          ? ((error as { code: number }).code ?? 1)
          : 0;
      resolvePromise({ code, stderr, stdout });
    });
    child.stdin?.end(JSON.stringify(payload));
  });
}

async function fixtures(): Promise<{ generated: string; handAuthored: string }> {
  const directory = await mkdtemp(join(tmpdir(), "supa-agent-hooks-"));
  const generated = join(directory, "20260611000000_generated.sql");
  const handAuthored = join(directory, "20260611000001_hand.sql");
  await writeFile(generated, lineageSql);
  await writeFile(handAuthored, handAuthoredSql);
  return { generated, handAuthored };
}

describe("claude generated-migration edit hook", () => {
  const script = ".claude/hooks/block-generated-migration-edits.mjs";

  it("blocks edits to migrations carrying the lineage marker", async () => {
    const { generated } = await fixtures();
    const result = await runHook(script, {
      tool_input: { file_path: generated },
      tool_name: "Edit",
    });

    expect(result.code).toBe(2);
    expect(result.stderr).toContain("supaschema diff");
  });

  it("allows hand-authored migrations, new files, and non-sql edits", async () => {
    const { handAuthored } = await fixtures();
    for (const payload of [
      { tool_input: { file_path: handAuthored }, tool_name: "Write" },
      { tool_input: { file_path: `${handAuthored}.missing.sql` }, tool_name: "Write" },
      { tool_input: { file_path: "src/render.ts" }, tool_name: "Edit" },
      { tool_input: { command: "ls" }, tool_name: "Bash" },
    ]) {
      const result = await runHook(script, payload);
      expect(result.code).toBe(0);
    }
  });
});

describe("codex generated-migration tool gate", () => {
  const script = ".codex/hooks/supaschema-tool-gate.mjs";

  it("denies apply_patch updates to migrations carrying the lineage marker", async () => {
    const { generated } = await fixtures();
    const patch = `*** Begin Patch\n*** Update File: ${generated}\n@@\n-SET lock_timeout = '5s';\n+SET lock_timeout = '1s';\n*** End Patch`;
    const result = await runHook(script, {
      tool_input: { patch },
      tool_name: "apply_patch",
    });

    expect(result.code).toBe(0);
    const output = JSON.parse(result.stdout) as {
      hookSpecificOutput?: { permissionDecision?: string; permissionDecisionReason?: string };
    };
    expect(output.hookSpecificOutput?.permissionDecision).toBe("deny");
    expect(output.hookSpecificOutput?.permissionDecisionReason).toContain("supaschema diff");
  });

  it("allows hand-authored targets and emits empty output", async () => {
    const { handAuthored } = await fixtures();
    const patch = `*** Begin Patch\n*** Update File: ${handAuthored}\n@@\n-x\n+y\n*** End Patch`;
    const result = await runHook(script, {
      tool_input: { patch },
      tool_name: "apply_patch",
    });

    expect(result.code).toBe(0);
    expect(JSON.parse(result.stdout)).toEqual({});
  });

  it("denies direct file-path edits to generated migrations", async () => {
    const { generated } = await fixtures();
    const result = await runHook(script, {
      tool_input: { file_path: generated },
      tool_name: "edit_file",
    });

    const output = JSON.parse(result.stdout) as {
      hookSpecificOutput?: { permissionDecision?: string };
    };
    expect(output.hookSpecificOutput?.permissionDecision).toBe("deny");
  });

  it("allows deleting a stale generated migration (the sanctioned recovery lane)", async () => {
    const { generated } = await fixtures();
    const patch = `*** Begin Patch\n*** Delete File: ${generated}\n*** End Patch`;
    const result = await runHook(script, {
      tool_input: { patch },
      tool_name: "apply_patch",
    });

    expect(result.code).toBe(0);
    expect(JSON.parse(result.stdout)).toEqual({});
  });

  it("denies delete-and-rewrite patches that replace a generated migration in place", async () => {
    const { generated } = await fixtures();
    const patch = `*** Begin Patch\n*** Delete File: ${generated}\n*** Add File: ${generated}\n+-- hand-written replacement\n*** End Patch`;
    const result = await runHook(script, {
      tool_input: { patch },
      tool_name: "apply_patch",
    });

    const output = JSON.parse(result.stdout) as {
      hookSpecificOutput?: { permissionDecision?: string };
    };
    expect(output.hookSpecificOutput?.permissionDecision).toBe("deny");
  });

  it("denies delete-and-rewrite patches even when the two headers spell the path differently", async () => {
    const { generated } = await fixtures();
    const dotSpelled = `${dirname(generated)}${sep}.${sep}${basename(generated)}`;
    const patch = `*** Begin Patch\n*** Delete File: ${dotSpelled}\n*** Add File: ${generated}\n+-- hand-written replacement\n*** End Patch`;
    const result = await runHook(script, {
      tool_input: { patch },
      tool_name: "apply_patch",
    });

    const output = JSON.parse(result.stdout) as {
      hookSpecificOutput?: { permissionDecision?: string };
    };
    expect(output.hookSpecificOutput?.permissionDecision).toBe("deny");
  });
});
