import { execFile } from "node:child_process";
import { chmod, mkdir, mkdtemp, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { basename, dirname, join, resolve, sep } from "node:path";
import { describe, expect, it } from "vitest";

const lineageSql =
  "-- Generated by supaschema.\n-- supaschema: lineage from=abc to=def\nSET lock_timeout = '5s';\n";
const handAuthoredSql = "-- reviewed migration\nINSERT INTO t VALUES (1) ON CONFLICT DO NOTHING;\n";

async function runHook(
  script: string,
  payload: unknown,
  options: { cwd?: string; env?: NodeJS.ProcessEnv } = {}
): Promise<{ code: number; stderr: string; stdout: string }> {
  return await new Promise((resolvePromise) => {
    const child = execFile(
      "node",
      [resolve(script)],
      { cwd: options.cwd, env: options.env },
      (error, stdout, stderr) => {
        const code =
          error && typeof (error as { code?: unknown }).code === "number"
            ? ((error as { code: number }).code ?? 1)
            : 0;
        resolvePromise({ code, stderr, stdout });
      }
    );
    child.stdin?.end(JSON.stringify(payload));
  });
}

function hookAdditionalContext(stdout: string): string {
  const output = JSON.parse(stdout) as {
    hookSpecificOutput?: { additionalContext?: string };
  };
  return output.hookSpecificOutput?.additionalContext ?? "";
}

async function fixtures(): Promise<{ generated: string; handAuthored: string }> {
  const directory = await mkdtemp(join(tmpdir(), "supa-agent-hooks-"));
  const generated = join(directory, "20260611000000_generated.sql");
  const handAuthored = join(directory, "20260611000001_hand.sql");
  await writeFile(generated, lineageSql);
  await writeFile(handAuthored, handAuthoredSql);
  return { generated, handAuthored };
}

async function autoDiffFixture(
  schemaPaths: string[],
  fakeSupaschema?: string,
  options: { writeConfig?: boolean } = {}
): Promise<{
  bin: string;
  env: NodeJS.ProcessEnv;
  log: string;
  project: string;
}> {
  const project = await mkdtemp(join(tmpdir(), "supa-auto-diff-hook-"));
  for (const schemaPath of schemaPaths) {
    await mkdir(join(project, schemaPath), { recursive: true });
  }
  if (options.writeConfig !== false) {
    await writeFile(join(project, "supaschema.config.json"), JSON.stringify({ schemaPaths }));
  }
  const log = join(project, "calls.log");
  const bin = join(project, "fake-supaschema.mjs");
  await writeFile(
    bin,
    fakeSupaschema ??
      `#!/usr/bin/env node
import { appendFileSync } from "node:fs";

appendFileSync(process.env.SUPASCHEMA_FAKE_LOG, JSON.stringify(process.argv.slice(2)) + "\\n");
if (process.argv[2] === "diff") {
  process.stdout.write("supabase/migrations/20260613000000_fake.sql\\n");
  process.exit(0);
}
if (process.argv[2] === "check") {
  process.exit(0);
}
process.exit(1);
`
  );
  await chmod(bin, 0o755);
  return {
    bin,
    env: { ...process.env, SUPASCHEMA_FAKE_LOG: log, SUPASCHEMA_HOOK_BIN: bin },
    log,
    project,
  };
}

async function syncHookProject(
  options: { packageName?: string } = {}
): Promise<{ log: string; project: string }> {
  const project = await mkdtemp(join(tmpdir(), "supa-llm-sync-hook-"));
  const log = join(project, "sync.log");
  await mkdir(join(project, ".claude/agents"), { recursive: true });
  await mkdir(join(project, ".claude/hooks"), { recursive: true });
  await mkdir(join(project, ".claude/rules"), { recursive: true });
  await mkdir(join(project, ".claude/skills/demo"), { recursive: true });
  await writeFile(
    join(project, "package.json"),
    `${JSON.stringify({
      name: options.packageName ?? "supaschema",
      scripts: { "sync:llm": "node sync.mjs" },
    })}\n`
  );
  await writeFile(
    join(project, "sync.mjs"),
    `import { appendFileSync } from "node:fs";
appendFileSync("sync.log", "sync\\n");
`
  );
  await writeFile(
    join(project, ".claude/agents/demo.md"),
    `---
name: demo
description: Demo agent
---

# Demo
`
  );
  await writeFile(join(project, ".claude/hooks/example.mjs"), "console.log('hook');\n");
  await writeFile(join(project, ".claude/rules/supaschema.md"), "# rule\n");
  await writeFile(join(project, ".claude/skills/demo/SKILL.md"), "# skill\n");
  return { log, project };
}

async function readFakeCalls(log: string): Promise<string[][]> {
  const content = await readFile(log, "utf8").catch((error: unknown) => {
    if (error instanceof Error && "code" in error && error.code === "ENOENT") {
      return "";
    }
    throw error;
  });
  return content
    .trim()
    .split("\n")
    .filter(Boolean)
    .map((line) => JSON.parse(line) as string[]);
}

function hookJson(stdout: string): Record<string, unknown> {
  return stdout.trim().length > 0 ? (JSON.parse(stdout) as Record<string, unknown>) : {};
}

function hookHandlers(value: unknown): Record<string, unknown>[] {
  const out: Record<string, unknown>[] = [];
  const visit = (candidate: unknown) => {
    if (Array.isArray(candidate)) {
      for (const item of candidate) {
        visit(item);
      }
      return;
    }
    if (!(candidate && typeof candidate === "object")) {
      return;
    }
    const record = candidate as Record<string, unknown>;
    if (typeof record.command === "string" && record.type === "command") {
      out.push(record);
    }
    for (const item of Object.values(record)) {
      visit(item);
    }
  };
  visit(value);
  return out;
}

function workspaceVariable(name: string): string {
  return ["$", "{", name, "}"].join("");
}

describe("agent hook configuration", () => {
  it("registers Claude path-bearing Node hooks in exec form", async () => {
    const settings = JSON.parse(await readFile(".claude/settings.json", "utf8")) as Record<
      string,
      unknown
    >;
    const text = JSON.stringify(settings);
    const handlers = hookHandlers(settings);
    const hooks = settings.hooks as Record<string, Record<string, unknown>[]> | undefined;

    expect(text).not.toContain(['node "', "$CLAUDE_PROJECT_DIR", '"'].join(""));
    expect(text).not.toContain(`node "${workspaceVariable("CLAUDE_PROJECT_DIR")}`);
    for (const script of [
      "context-session-start.mjs",
      "context-user-prompt-submit.mjs",
      "context-pre-tool-use.mjs",
      "context-post-tool-use.mjs",
      "context-subagent-start.mjs",
      "context-subagent-stop.mjs",
      "context-stop.mjs",
      "context-task-completed.mjs",
      "context-permission-denied.mjs",
      "context-session-end.mjs",
      "block-generated-migration-edits.mjs",
      "auto-diff-on-schema-change.mjs",
      "sync-llm-on-claude-surface-change.mjs",
    ]) {
      expect(handlers).toContainEqual(
        expect.objectContaining({
          args: [`${workspaceVariable("CLAUDE_PROJECT_DIR")}/.claude/hooks/${script}`],
          command: "node",
          type: "command",
        })
      );
    }
    expect(handlers).toContainEqual(
      expect.objectContaining({
        args: [],
        command: `${workspaceVariable("CLAUDE_PROJECT_DIR")}/.claude/hooks/pre_tool_guard.sh`,
        type: "command",
      })
    );
    const postToolUseText = JSON.stringify(hooks?.PostToolUse ?? []);
    const postToolBatch = hooks?.PostToolBatch;
    expect(postToolUseText).not.toContain("sync-llm-on-claude-surface-change.mjs");
    expect(postToolBatch).toEqual([
      expect.objectContaining({
        hooks: [
          expect.objectContaining({
            args: [
              `${workspaceVariable("CLAUDE_PROJECT_DIR")}/.claude/hooks/sync-llm-on-claude-surface-change.mjs`,
            ],
            command: "node",
            type: "command",
          }),
        ],
      }),
    ]);
    for (const entry of postToolBatch ?? []) {
      expect(entry).not.toHaveProperty("matcher");
    }
  });

  it("uses Codex matchers only on supported tool hook events", async () => {
    const config = JSON.parse(await readFile(".codex/hooks.json", "utf8")) as {
      hooks?: Record<string, Record<string, unknown>[]>;
    };

    for (const eventName of ["PreToolUse", "PostToolUse"]) {
      const entries = config.hooks?.[eventName] ?? [];
      expect(entries.length).toBeGreaterThan(0);
      for (const entry of entries) {
        expect(entry.matcher, `${eventName} entry missing matcher`).toEqual(expect.any(String));
      }
    }
    const postToolUseText = JSON.stringify(config.hooks?.PostToolUse ?? []);
    const stopEntries = config.hooks?.Stop ?? [];
    expect(postToolUseText).not.toContain("sync-llm-on-claude-surface-change.mjs");
    expect(stopEntries).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          hooks: [
            expect.objectContaining({
              command: [
                'node "$',
                "{CODEX_PROJECT_DIR:-$PWD}",
                '/.codex/hooks/context-stop.mjs"',
              ].join(""),
              type: "command",
            }),
          ],
        }),
        expect.objectContaining({
          hooks: [
            expect.objectContaining({
              command: [
                'node "$',
                "{CODEX_PROJECT_DIR:-$PWD}",
                '/.codex/hooks/sync-llm-on-claude-surface-change.mjs"',
              ].join(""),
              type: "command",
            }),
          ],
        }),
      ])
    );
    for (const entry of stopEntries) {
      expect(entry).not.toHaveProperty("matcher");
    }
  });
});

describe("llm surface sync hook", () => {
  const script = ".claude/hooks/sync-llm-on-claude-surface-change.mjs";

  it("runs sync:llm after direct edits to Claude-owned skill surfaces", async () => {
    const { log, project } = await syncHookProject();

    const result = await runHook(
      script,
      {
        cwd: project,
        hook_event_name: "PostToolBatch",
        tool_calls: [
          {
            tool_input: { file_path: ".claude/skills/demo/SKILL.md" },
            tool_name: "Edit",
          },
        ],
      },
      { cwd: project }
    );

    expect(result.code).toBe(0);
    expect(hookJson(result.stdout)).toMatchObject({
      hookSpecificOutput: expect.objectContaining({
        additionalContext: "SYNC_LLM_OK",
        hookEventName: "PostToolBatch",
      }),
    });
    expect(await readFile(log, "utf8")).toBe("sync\n");
  });

  it("catches non-file-targeted Claude surface changes through the surface fingerprint", async () => {
    const { log, project } = await syncHookProject();
    await runHook(
      script,
      {
        cwd: project,
        hook_event_name: "PostToolBatch",
        tool_calls: [{ tool_input: { file_path: "README.md" }, tool_name: "Edit" }],
      },
      { cwd: project }
    );
    await writeFile(join(project, ".claude/rules/supaschema.md"), "# changed\n");

    const result = await runHook(
      script,
      {
        cwd: project,
        hook_event_name: "PostToolBatch",
        tool_calls: [{ tool_input: { command: "echo done" }, tool_name: "Bash" }],
      },
      { cwd: project }
    );

    expect(result.code).toBe(0);
    expect(hookJson(result.stdout)).toMatchObject({
      hookSpecificOutput: expect.objectContaining({
        additionalContext: "SYNC_LLM_OK",
        hookEventName: "PostToolBatch",
      }),
    });
    expect(await readFile(log, "utf8")).toBe("sync\n");
  });

  it("uses Codex Stop JSON output while syncing changed Claude surfaces", async () => {
    const { log, project } = await syncHookProject();
    const env = { ...process.env, CODEX_PROJECT_DIR: project };
    await runHook(script, { cwd: project, hook_event_name: "Stop" }, { cwd: project, env });
    await writeFile(join(project, ".claude/rules/supaschema.md"), "# codex changed\n");

    const result = await runHook(
      script,
      { cwd: project, hook_event_name: "Stop" },
      { cwd: project, env }
    );

    expect(result.code).toBe(0);
    expect(hookJson(result.stdout)).toEqual({});
    expect(await readFile(log, "utf8")).toBe("sync\n");
  });

  it("no-ops outside the supaschema repo package", async () => {
    const { log, project } = await syncHookProject({ packageName: "consumer" });

    const result = await runHook(
      script,
      {
        cwd: project,
        hook_event_name: "PostToolBatch",
        tool_calls: [
          {
            tool_input: { file_path: ".claude/hooks/example.mjs" },
            tool_name: "Write",
          },
        ],
      },
      { cwd: project }
    );

    expect(result.code).toBe(0);
    await expect(readFile(log, "utf8")).rejects.toMatchObject({ code: "ENOENT" });
  });
});

describe("claude generated-migration edit hook", () => {
  const script = ".claude/hooks/block-generated-migration-edits.mjs";

  it("blocks edits to migrations carrying the lineage marker", async () => {
    const { generated } = await fixtures();
    const result = await runHook(script, {
      tool_input: { file_path: generated },
      tool_name: "Edit",
    });

    expect(result.code).toBe(2);
    expect(result.stderr).toContain("supaschema diff");
  });

  it("blocks apply_patch updates to migrations carrying the lineage marker", async () => {
    const { generated } = await fixtures();
    const patch = `*** Begin Patch\n*** Update File: ${generated}\n@@\n-SET lock_timeout = '5s';\n+SET lock_timeout = '1s';\n*** End Patch`;
    const result = await runHook(script, {
      tool_input: { patch },
      tool_name: "apply_patch",
    });

    expect(result.code).toBe(2);
    expect(result.stderr).toContain("supaschema diff");
  });

  it("allows deleting a stale generated migration", async () => {
    const { generated } = await fixtures();
    const patch = `*** Begin Patch\n*** Delete File: ${generated}\n*** End Patch`;
    const result = await runHook(script, {
      tool_input: { patch },
      tool_name: "apply_patch",
    });

    expect(result.code).toBe(0);
  });

  it("allows hand-authored migrations, new files, and non-sql edits", async () => {
    const { handAuthored } = await fixtures();
    for (const payload of [
      { tool_input: { file_path: handAuthored }, tool_name: "Write" },
      { tool_input: { file_path: `${handAuthored}.missing.sql` }, tool_name: "Write" },
      { tool_input: { file_path: "src/render.ts" }, tool_name: "Edit" },
      { tool_input: { command: "ls" }, tool_name: "Bash" },
    ]) {
      const result = await runHook(script, payload);
      expect(result.code).toBe(0);
    }
  });
});

describe("codex generated-migration tool gate", () => {
  const script = ".codex/hooks/block-generated-migration-edits.mjs";

  it("denies apply_patch updates to migrations carrying the lineage marker", async () => {
    const { generated } = await fixtures();
    const patch = `*** Begin Patch\n*** Update File: ${generated}\n@@\n-SET lock_timeout = '5s';\n+SET lock_timeout = '1s';\n*** End Patch`;
    const result = await runHook(script, {
      tool_input: { patch },
      tool_name: "apply_patch",
    });

    expect(result.code).toBe(0);
    const output = JSON.parse(result.stdout) as {
      hookSpecificOutput?: { permissionDecision?: string; permissionDecisionReason?: string };
    };
    expect(output.hookSpecificOutput?.permissionDecision).toBe("deny");
    expect(output.hookSpecificOutput?.permissionDecisionReason).toContain("supaschema diff");
  });

  it("allows hand-authored targets and emits empty output", async () => {
    const { handAuthored } = await fixtures();
    const patch = `*** Begin Patch\n*** Update File: ${handAuthored}\n@@\n-x\n+y\n*** End Patch`;
    const result = await runHook(script, {
      tool_input: { patch },
      tool_name: "apply_patch",
    });

    expect(result.code).toBe(0);
    expect(JSON.parse(result.stdout)).toEqual({});
  });

  it("denies direct file-path edits to generated migrations", async () => {
    const { generated } = await fixtures();
    const result = await runHook(script, {
      tool_input: { file_path: generated },
      tool_name: "edit_file",
    });

    const output = JSON.parse(result.stdout) as {
      hookSpecificOutput?: { permissionDecision?: string };
    };
    expect(output.hookSpecificOutput?.permissionDecision).toBe("deny");
  });

  it("resolves relative patch targets from the payload cwd", async () => {
    const project = await mkdtemp(join(tmpdir(), "supa-codex-relative-hook-"));
    const generated = join(project, "supabase", "migrations", "20260611000000_generated.sql");
    await mkdir(dirname(generated), { recursive: true });
    await writeFile(generated, lineageSql);
    const patch =
      "*** Begin Patch\n" +
      "*** Update File: supabase/migrations/20260611000000_generated.sql\n" +
      "@@\n" +
      "-SET lock_timeout = '5s';\n" +
      "+SET lock_timeout = '1s';\n" +
      "*** End Patch";
    const result = await runHook(
      script,
      {
        cwd: project,
        tool_input: { patch },
        tool_name: "apply_patch",
      },
      { cwd: tmpdir() }
    );

    const output = JSON.parse(result.stdout) as {
      hookSpecificOutput?: { permissionDecision?: string };
    };
    expect(output.hookSpecificOutput?.permissionDecision).toBe("deny");
  });

  it("allows deleting a stale generated migration (the sanctioned recovery lane)", async () => {
    const { generated } = await fixtures();
    const patch = `*** Begin Patch\n*** Delete File: ${generated}\n*** End Patch`;
    const result = await runHook(script, {
      tool_input: { patch },
      tool_name: "apply_patch",
    });

    expect(result.code).toBe(0);
    expect(JSON.parse(result.stdout)).toEqual({});
  });

  it("denies delete-and-rewrite patches that replace a generated migration in place", async () => {
    const { generated } = await fixtures();
    const patch = `*** Begin Patch\n*** Delete File: ${generated}\n*** Add File: ${generated}\n+-- hand-written replacement\n*** End Patch`;
    const result = await runHook(script, {
      tool_input: { patch },
      tool_name: "apply_patch",
    });

    const output = JSON.parse(result.stdout) as {
      hookSpecificOutput?: { permissionDecision?: string };
    };
    expect(output.hookSpecificOutput?.permissionDecision).toBe("deny");
  });

  it("denies delete-and-rewrite patches even when the two headers spell the path differently", async () => {
    const { generated } = await fixtures();
    const dotSpelled = `${dirname(generated)}${sep}.${sep}${basename(generated)}`;
    const patch = `*** Begin Patch\n*** Delete File: ${dotSpelled}\n*** Add File: ${generated}\n+-- hand-written replacement\n*** End Patch`;
    const result = await runHook(script, {
      tool_input: { patch },
      tool_name: "apply_patch",
    });

    const output = JSON.parse(result.stdout) as {
      hookSpecificOutput?: { permissionDecision?: string };
    };
    expect(output.hookSpecificOutput?.permissionDecision).toBe("deny");
  });
});

const skillGateCases = [
  {
    gate: ".claude/hooks/skill-gate.mjs",
    init: ".claude/hooks/skill-session-init.mjs",
    name: "claude",
  },
  {
    gate: ".codex/hooks/skill-gate.mjs",
    init: ".codex/hooks/skill-session-init.mjs",
    name: "codex",
  },
];

describe.each(skillGateCases)("repo skill enforcement hook ($name)", ({ gate, init }) => {
  it("denies a governed edit once, delivers skill context, then allows the re-run", async () => {
    const ledger = await mkdtemp(join(tmpdir(), "supa-skill-gate-"));
    const env = {
      ...process.env,
      SKILL_GATE_MODE: "enforce",
      SUPASCHEMA_SKILL_GATE_LEDGER_DIR: ledger,
    };
    const payload = {
      session_id: "skill-gate-test",
      tool_input: {
        patch:
          "*** Begin Patch\n" +
          "*** Update File: src/render.ts\n" +
          "@@\n" +
          "-old\n" +
          "+new\n" +
          "*** End Patch",
      },
      tool_name: "apply_patch",
    };

    await runHook(init, { session_id: "skill-gate-test" }, { env });
    const first = await runHook(gate, payload, { env });
    const firstOutput = hookJson(first.stdout) as {
      hookSpecificOutput?: {
        permissionDecision?: string;
        permissionDecisionReason?: string;
      };
    };
    expect(first.code).toBe(0);
    expect(firstOutput.hookSpecificOutput?.permissionDecision).toBe("deny");
    expect(firstOutput.hookSpecificOutput?.permissionDecisionReason).toContain("code-atlas");
    expect(firstOutput.hookSpecificOutput?.permissionDecisionReason).toContain(
      "Code Atlas Workflow"
    );

    const second = await runHook(gate, payload, { env });
    expect(second.code).toBe(0);
    expect(second.stdout.trim()).toBe("");

    await runHook(init, { session_id: "skill-gate-test" }, { env });
    const afterReset = await runHook(gate, payload, { env });
    const resetOutput = hookJson(afterReset.stdout) as {
      hookSpecificOutput?: { permissionDecision?: string };
    };
    expect(resetOutput.hookSpecificOutput?.permissionDecision).toBe("deny");
  });
});

const autoDiffCases = [
  { name: "codex", script: ".codex/hooks/auto-diff-on-schema-change.mjs" },
  { name: "claude", script: ".claude/hooks/auto-diff-on-schema-change.mjs" },
];

describe.each(autoDiffCases)("supaschema auto-diff hook ($name)", ({ script }) => {
  it.skipIf(process.platform === "win32")(
    "runs auto-diff for apply_patch schema deletes",
    async () => {
      const { env, log, project } = await autoDiffFixture(["supabase/schemas"]);
      const result = await runHook(
        script,
        {
          cwd: project,
          tool_input: {
            patch: "*** Begin Patch\n*** Delete File: supabase/schemas/accounts.sql\n*** End Patch",
          },
          tool_name: "apply_patch",
        },
        { cwd: project, env }
      );

      expect(result.code).toBe(0);
      expect(hookAdditionalContext(result.stdout)).toContain(
        "workflow.type_generation=create_or_refresh, workflow.zod_generation=create_or_refresh, workflow.type_usage=zod_validated"
      );
      expect(await readFakeCalls(log)).toEqual([
        ["diff", "--to", "dir:supabase/schemas"],
        ["check"],
      ]);
    }
  );

  it.skipIf(process.platform === "win32")(
    "runs auto-diff for apply_patch moves into the schema tree",
    async () => {
      const { env, log, project } = await autoDiffFixture(["supabase/schemas"]);
      const result = await runHook(
        script,
        {
          cwd: project,
          tool_input: {
            // The old path is outside the schema root; only the `*** Move to:`
            // destination lands inside it. The hook must still fire on the move.
            patch:
              "*** Begin Patch\n*** Update File: drafts/accounts.sql\n*** Move to: supabase/schemas/accounts.sql\n@@\n-CREATE TABLE app.t (id int);\n+CREATE TABLE app.t (id bigint);\n*** End Patch",
          },
          tool_name: "apply_patch",
        },
        { cwd: project, env }
      );

      expect(result.code).toBe(0);
      expect(await readFakeCalls(log)).toEqual([
        ["diff", "--to", "dir:supabase/schemas"],
        ["check"],
      ]);
    }
  );

  it.skipIf(process.platform === "win32")(
    "diffs the schema path that contains the changed file",
    async () => {
      const { env, log, project } = await autoDiffFixture(["schemas/one", "schemas/two"]);
      await writeFile(
        join(project, "schemas", "two", "accounts.sql"),
        "CREATE TABLE app.t (id int);"
      );
      const result = await runHook(
        script,
        {
          cwd: project,
          tool_input: { file_path: join(project, "schemas", "two", "accounts.sql") },
          tool_name: "Edit",
        },
        { cwd: project, env }
      );

      expect(result.code).toBe(0);
      expect(await readFakeCalls(log)).toEqual([["diff", "--to", "dir:schemas/two"], ["check"]]);
    }
  );

  it.skipIf(process.platform === "win32")(
    "runs auto-diff for direct edit_file schema edits",
    async () => {
      const { env, log, project } = await autoDiffFixture(["supabase/schemas"]);
      await writeFile(
        join(project, "supabase", "schemas", "accounts.sql"),
        "CREATE TABLE app.t (id int);"
      );
      const result = await runHook(
        script,
        {
          cwd: project,
          tool_input: { file_path: join(project, "supabase", "schemas", "accounts.sql") },
          tool_name: "edit_file",
        },
        { cwd: project, env }
      );

      expect(result.code).toBe(0);
      expect(await readFakeCalls(log)).toEqual([
        ["diff", "--to", "dir:supabase/schemas"],
        ["check"],
      ]);
    }
  );

  it.skipIf(process.platform === "win32")(
    "skips auto-diff when workflow.schema_diff is manual",
    async () => {
      const { env, log, project } = await autoDiffFixture(["supabase/schemas"]);
      await writeFile(
        join(project, "supaschema.config.json"),
        JSON.stringify({
          schemaPaths: ["supabase/schemas"],
          workflow: { schema_diff: "manual" },
        })
      );
      await writeFile(
        join(project, "supabase", "schemas", "accounts.sql"),
        "CREATE TABLE app.t (id int);"
      );

      const result = await runHook(
        script,
        {
          cwd: project,
          tool_input: { file_path: join(project, "supabase", "schemas", "accounts.sql") },
          tool_name: "Edit",
        },
        { cwd: project, env }
      );

      expect(result.code).toBe(0);
      expect(hookAdditionalContext(result.stdout)).toContain('workflow.schema_diff is "manual"');
      expect(await readFakeCalls(log)).toEqual([]);
    }
  );

  it.skipIf(process.platform === "win32")(
    "skips post-diff check when workflow.migration_check is manual",
    async () => {
      const { env, log, project } = await autoDiffFixture(["supabase/schemas"]);
      await writeFile(
        join(project, "supaschema.config.json"),
        JSON.stringify({
          schemaPaths: ["supabase/schemas"],
          workflow: { migration_check: "manual" },
        })
      );
      await writeFile(
        join(project, "supabase", "schemas", "accounts.sql"),
        "CREATE TABLE app.t (id int);"
      );

      const result = await runHook(
        script,
        {
          cwd: project,
          tool_input: { file_path: join(project, "supabase", "schemas", "accounts.sql") },
          tool_name: "Edit",
        },
        { cwd: project, env }
      );

      expect(result.code).toBe(0);
      expect(hookAdditionalContext(result.stdout)).toContain(
        'workflow.migration_check is "manual"'
      );
      expect(await readFakeCalls(log)).toEqual([["diff", "--to", "dir:supabase/schemas"]]);
    }
  );

  it.skipIf(process.platform === "win32")(
    "runs verify when workflow.migration_verify is after_schema_diff",
    async () => {
      const { env, log, project } = await autoDiffFixture(
        ["supabase/schemas"],
        `#!/usr/bin/env node
import { appendFileSync } from "node:fs";

appendFileSync(process.env.SUPASCHEMA_FAKE_LOG, JSON.stringify(process.argv.slice(2)) + "\\n");
if (process.argv[2] === "diff") {
  process.stdout.write("supabase/migrations/20260613000000_fake.sql\\n");
  process.exit(0);
}
if (process.argv[2] === "check" || process.argv[2] === "verify") {
  process.exit(0);
}
process.exit(1);
`
      );
      await writeFile(
        join(project, "supaschema.config.json"),
        JSON.stringify({
          schemaPaths: ["supabase/schemas"],
          workflow: { migration_verify: "after_schema_diff" },
        })
      );
      await writeFile(
        join(project, "supabase", "schemas", "accounts.sql"),
        "CREATE TABLE app.t (id int);"
      );

      const result = await runHook(
        script,
        {
          cwd: project,
          tool_input: { file_path: join(project, "supabase", "schemas", "accounts.sql") },
          tool_name: "Edit",
        },
        { cwd: project, env }
      );

      expect(result.code).toBe(0);
      expect(hookAdditionalContext(result.stdout)).toContain("supaschema verify passed");
      expect(await readFakeCalls(log)).toEqual([
        ["diff", "--to", "dir:supabase/schemas"],
        ["check"],
        ["verify"],
      ]);
    }
  );

  it.skipIf(process.platform === "win32")(
    "defaults to the generic PostgreSQL schema path when no config exists",
    async () => {
      const { env, log, project } = await autoDiffFixture(["database/schemas"], undefined, {
        writeConfig: false,
      });
      await writeFile(
        join(project, "database", "schemas", "accounts.sql"),
        "CREATE TABLE app.t (id int);"
      );
      const result = await runHook(
        script,
        {
          cwd: project,
          tool_input: { file_path: join(project, "database", "schemas", "accounts.sql") },
          tool_name: "Edit",
        },
        { cwd: project, env }
      );

      expect(result.code).toBe(0);
      expect(await readFakeCalls(log)).toEqual([
        ["diff", "--to", "dir:database/schemas"],
        ["check"],
      ]);
    }
  );

  it.skipIf(process.platform === "win32")(
    "defaults to a detected provider schema path when no config exists",
    async () => {
      const { env, log, project } = await autoDiffFixture(["neon/schemas"], undefined, {
        writeConfig: false,
      });
      await writeFile(join(project, "neon.toml"), "project_id = 'quiet-waterfall-123456'\n");
      await writeFile(
        join(project, "neon", "schemas", "accounts.sql"),
        "CREATE TABLE app.t (id int);"
      );
      const result = await runHook(
        script,
        {
          cwd: project,
          tool_input: { file_path: join(project, "neon", "schemas", "accounts.sql") },
          tool_name: "Edit",
        },
        { cwd: project, env }
      );

      expect(result.code).toBe(0);
      expect(await readFakeCalls(log)).toEqual([["diff", "--to", "dir:neon/schemas"], ["check"]]);
    }
  );

  it.skipIf(process.platform === "win32")(
    "skips auto-diff when one edit touches multiple schema paths",
    async () => {
      const { env, log, project } = await autoDiffFixture(["schemas/one", "schemas/two"]);
      await writeFile(join(project, "schemas", "one", "one.sql"), "CREATE TABLE app.one (id int);");
      await writeFile(join(project, "schemas", "two", "two.sql"), "CREATE TABLE app.two (id int);");
      const result = await runHook(
        script,
        {
          cwd: project,
          tool_input: {
            patch:
              "*** Begin Patch\n" +
              "*** Update File: schemas/one/one.sql\n" +
              "@@\n-old\n+new\n" +
              "*** Update File: schemas/two/two.sql\n" +
              "@@\n-old\n+new\n" +
              "*** End Patch",
          },
          tool_name: "apply_patch",
        },
        { cwd: project, env }
      );

      expect(result.code).toBe(0);
      expect(result.stdout).toContain("multiple configured schema roots");
      expect(await readFakeCalls(log)).toEqual([]);
    }
  );

  it.skipIf(process.platform === "win32")(
    "skips auto-diff while install path confirmation is pending",
    async () => {
      // No confirmed config yet: the installer leaves the config absent in the
      // ambiguous case, so the manifest's pending flag is the only path signal.
      const { env, log, project } = await autoDiffFixture(["apps/api/schemas"], undefined, {
        writeConfig: false,
      });
      await mkdir(join(project, ".supaschema"), { recursive: true });
      await mkdir(join(project, "packages", "db", "schemas"), { recursive: true });
      await writeFile(
        join(project, ".supaschema", "install.json"),
        JSON.stringify({
          candidates: {
            migrationsDirs: ["apps/api/migrations", "packages/db/migrations"],
            schemaPaths: ["apps/api/schemas", "packages/db/schemas"],
          },
          migrationsDir: "apps/api/migrations",
          pathConfirmationNeeded: true,
          schemaPaths: ["apps/api/schemas"],
        })
      );
      await writeFile(
        join(project, "apps", "api", "schemas", "accounts.sql"),
        "CREATE TABLE app.t (id int);"
      );
      const result = await runHook(
        script,
        {
          cwd: project,
          tool_input: { file_path: join(project, "apps", "api", "schemas", "accounts.sql") },
          tool_name: "Edit",
        },
        { cwd: project, env }
      );

      expect(result.code).toBe(0);
      expect(result.stdout).toContain("path confirmation is pending");
      expect(result.stdout).toContain(".supaschema/install.json");
      expect(await readFakeCalls(log)).toEqual([]);
    }
  );

  it.skipIf(process.platform === "win32")(
    "resumes auto-diff once config confirms all path fields despite a stale pending flag",
    async () => {
      // The installer recorded pathConfirmationNeeded, then a human confirmed by
      // setting schemaPaths, sources.to, and migrationsDir in supaschema.config.json.
      // The stale manifest flag must no longer block auto-diff — the documented
      // confirmation step re-enables it without anyone hand-editing or deleting
      // .supaschema/install.json.
      const { env, log, project } = await autoDiffFixture(["apps/api/schemas"]);
      await writeFile(
        join(project, "supaschema.config.json"),
        JSON.stringify({
          migrationsDir: "apps/api/migrations",
          schemaPaths: ["apps/api/schemas"],
          sources: { from: "auto", to: "dir:apps/api/schemas" },
        })
      );
      await mkdir(join(project, ".supaschema"), { recursive: true });
      await writeFile(
        join(project, ".supaschema", "install.json"),
        JSON.stringify({
          candidates: {
            migrationsDirs: ["apps/api/migrations", "packages/db/migrations"],
            schemaPaths: ["apps/api/schemas", "packages/db/schemas"],
          },
          migrationsDir: "apps/api/migrations",
          pathConfirmationNeeded: true,
          schemaPaths: ["apps/api/schemas"],
        })
      );
      await writeFile(
        join(project, "apps", "api", "schemas", "accounts.sql"),
        "CREATE TABLE app.t (id int);"
      );
      const result = await runHook(
        script,
        {
          cwd: project,
          tool_input: { file_path: join(project, "apps", "api", "schemas", "accounts.sql") },
          tool_name: "Edit",
        },
        { cwd: project, env }
      );

      expect(result.code).toBe(0);
      expect(result.stdout).not.toContain("path confirmation is pending");
      expect(await readFakeCalls(log)).toEqual([
        ["diff", "--to", "dir:apps/api/schemas"],
        ["check"],
      ]);
    }
  );

  it.skipIf(process.platform === "win32")(
    "redacts secrets from raw supaschema output",
    async () => {
      const jwt = "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIn0.signature";
      const { env, project } = await autoDiffFixture(
        ["supabase/schemas"],
        `#!/usr/bin/env node
import { appendFileSync } from "node:fs";

appendFileSync(process.env.SUPASCHEMA_FAKE_LOG, JSON.stringify(process.argv.slice(2)) + "\\n");
if (process.argv[2] === "diff") {
  process.stderr.write("failed postgresql://postgres:super-secret@localhost/db token=abc123 ${jwt}\\n");
  process.exit(1);
}
process.exit(0);
`
      );
      await writeFile(
        join(project, "supabase", "schemas", "accounts.sql"),
        "CREATE TABLE app.t (id int);"
      );
      const result = await runHook(
        script,
        {
          cwd: project,
          tool_input: { file_path: join(project, "supabase", "schemas", "accounts.sql") },
          tool_name: "Edit",
        },
        { cwd: project, env }
      );

      expect(result.code).toBe(0);
      const output = JSON.parse(result.stdout) as {
        hookSpecificOutput?: { additionalContext?: string };
      };
      const context = output.hookSpecificOutput?.additionalContext ?? "";
      expect(context).toContain("postgresql://postgres:[redacted]@localhost/db");
      expect(context).toContain("token=[redacted]");
      expect(context).toContain("[redacted-jwt]");
      expect(context).not.toContain("super-secret");
      expect(context).not.toContain("abc123");
      expect(context).not.toContain("eyJhbGci");
    }
  );
});
