import { execFile } from "node:child_process";
import { chmod, mkdir, mkdtemp, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { basename, dirname, join, resolve, sep } from "node:path";
import { describe, expect, it } from "vitest";

const lineageSql =
  "-- Generated by supaschema.\n-- supaschema: lineage from=abc to=def\nSET lock_timeout = '5s';\n";
const handAuthoredSql = "-- reviewed migration\nINSERT INTO t VALUES (1) ON CONFLICT DO NOTHING;\n";
const cliPath = resolve(import.meta.dirname, "../dist/cli.js");

async function runHook(
  script: string,
  payload: unknown,
  options: { cwd?: string; env?: NodeJS.ProcessEnv } = {}
): Promise<{ code: number; stderr: string; stdout: string }> {
  return await new Promise((resolvePromise) => {
    const cliArgs = script.startsWith("supaschema hook ")
      ? [cliPath, ...script.split(" ").slice(1)]
      : undefined;
    const child = execFile(
      process.execPath,
      cliArgs ?? [resolve(script)],
      { cwd: options.cwd, env: options.env },
      (error, stdout, stderr) => {
        const code =
          error && typeof (error as { code?: unknown }).code === "number"
            ? ((error as { code: number }).code ?? 1)
            : 0;
        resolvePromise({ code, stderr, stdout });
      }
    );
    child.stdin?.end(JSON.stringify(payload));
  });
}

function hookAdditionalContext(stdout: string): string {
  const output = JSON.parse(stdout) as {
    hookSpecificOutput?: { additionalContext?: string };
  };
  return output.hookSpecificOutput?.additionalContext ?? "";
}

async function fixtures(): Promise<{
  generated: string;
  handAuthored: string;
}> {
  const directory = await mkdtemp(join(tmpdir(), "supa-agent-hooks-"));
  const generated = join(directory, "20260611000000_generated.sql");
  const handAuthored = join(directory, "20260611000001_hand.sql");
  await writeFile(generated, lineageSql);
  await writeFile(handAuthored, handAuthoredSql);
  return { generated, handAuthored };
}

async function autoDiffFixture(
  schemaPaths: string[],
  fakeSupaschema?: string,
  options: { writeConfig?: boolean } = {}
): Promise<{
  bin: string;
  env: NodeJS.ProcessEnv;
  log: string;
  project: string;
}> {
  const project = await mkdtemp(join(tmpdir(), "supa-auto-diff-hook-"));
  for (const schemaPath of schemaPaths) {
    await mkdir(join(project, schemaPath), { recursive: true });
  }
  if (options.writeConfig !== false) {
    await writeFile(join(project, "supaschema.config.json"), JSON.stringify({ schemaPaths }));
  }
  const log = join(project, "calls.log");
  const bin = join(project, "fake-supaschema.mjs");
  await writeFile(
    bin,
    fakeSupaschema ??
      `#!/usr/bin/env node
import { appendFileSync } from "node:fs";

appendFileSync(process.env.SUPASCHEMA_FAKE_LOG, JSON.stringify(process.argv.slice(2)) + "\\n");
if (process.argv[2] === "diff") {
  process.stdout.write("supabase/migrations/20260613000000_fake.sql\\n");
  process.exit(0);
}
if (process.argv[2] === "check") {
  process.exit(0);
}
process.exit(1);
`
  );
  await chmod(bin, 0o755);
  return {
    bin,
    env: { ...process.env, SUPASCHEMA_FAKE_LOG: log, SUPASCHEMA_HOOK_BIN: bin },
    log,
    project,
  };
}

async function syncHookProject(
  options: { packageName?: string } = {}
): Promise<{ log: string; project: string }> {
  const project = await mkdtemp(join(tmpdir(), "supa-llm-sync-hook-"));
  const log = join(project, "sync.log");
  await mkdir(join(project, ".claude/agents"), { recursive: true });
  await mkdir(join(project, ".claude/hooks"), { recursive: true });
  await mkdir(join(project, ".claude/rules"), { recursive: true });
  await mkdir(join(project, ".claude/skills/demo"), { recursive: true });
  await writeFile(
    join(project, "package.json"),
    `${JSON.stringify({
      name: options.packageName ?? "supaschema",
      scripts: { "sync:llm": "node sync.mjs" },
    })}\n`
  );
  await writeFile(
    join(project, "sync.mjs"),
    `import { appendFileSync } from "node:fs";
appendFileSync("sync.log", "sync\\n");
`
  );
  await writeFile(
    join(project, ".claude/agents/demo.md"),
    `---
name: demo
description: Demo agent
---

# Demo
`
  );
  await writeFile(join(project, ".claude/hooks/example.mjs"), "console.log('hook');\n");
  await writeFile(join(project, ".claude/rules/supaschema.md"), "# rule\n");
  await writeFile(join(project, ".claude/skills/demo/SKILL.md"), "# skill\n");
  return { log, project };
}

async function readFakeCalls(log: string): Promise<string[][]> {
  const content = await readFile(log, "utf8").catch((error: unknown) => {
    if (error instanceof Error && "code" in error && error.code === "ENOENT") {
      return "";
    }
    throw error;
  });
  return content
    .trim()
    .split("\n")
    .filter(Boolean)
    .map((line) => JSON.parse(line) as string[]);
}

function hookJson(stdout: string): Record<string, unknown> {
  return stdout.trim().length > 0 ? (JSON.parse(stdout) as Record<string, unknown>) : {};
}

function hookHandlers(value: unknown): Record<string, unknown>[] {
  const out: Record<string, unknown>[] = [];
  const visit = (candidate: unknown) => {
    if (Array.isArray(candidate)) {
      for (const item of candidate) {
        visit(item);
      }
      return;
    }
    if (!(candidate && typeof candidate === "object")) {
      return;
    }
    const record = candidate as Record<string, unknown>;
    if (typeof record.command === "string" && record.type === "command") {
      out.push(record);
    }
    for (const item of Object.values(record)) {
      visit(item);
    }
  };
  visit(value);
  return out;
}

function workspaceVariable(name: string): string {
  return ["$", "{", name, "}"].join("");
}

describe("agent hook configuration", () => {
  it("registers Claude hooks without retired wrapper scripts", async () => {
    const settings = JSON.parse(await readFile(".claude/settings.json", "utf8")) as Record<
      string,
      unknown
    >;
    const text = JSON.stringify(settings);
    const handlers = hookHandlers(settings);
    const hooks = settings.hooks as Record<string, Record<string, unknown>[]> | undefined;

    expect(text).not.toContain(['node "', "$CLAUDE_PROJECT_DIR", '"'].join(""));
    expect(text).not.toContain(`node "${workspaceVariable("CLAUDE_PROJECT_DIR")}`);
    for (const script of [
      "context-session-start.mjs",
      "context-user-prompt-submit.mjs",
      "context-pre-tool-use.mjs",
      "context-post-tool-use.mjs",
      "context-subagent-start.mjs",
      "context-subagent-stop.mjs",
      "context-stop.mjs",
      "context-task-completed.mjs",
      "context-permission-denied.mjs",
      "context-session-end.mjs",
      "sync-llm-on-claude-surface-change.mjs",
      "guards/bash-policy-checks.mjs",
    ]) {
      expect(handlers).toContainEqual(
        expect.objectContaining({
          args: [`${workspaceVariable("CLAUDE_PROJECT_DIR")}/.claude/hooks/${script}`],
          command: "node",
          type: "command",
        })
      );
    }
    expect(text).not.toContain("block-generated-migration-edits.mjs");
    expect(text).not.toContain("auto-diff-on-schema-change.mjs");
    expect(handlers).toContainEqual(
      expect.objectContaining({
        args: [
          "--no-install",
          "supaschema",
          "hook",
          "generated-migration-edit",
          "--runtime",
          "claude",
        ],
        command: "npx",
        type: "command",
      })
    );
    expect(handlers).toContainEqual(
      expect.objectContaining({
        args: ["--no-install", "supaschema", "hook", "schema-write"],
        command: "npx",
        type: "command",
      })
    );
    const postToolUseText = JSON.stringify(hooks?.PostToolUse ?? []);
    const postToolBatch = hooks?.PostToolBatch;
    expect(postToolUseText).not.toContain("sync-llm-on-claude-surface-change.mjs");
    expect(postToolBatch).toEqual([
      expect.objectContaining({
        hooks: [
          expect.objectContaining({
            args: [
              `${workspaceVariable("CLAUDE_PROJECT_DIR")}/.claude/hooks/sync-llm-on-claude-surface-change.mjs`,
            ],
            command: "node",
            type: "command",
          }),
        ],
      }),
    ]);
    for (const entry of postToolBatch ?? []) {
      expect(entry).not.toHaveProperty("matcher");
    }
  });

  it("uses Codex matchers only on supported tool hook events", async () => {
    const config = JSON.parse(await readFile(".codex/hooks.json", "utf8")) as {
      hooks?: Record<string, Record<string, unknown>[]>;
    };

    for (const eventName of ["PreToolUse", "PostToolUse"]) {
      const entries = config.hooks?.[eventName] ?? [];
      expect(entries.length).toBeGreaterThan(0);
      for (const entry of entries) {
        expect(entry.matcher, `${eventName} entry missing matcher`).toEqual(expect.any(String));
      }
    }
    const postToolUseText = JSON.stringify(config.hooks?.PostToolUse ?? []);
    const stopEntries = config.hooks?.Stop ?? [];
    expect(postToolUseText).not.toContain("sync-llm-on-claude-surface-change.mjs");
    expect(JSON.stringify(config)).not.toContain("context-");
    expect(JSON.stringify(config)).toContain("general-guard.mjs");
    expect(JSON.stringify(config)).not.toContain("block-generated-migration-edits.mjs");
    expect(JSON.stringify(config)).not.toContain("auto-diff-on-schema-change.mjs");
    expect(JSON.stringify(config)).toContain("supaschema hook generated-migration-edit");
    expect(JSON.stringify(config)).toContain("supaschema hook schema-write");
    expect(stopEntries).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          hooks: [
            expect.objectContaining({
              command: [
                'node "$',
                "{CODEX_PROJECT_DIR:-$PWD}",
                '/.codex/hooks/sync-llm-on-claude-surface-change.mjs"',
              ].join(""),
              type: "command",
            }),
          ],
        }),
      ])
    );
    for (const entry of stopEntries) {
      expect(entry).not.toHaveProperty("matcher");
    }
  });
});

describe("general Bash blocker policy", () => {
  const claudeScript = ".claude/hooks/guards/bash-policy-checks.mjs";
  const codexScript = ".codex/hooks/general-guard.mjs";
  const preToolBash = (command: string) => ({
    hook_event_name: "PreToolUse",
    tool_input: { command },
    tool_name: "Bash",
  });
  const codexDenial = (stdout: string): string | undefined => {
    const parsed = JSON.parse(stdout) as {
      hookSpecificOutput?: {
        permissionDecision?: string;
        permissionDecisionReason?: string;
      };
    };
    return parsed.hookSpecificOutput?.permissionDecision === "deny"
      ? parsed.hookSpecificOutput.permissionDecisionReason
      : undefined;
  };

  it("matches Anilize destructive Git and rm behavior", async () => {
    for (const command of [
      "git checkout main",
      "git restore --source=HEAD~1 src/index.ts",
      "rm -rf tmp",
      "rm -fr tmp",
    ]) {
      const result = await runHook(claudeScript, preToolBash(command));
      expect(result.code, command).toBe(2);
    }

    for (const command of ["rm -r tmp", "rm -rg tmp"]) {
      const result = await runHook(claudeScript, preToolBash(command));
      expect(result.code, command).toBe(0);
    }
  });

  it("blocks stateful git shortcuts and diagnostic pushes", async () => {
    for (const command of [
      "git stash",
      "git merge --squash feature/demo",
      "git reset --hard",
      'git commit --no-verify -m "skip"',
      "git push --force origin main",
      "git push | tail -20",
    ]) {
      const result = await runHook(claudeScript, preToolBash(command));
      expect(result.code, command).toBe(2);
    }
  });

  it("blocks secret argv, env file reads, and raw SQL DDL through Bash", async () => {
    for (const command of [
      "psql postgres://user:verylongpassword123@example.com/db -c 'select 1'",
      "cat .env.local",
      "psql -c 'CREATE TABLE demo(id int)'",
      "supabase db execute --sql 'DROP TABLE demo'",
    ]) {
      const result = await runHook(claudeScript, preToolBash(command));
      expect(result.code, command).toBe(2);
    }

    for (const command of [
      "cat .env.example",
      "psql -c 'select * from information_schema.tables'",
    ]) {
      const result = await runHook(claudeScript, preToolBash(command));
      expect(result.code, command).toBe(0);
    }
  });

  it("emits Codex PreToolUse denial JSON for the shared policy", async () => {
    const blocked = await runHook(codexScript, preToolBash("rm -rf tmp"));
    expect(blocked.code).toBe(0);
    expect(codexDenial(blocked.stdout)).toContain("recursive+force rm");

    const allowed = await runHook(codexScript, preToolBash("rm -r tmp"));
    expect(allowed.code).toBe(0);
    expect(JSON.parse(allowed.stdout)).toEqual({});
  });
});

describe("llm surface sync hook", () => {
  const script = ".claude/hooks/sync-llm-on-claude-surface-change.mjs";

  it("runs sync:llm after direct edits to Claude-owned skill surfaces", async () => {
    const { log, project } = await syncHookProject();

    const result = await runHook(
      script,
      {
        cwd: project,
        hook_event_name: "PostToolBatch",
        tool_calls: [
          {
            tool_input: { file_path: ".claude/skills/demo/SKILL.md" },
            tool_name: "Edit",
          },
        ],
      },
      { cwd: project }
    );

    expect(result.code).toBe(0);
    expect(hookJson(result.stdout)).toMatchObject({
      hookSpecificOutput: expect.objectContaining({
        additionalContext: "SYNC_LLM_OK",
        hookEventName: "PostToolBatch",
      }),
    });
    expect(await readFile(log, "utf8")).toBe("sync\n");
  });

  it("catches non-file-targeted Claude surface changes through the surface fingerprint", async () => {
    const { log, project } = await syncHookProject();
    await runHook(
      script,
      {
        cwd: project,
        hook_event_name: "PostToolBatch",
        tool_calls: [{ tool_input: { file_path: "README.md" }, tool_name: "Edit" }],
      },
      { cwd: project }
    );
    await writeFile(join(project, ".claude/rules/supaschema.md"), "# changed\n");

    const result = await runHook(
      script,
      {
        cwd: project,
        hook_event_name: "PostToolBatch",
        tool_calls: [{ tool_input: { command: "echo done" }, tool_name: "Bash" }],
      },
      { cwd: project }
    );

    expect(result.code).toBe(0);
    expect(hookJson(result.stdout)).toMatchObject({
      hookSpecificOutput: expect.objectContaining({
        additionalContext: "SYNC_LLM_OK",
        hookEventName: "PostToolBatch",
      }),
    });
    expect(await readFile(log, "utf8")).toBe("sync\n");
  });

  it("uses Codex Stop JSON output while syncing changed Claude surfaces", async () => {
    const { log, project } = await syncHookProject();
    const env = { ...process.env, CODEX_PROJECT_DIR: project };
    await runHook(script, { cwd: project, hook_event_name: "Stop" }, { cwd: project, env });
    await writeFile(join(project, ".claude/rules/supaschema.md"), "# codex changed\n");

    const result = await runHook(
      script,
      { cwd: project, hook_event_name: "Stop" },
      { cwd: project, env }
    );

    expect(result.code).toBe(0);
    expect(hookJson(result.stdout)).toEqual({});
    expect(await readFile(log, "utf8")).toBe("sync\n");
  });

  it("no-ops outside the supaschema repo package", async () => {
    const { log, project } = await syncHookProject({ packageName: "consumer" });

    const result = await runHook(
      script,
      {
        cwd: project,
        hook_event_name: "PostToolBatch",
        tool_calls: [
          {
            tool_input: { file_path: ".claude/hooks/example.mjs" },
            tool_name: "Write",
          },
        ],
      },
      { cwd: project }
    );

    expect(result.code).toBe(0);
    await expect(readFile(log, "utf8")).rejects.toMatchObject({
      code: "ENOENT",
    });
    await expect(
      readFile(join(project, ".tmp", "sync-llm-on-claude-surface-change.json"), "utf8")
    ).rejects.toMatchObject({ code: "ENOENT" });
  });
});

describe("claude generated-migration edit hook", () => {
  const script = "supaschema hook generated-migration-edit --runtime claude";

  it("blocks edits to migrations carrying the lineage marker", async () => {
    const { generated } = await fixtures();
    const result = await runHook(script, {
      tool_input: { file_path: generated },
      tool_name: "Edit",
    });

    expect(result.code).toBe(2);
    expect(result.stderr).toContain("supaschema diff");
  });

  it("blocks apply_patch updates to migrations carrying the lineage marker", async () => {
    const { generated } = await fixtures();
    const patch = `*** Begin Patch\n*** Update File: ${generated}\n@@\n-SET lock_timeout = '5s';\n+SET lock_timeout = '1s';\n*** End Patch`;
    const result = await runHook(script, {
      tool_input: { patch },
      tool_name: "apply_patch",
    });

    expect(result.code).toBe(2);
    expect(result.stderr).toContain("supaschema diff");
  });

  it("allows deleting a stale generated migration", async () => {
    const { generated } = await fixtures();
    const patch = `*** Begin Patch\n*** Delete File: ${generated}\n*** End Patch`;
    const result = await runHook(script, {
      tool_input: { patch },
      tool_name: "apply_patch",
    });

    expect(result.code).toBe(0);
  });

  it("allows hand-authored migrations, new files, and non-sql edits", async () => {
    const { handAuthored } = await fixtures();
    for (const payload of [
      { tool_input: { file_path: handAuthored }, tool_name: "Write" },
      {
        tool_input: { file_path: `${handAuthored}.missing.sql` },
        tool_name: "Write",
      },
      { tool_input: { file_path: "src/render.ts" }, tool_name: "Edit" },
      { tool_input: { command: "ls" }, tool_name: "Bash" },
    ]) {
      const result = await runHook(script, payload);
      expect(result.code).toBe(0);
    }
  });
});

describe("codex generated-migration tool gate", () => {
  const script = "supaschema hook generated-migration-edit --runtime codex";

  it("denies apply_patch updates to migrations carrying the lineage marker", async () => {
    const { generated } = await fixtures();
    const patch = `*** Begin Patch\n*** Update File: ${generated}\n@@\n-SET lock_timeout = '5s';\n+SET lock_timeout = '1s';\n*** End Patch`;
    const result = await runHook(script, {
      tool_input: { patch },
      tool_name: "apply_patch",
    });

    expect(result.code).toBe(0);
    const output = JSON.parse(result.stdout) as {
      hookSpecificOutput?: {
        permissionDecision?: string;
        permissionDecisionReason?: string;
      };
    };
    expect(output.hookSpecificOutput?.permissionDecision).toBe("deny");
    expect(output.hookSpecificOutput?.permissionDecisionReason).toContain("supaschema diff");
  });

  it("allows hand-authored targets and emits empty output", async () => {
    const { handAuthored } = await fixtures();
    const patch = `*** Begin Patch\n*** Update File: ${handAuthored}\n@@\n-x\n+y\n*** End Patch`;
    const result = await runHook(script, {
      tool_input: { patch },
      tool_name: "apply_patch",
    });

    expect(result.code).toBe(0);
    expect(JSON.parse(result.stdout)).toEqual({});
  });

  it("denies direct file-path edits to generated migrations", async () => {
    const { generated } = await fixtures();
    const result = await runHook(script, {
      tool_input: { file_path: generated },
      tool_name: "edit_file",
    });

    const output = JSON.parse(result.stdout) as {
      hookSpecificOutput?: { permissionDecision?: string };
    };
    expect(output.hookSpecificOutput?.permissionDecision).toBe("deny");
  });

  it("resolves relative patch targets from the payload cwd", async () => {
    const project = await mkdtemp(join(tmpdir(), "supa-codex-relative-hook-"));
    const generated = join(project, "supabase", "migrations", "20260611000000_generated.sql");
    await mkdir(dirname(generated), { recursive: true });
    await writeFile(generated, lineageSql);
    const patch =
      "*** Begin Patch\n" +
      "*** Update File: supabase/migrations/20260611000000_generated.sql\n" +
      "@@\n" +
      "-SET lock_timeout = '5s';\n" +
      "+SET lock_timeout = '1s';\n" +
      "*** End Patch";
    const result = await runHook(
      script,
      {
        cwd: project,
        tool_input: { patch },
        tool_name: "apply_patch",
      },
      { cwd: tmpdir() }
    );

    const output = JSON.parse(result.stdout) as {
      hookSpecificOutput?: { permissionDecision?: string };
    };
    expect(output.hookSpecificOutput?.permissionDecision).toBe("deny");
  });

  it("allows deleting a stale generated migration (the sanctioned recovery lane)", async () => {
    const { generated } = await fixtures();
    const patch = `*** Begin Patch\n*** Delete File: ${generated}\n*** End Patch`;
    const result = await runHook(script, {
      tool_input: { patch },
      tool_name: "apply_patch",
    });

    expect(result.code).toBe(0);
    expect(JSON.parse(result.stdout)).toEqual({});
  });

  it("denies delete-and-rewrite patches that replace a generated migration in place", async () => {
    const { generated } = await fixtures();
    const patch = `*** Begin Patch\n*** Delete File: ${generated}\n*** Add File: ${generated}\n+-- hand-written replacement\n*** End Patch`;
    const result = await runHook(script, {
      tool_input: { patch },
      tool_name: "apply_patch",
    });

    const output = JSON.parse(result.stdout) as {
      hookSpecificOutput?: { permissionDecision?: string };
    };
    expect(output.hookSpecificOutput?.permissionDecision).toBe("deny");
  });

  it("denies delete-and-rewrite patches even when the two headers spell the path differently", async () => {
    const { generated } = await fixtures();
    const dotSpelled = `${dirname(generated)}${sep}.${sep}${basename(generated)}`;
    const patch = `*** Begin Patch\n*** Delete File: ${dotSpelled}\n*** Add File: ${generated}\n+-- hand-written replacement\n*** End Patch`;
    const result = await runHook(script, {
      tool_input: { patch },
      tool_name: "apply_patch",
    });

    const output = JSON.parse(result.stdout) as {
      hookSpecificOutput?: { permissionDecision?: string };
    };
    expect(output.hookSpecificOutput?.permissionDecision).toBe("deny");
  });
});

describe("agent-hooks response-evidence recording", () => {
  const postToolHook = ".claude/hooks/context-post-tool-use.mjs";
  const stopHook = ".claude/hooks/context-stop.mjs";
  const promptHook = ".claude/hooks/context-user-prompt-submit.mjs";
  const claimReason = "claims verification without a recorded successful verification command";

  const bashResponse = {
    interrupted: false,
    stderr: "",
    stdout: "ALL_GUARDS_OK",
  };

  it("records a completed Bash run as evidence so a truthful verification claim is not flagged", async () => {
    const stateDir = await mkdtemp(join(tmpdir(), "supa-evidence-state-"));
    const env = { ...process.env, SUPASCHEMA_AGENT_HOOK_STATE_DIR: stateDir };
    const session = "evidence-positive";

    await runHook(promptHook, { prompt: "do the task", session_id: session }, { env });
    await runHook(
      postToolHook,
      {
        session_id: session,
        tool_input: { command: "npm run guard" },
        tool_name: "Bash",
        tool_response: bashResponse,
      },
      { env }
    );
    const stop = await runHook(
      stopHook,
      {
        last_assistant_message: "Guards passed and the change is verified.",
        session_id: session,
      },
      { env }
    );
    expect(stop.stdout).not.toContain(claimReason);
  });

  it("still flags a verification claim when no successful command evidence exists", async () => {
    const stateDir = await mkdtemp(join(tmpdir(), "supa-evidence-state-"));
    const env = { ...process.env, SUPASCHEMA_AGENT_HOOK_STATE_DIR: stateDir };
    const session = "evidence-negative";

    await runHook(promptHook, { prompt: "do the task", session_id: session }, { env });
    const stop = await runHook(
      stopHook,
      {
        last_assistant_message: "The change is verified and tested.",
        session_id: session,
      },
      { env }
    );
    expect(stop.stdout).toContain(claimReason);
  });

  it("treats an interrupted Bash run as a failure, not evidence", async () => {
    const stateDir = await mkdtemp(join(tmpdir(), "supa-evidence-state-"));
    const env = { ...process.env, SUPASCHEMA_AGENT_HOOK_STATE_DIR: stateDir };
    const session = "evidence-interrupted";

    await runHook(promptHook, { prompt: "do the task", session_id: session }, { env });
    await runHook(
      postToolHook,
      {
        session_id: session,
        tool_input: { command: "npm run guard" },
        tool_name: "Bash",
        tool_response: { interrupted: true, stderr: "", stdout: "" },
      },
      { env }
    );
    const stop = await runHook(
      stopHook,
      {
        last_assistant_message: "The guards passed and are verified.",
        session_id: session,
      },
      { env }
    );
    expect(stop.stdout).toContain(claimReason);
  });

  it("does not credit a completed command whose output reports a non-zero exit code", async () => {
    const stateDir = await mkdtemp(join(tmpdir(), "supa-evidence-state-"));
    const env = { ...process.env, SUPASCHEMA_AGENT_HOOK_STATE_DIR: stateDir };
    const session = "evidence-failed-exit";

    await runHook(promptHook, { prompt: "do the task", session_id: session }, { env });
    await runHook(
      postToolHook,
      {
        session_id: session,
        tool_input: { command: "npm run guard" },
        tool_name: "Bash",

        tool_response: {
          interrupted: false,
          stderr: "guard exited with code 1",
          stdout: "",
        },
      },
      { env }
    );
    const stop = await runHook(
      stopHook,
      {
        last_assistant_message: "The guards passed and are verified.",
        session_id: session,
      },
      { env }
    );
    expect(stop.stdout).toContain(claimReason);
  });
});

describe("agent-hooks PreToolUse subagent downgrade", () => {
  it("hard-denies a gated tool in the main session but only advises inside a subagent", async () => {
    const stateDir = await mkdtemp(join(tmpdir(), "supa-agent-hook-state-"));
    const env = { ...process.env, SUPASCHEMA_AGENT_HOOK_STATE_DIR: stateDir };
    const session = "subagent-downgrade-test";
    const promptHook = ".claude/hooks/context-user-prompt-submit.mjs";
    const preToolHook = ".claude/hooks/context-pre-tool-use.mjs";

    await runHook(
      promptHook,
      { prompt: "load the supaschema skill now", session_id: session },
      { env }
    );

    const gatedInput = {
      file_path: "src/example-not-a-skill.ts",
      new_string: "b",
      old_string: "a",
    };

    const mainCall = await runHook(
      preToolHook,
      { session_id: session, tool_input: gatedInput, tool_name: "Edit" },
      { env }
    );
    const mainOut = JSON.parse(mainCall.stdout) as {
      hookSpecificOutput?: {
        permissionDecision?: string;
        permissionDecisionReason?: string;
      };
    };
    expect(mainOut.hookSpecificOutput?.permissionDecision).toBe("deny");
    expect(mainOut.hookSpecificOutput?.permissionDecisionReason).toContain(
      "Required skills are pending"
    );

    const subCall = await runHook(
      preToolHook,
      {
        agent_id: "sub-1",
        session_id: session,
        tool_input: gatedInput,
        tool_name: "Edit",
      },
      { env }
    );
    const subOut = JSON.parse(subCall.stdout) as {
      hookSpecificOutput?: {
        additionalContext?: string;
        permissionDecision?: string;
      };
    };
    expect(subOut.hookSpecificOutput?.permissionDecision).toBeUndefined();
    expect(subOut.hookSpecificOutput?.additionalContext ?? "").toContain("subagent");
  });
});

const autoDiffCases = [{ name: "cli", script: "supaschema hook schema-write" }];

describe.each(autoDiffCases)("supaschema auto-diff hook ($name)", ({ script }) => {
  it.skipIf(process.platform === "win32")(
    "runs auto-diff for apply_patch schema deletes",
    async () => {
      const { env, log, project } = await autoDiffFixture(["supabase/schemas"]);
      const result = await runHook(
        script,
        {
          cwd: project,
          tool_input: {
            patch: "*** Begin Patch\n*** Delete File: supabase/schemas/accounts.sql\n*** End Patch",
          },
          tool_name: "apply_patch",
        },
        { cwd: project, env }
      );

      expect(result.code).toBe(0);
      expect(hookAdditionalContext(result.stdout)).toContain(
        "workflow.type_generation=create_or_refresh, workflow.zod_generation=create_or_refresh, workflow.type_usage=zod_validated"
      );
      expect(await readFakeCalls(log)).toEqual([
        ["diff", "--to", "dir:supabase/schemas"],
        ["check"],
      ]);
    }
  );

  it.skipIf(process.platform === "win32")(
    "runs auto-diff for apply_patch moves into the schema tree",
    async () => {
      const { env, log, project } = await autoDiffFixture(["supabase/schemas"]);
      const result = await runHook(
        script,
        {
          cwd: project,
          tool_input: {
            patch:
              "*** Begin Patch\n*** Update File: drafts/accounts.sql\n*** Move to: supabase/schemas/accounts.sql\n@@\n-CREATE TABLE app.t (id int);\n+CREATE TABLE app.t (id bigint);\n*** End Patch",
          },
          tool_name: "apply_patch",
        },
        { cwd: project, env }
      );

      expect(result.code).toBe(0);
      expect(await readFakeCalls(log)).toEqual([
        ["diff", "--to", "dir:supabase/schemas"],
        ["check"],
      ]);
    }
  );

  it.skipIf(process.platform === "win32")(
    "skips auto-diff for a single-root edit in a multi-root config",
    async () => {
      const { env, log, project } = await autoDiffFixture(["schemas/one", "schemas/two"]);
      await writeFile(
        join(project, "schemas", "two", "accounts.sql"),
        "CREATE TABLE app.t (id int);"
      );
      const result = await runHook(
        script,
        {
          cwd: project,
          tool_input: {
            file_path: join(project, "schemas", "two", "accounts.sql"),
          },
          tool_name: "Edit",
        },
        { cwd: project, env }
      );

      expect(result.code).toBe(0);
      expect(result.stdout).toContain("multi-root schemaPaths");
      expect(await readFakeCalls(log)).toEqual([]);
    }
  );

  it.skipIf(process.platform === "win32")(
    "runs auto-diff for direct edit_file schema edits",
    async () => {
      const { env, log, project } = await autoDiffFixture(["supabase/schemas"]);
      await writeFile(
        join(project, "supabase", "schemas", "accounts.sql"),
        "CREATE TABLE app.t (id int);"
      );
      const result = await runHook(
        script,
        {
          cwd: project,
          tool_input: {
            file_path: join(project, "supabase", "schemas", "accounts.sql"),
          },
          tool_name: "edit_file",
        },
        { cwd: project, env }
      );

      expect(result.code).toBe(0);
      expect(await readFakeCalls(log)).toEqual([
        ["diff", "--to", "dir:supabase/schemas"],
        ["check"],
      ]);
    }
  );

  it.skipIf(process.platform === "win32")(
    "skips auto-diff when workflow.schema_diff is manual",
    async () => {
      const { env, log, project } = await autoDiffFixture(["supabase/schemas"]);
      await writeFile(
        join(project, "supaschema.config.json"),
        JSON.stringify({
          schemaPaths: ["supabase/schemas"],
          workflow: { schema_diff: "manual" },
        })
      );
      await writeFile(
        join(project, "supabase", "schemas", "accounts.sql"),
        "CREATE TABLE app.t (id int);"
      );

      const result = await runHook(
        script,
        {
          cwd: project,
          tool_input: {
            file_path: join(project, "supabase", "schemas", "accounts.sql"),
          },
          tool_name: "Edit",
        },
        { cwd: project, env }
      );

      expect(result.code).toBe(0);
      expect(hookAdditionalContext(result.stdout)).toContain('workflow.schema_diff is "manual"');
      expect(await readFakeCalls(log)).toEqual([]);
    }
  );

  it.skipIf(process.platform === "win32")(
    "skips post-diff check when workflow.migration_check is manual",
    async () => {
      const { env, log, project } = await autoDiffFixture(["supabase/schemas"]);
      await writeFile(
        join(project, "supaschema.config.json"),
        JSON.stringify({
          schemaPaths: ["supabase/schemas"],
          workflow: { migration_check: "manual" },
        })
      );
      await writeFile(
        join(project, "supabase", "schemas", "accounts.sql"),
        "CREATE TABLE app.t (id int);"
      );

      const result = await runHook(
        script,
        {
          cwd: project,
          tool_input: {
            file_path: join(project, "supabase", "schemas", "accounts.sql"),
          },
          tool_name: "Edit",
        },
        { cwd: project, env }
      );

      expect(result.code).toBe(0);
      expect(hookAdditionalContext(result.stdout)).toContain(
        'workflow.migration_check is "manual"'
      );
      expect(await readFakeCalls(log)).toEqual([["diff", "--to", "dir:supabase/schemas"]]);
    }
  );

  it.skipIf(process.platform === "win32")(
    "runs config-gated sync instead of diff/check for resolved automatic targets",
    async () => {
      const { env, log, project } = await autoDiffFixture(
        ["supabase/schemas"],
        `#!/usr/bin/env node
import { appendFileSync } from "node:fs";

appendFileSync(process.env.SUPASCHEMA_FAKE_LOG, JSON.stringify(process.argv.slice(2)) + "\\n");
if (process.argv[2] === "sync") {
  process.stdout.write("sync ok\\n");
  process.exit(0);
}
process.exit(1);
`
      );
      await writeFile(
        join(project, "supaschema.config.json"),
        JSON.stringify({
          environments: {
            local: { databaseUrl: "$SUPASCHEMA_HOOK_LOCAL_DATABASE_URL" },
          },
          schemaPaths: ["supabase/schemas"],
          sync: {
            targets: {
              local: {
                environment: "local",
                historyTable: "supabase_migrations.schema_migrations",
                mode: "auto",
                runner: "direct",
              },
            },
          },
          workflow: { migration_sync: "auto" },
        })
      );
      await writeFile(
        join(project, "supabase", "schemas", "accounts.sql"),
        "CREATE TABLE app.t (id int);"
      );

      const result = await runHook(
        script,
        {
          cwd: project,
          tool_input: {
            file_path: join(project, "supabase", "schemas", "accounts.sql"),
          },
          tool_name: "Edit",
        },
        {
          cwd: project,
          env: {
            ...env,
            SUPASCHEMA_HOOK_LOCAL_DATABASE_URL: "postgresql://postgres:postgres@localhost/db",
          },
        }
      );

      expect(result.code).toBe(0);
      expect(hookAdditionalContext(result.stdout)).toContain("supaschema auto-sync completed");
      expect(hookAdditionalContext(result.stdout)).toContain(
        "Automatic sync target preflight passed for local"
      );
      expect(await readFakeCalls(log)).toEqual([["sync"]]);
    }
  );

  it.skipIf(process.platform === "win32")(
    "falls back to diff/check when automatic remote approval is absent",
    async () => {
      const { env, log, project } = await autoDiffFixture(["supabase/schemas"]);
      await writeFile(
        join(project, "supaschema.config.json"),
        JSON.stringify({
          environments: {
            production: {
              databaseUrl: "$SUPASCHEMA_HOOK_REMOTE_DATABASE_URL",
            },
          },
          schemaPaths: ["supabase/schemas"],
          sync: {
            targets: {
              remote: {
                environment: "production",
                historyTable: "supabase_migrations.schema_migrations",
                mode: "auto",
                remote: true,
                requireApprovalEnv: "SUPASCHEMA_REMOTE_SYNC_APPROVED",
                runner: "direct",
              },
            },
          },
          workflow: { migration_sync: "auto" },
        })
      );
      await writeFile(
        join(project, "supabase", "schemas", "accounts.sql"),
        "CREATE TABLE app.t (id int);"
      );

      const result = await runHook(
        script,
        {
          cwd: project,
          tool_input: {
            file_path: join(project, "supabase", "schemas", "accounts.sql"),
          },
          tool_name: "Edit",
        },
        {
          cwd: project,
          env: {
            ...env,
            SUPASCHEMA_HOOK_REMOTE_DATABASE_URL: "postgresql://postgres:postgres@localhost/db",
          },
        }
      );

      expect(result.code).toBe(0);
      const context = hookAdditionalContext(result.stdout);
      expect(context).toContain(
        "Automatic sync skipped: remote sync target remote requires SUPASCHEMA_REMOTE_SYNC_APPROVED=1"
      );
      expect(await readFakeCalls(log)).toEqual([
        ["diff", "--to", "dir:supabase/schemas"],
        ["check"],
      ]);
    }
  );

  it.skipIf(process.platform === "win32")(
    "runs config-gated sync for approved automatic remote targets",
    async () => {
      const { env, log, project } = await autoDiffFixture(
        ["supabase/schemas"],
        `#!/usr/bin/env node
import { appendFileSync } from "node:fs";

appendFileSync(process.env.SUPASCHEMA_FAKE_LOG, JSON.stringify(process.argv.slice(2)) + "\\n");
if (process.argv[2] === "sync") {
  process.stdout.write("remote sync ok\\n");
  process.exit(0);
}
process.exit(1);
`
      );
      await writeFile(
        join(project, "supaschema.config.json"),
        JSON.stringify({
          environments: {
            production: {
              databaseUrl: "$SUPASCHEMA_HOOK_REMOTE_DATABASE_URL",
            },
          },
          schemaPaths: ["supabase/schemas"],
          sync: {
            targets: {
              remote: {
                environment: "production",
                historyTable: "supabase_migrations.schema_migrations",
                mode: "auto",
                remote: true,
                requireApprovalEnv: "SUPASCHEMA_REMOTE_SYNC_APPROVED",
                runner: "direct",
              },
            },
          },
          workflow: { migration_sync: "auto" },
        })
      );
      await writeFile(
        join(project, "supabase", "schemas", "accounts.sql"),
        "CREATE TABLE app.t (id int);"
      );

      const result = await runHook(
        script,
        {
          cwd: project,
          tool_input: { file_path: join(project, "supabase", "schemas", "accounts.sql") },
          tool_name: "Edit",
        },
        {
          cwd: project,
          env: {
            ...env,
            SUPASCHEMA_HOOK_REMOTE_DATABASE_URL: "postgresql://postgres:postgres@localhost/db",
            SUPASCHEMA_REMOTE_SYNC_APPROVED: "1",
          },
        }
      );

      expect(result.code).toBe(0);
      expect(hookAdditionalContext(result.stdout)).toContain(
        "Automatic sync target preflight passed for remote"
      );
      expect(await readFakeCalls(log)).toEqual([["sync"]]);
    }
  );

  it.skipIf(process.platform === "win32")(
    "blocks the agent loop when config-gated sync fails",
    async () => {
      const { env, log, project } = await autoDiffFixture(
        ["supabase/schemas"],
        `#!/usr/bin/env node
import { appendFileSync } from "node:fs";

appendFileSync(process.env.SUPASCHEMA_FAKE_LOG, JSON.stringify(process.argv.slice(2)) + "\\n");
if (process.argv[2] === "sync") {
  process.stderr.write("ERROR SUPA_RLS_POLICY_UNSAFE: policy exposes rows\\n");
  process.exit(2);
}
process.exit(1);
`
      );
      await writeFile(
        join(project, "supaschema.config.json"),
        JSON.stringify({
          environments: { local: { databaseUrl: "$SUPASCHEMA_HOOK_LOCAL_DATABASE_URL" } },
          schemaPaths: ["supabase/schemas"],
          sync: {
            targets: {
              local: {
                environment: "local",
                historyTable: "supabase_migrations.schema_migrations",
                mode: "auto",
                runner: "direct",
              },
            },
          },
          workflow: { migration_sync: "auto" },
        })
      );
      await writeFile(
        join(project, "supabase", "schemas", "accounts.sql"),
        "CREATE TABLE app.t (id int);"
      );

      const result = await runHook(
        script,
        {
          cwd: project,
          tool_input: { file_path: join(project, "supabase", "schemas", "accounts.sql") },
          tool_name: "Edit",
        },
        {
          cwd: project,
          env: {
            ...env,
            SUPASCHEMA_HOOK_LOCAL_DATABASE_URL: "postgresql://postgres:postgres@localhost/db",
          },
        }
      );
      const output = JSON.parse(result.stdout) as {
        decision?: string;
        hookSpecificOutput?: { additionalContext?: string };
        reason?: string;
      };

      expect(result.code).toBe(0);
      expect(output.decision).toBe("block");
      expect(output.reason).toContain("supaschema sync failed");
      expect(output.reason).toContain("SUPA_RLS_POLICY_UNSAFE");
      expect(output.hookSpecificOutput?.additionalContext).toContain("supaschema auto-sync for");
      expect(await readFakeCalls(log)).toEqual([["sync"]]);
    }
  );

  it.skipIf(process.platform === "win32")(
    "falls back to diff/check when an automatic target URL is unresolved",
    async () => {
      const { env, log, project } = await autoDiffFixture(["supabase/schemas"]);
      await writeFile(
        join(project, "supaschema.config.json"),
        JSON.stringify({
          environments: {
            local: { databaseUrl: "$SUPASCHEMA_HOOK_MISSING_DATABASE_URL" },
          },
          schemaPaths: ["supabase/schemas"],
          sync: {
            targets: {
              local: {
                environment: "local",
                historyTable: "supabase_migrations.schema_migrations",
                mode: "auto",
                runner: "direct",
              },
            },
          },
          workflow: { migration_sync: "auto" },
        })
      );
      await writeFile(
        join(project, "supabase", "schemas", "accounts.sql"),
        "CREATE TABLE app.t (id int);"
      );

      const result = await runHook(
        script,
        {
          cwd: project,
          tool_input: {
            file_path: join(project, "supabase", "schemas", "accounts.sql"),
          },
          tool_name: "Edit",
        },
        { cwd: project, env }
      );

      expect(result.code).toBe(0);
      expect(hookAdditionalContext(result.stdout)).toContain(
        "Automatic sync skipped: sync target local requires $SUPASCHEMA_HOOK_MISSING_DATABASE_URL"
      );
      expect(await readFakeCalls(log)).toEqual([
        ["diff", "--to", "dir:supabase/schemas"],
        ["check"],
      ]);
    }
  );

  it.skipIf(process.platform === "win32")(
    "continues the agent loop when post-diff check fails",
    async () => {
      const { env, log, project } = await autoDiffFixture(
        ["supabase/schemas"],
        `#!/usr/bin/env node
import { appendFileSync } from "node:fs";

appendFileSync(process.env.SUPASCHEMA_FAKE_LOG, JSON.stringify(process.argv.slice(2)) + "\\n");
if (process.argv[2] === "diff") {
  process.stdout.write("supabase/migrations/20260613000000_fake.sql\\n");
  process.exit(0);
}
if (process.argv[2] === "check") {
  process.stderr.write("ERROR SUPA_CHECK_CREATE_TABLE_GUARD: TABLE creation must use IF NOT EXISTS or a catalog guard\\n");
  process.exit(2);
}
process.exit(1);
`
      );
      await writeFile(
        join(project, "supabase", "schemas", "accounts.sql"),
        "CREATE TABLE app.t (id int);"
      );

      const result = await runHook(
        script,
        {
          cwd: project,
          tool_input: {
            file_path: join(project, "supabase", "schemas", "accounts.sql"),
          },
          tool_name: "Edit",
        },
        { cwd: project, env }
      );
      const output = JSON.parse(result.stdout) as {
        decision?: string;
        hookSpecificOutput?: { additionalContext?: string };
        reason?: string;
      };

      expect(result.code).toBe(0);
      expect(output.decision).toBe("block");
      expect(output.reason).toContain("supaschema check failed");
      expect(output.reason).toContain("SUPA_CHECK_CREATE_TABLE_GUARD");
      expect(output.reason).toContain("root source");
      expect(output.reason).toContain("correlated failures");
      expect(output.hookSpecificOutput?.additionalContext).toContain(
        "supaschema check reported diagnostics"
      );
      expect(await readFakeCalls(log)).toEqual([
        ["diff", "--to", "dir:supabase/schemas"],
        ["check"],
      ]);
    }
  );

  it.skipIf(process.platform === "win32")(
    "runs verify when workflow.migration_verify is after_schema_diff",
    async () => {
      const { env, log, project } = await autoDiffFixture(
        ["supabase/schemas"],
        `#!/usr/bin/env node
import { appendFileSync } from "node:fs";

appendFileSync(process.env.SUPASCHEMA_FAKE_LOG, JSON.stringify(process.argv.slice(2)) + "\\n");
if (process.argv[2] === "diff") {
  process.stdout.write("supabase/migrations/20260613000000_fake.sql\\n");
  process.exit(0);
}
if (process.argv[2] === "check" || process.argv[2] === "verify") {
  process.exit(0);
}
process.exit(1);
`
      );
      await writeFile(
        join(project, "supaschema.config.json"),
        JSON.stringify({
          schemaPaths: ["supabase/schemas"],
          workflow: { migration_verify: "after_schema_diff" },
        })
      );
      await writeFile(
        join(project, "supabase", "schemas", "accounts.sql"),
        "CREATE TABLE app.t (id int);"
      );

      const result = await runHook(
        script,
        {
          cwd: project,
          tool_input: {
            file_path: join(project, "supabase", "schemas", "accounts.sql"),
          },
          tool_name: "Edit",
        },
        { cwd: project, env }
      );

      expect(result.code).toBe(0);
      expect(hookAdditionalContext(result.stdout)).toContain("supaschema verify passed");
      expect(await readFakeCalls(log)).toEqual([
        ["diff", "--to", "dir:supabase/schemas"],
        ["check"],
        ["verify"],
      ]);
    }
  );

  it.skipIf(process.platform === "win32")(
    "defaults to the generic PostgreSQL schema path when no config exists",
    async () => {
      const { env, log, project } = await autoDiffFixture(["database/schemas"], undefined, {
        writeConfig: false,
      });
      await writeFile(
        join(project, "database", "schemas", "accounts.sql"),
        "CREATE TABLE app.t (id int);"
      );
      const result = await runHook(
        script,
        {
          cwd: project,
          tool_input: {
            file_path: join(project, "database", "schemas", "accounts.sql"),
          },
          tool_name: "Edit",
        },
        { cwd: project, env }
      );

      expect(result.code).toBe(0);
      expect(await readFakeCalls(log)).toEqual([
        ["diff", "--to", "dir:database/schemas"],
        ["check"],
      ]);
    }
  );

  it.skipIf(process.platform === "win32")(
    "defaults to a detected provider schema path when no config exists",
    async () => {
      const { env, log, project } = await autoDiffFixture(["neon/schemas"], undefined, {
        writeConfig: false,
      });
      await writeFile(join(project, "neon.toml"), "project_id = 'quiet-waterfall-123456'\n");
      await writeFile(
        join(project, "neon", "schemas", "accounts.sql"),
        "CREATE TABLE app.t (id int);"
      );
      const result = await runHook(
        script,
        {
          cwd: project,
          tool_input: {
            file_path: join(project, "neon", "schemas", "accounts.sql"),
          },
          tool_name: "Edit",
        },
        { cwd: project, env }
      );

      expect(result.code).toBe(0);
      expect(await readFakeCalls(log)).toEqual([["diff", "--to", "dir:neon/schemas"], ["check"]]);
    }
  );

  it.skipIf(process.platform === "win32")(
    "skips auto-diff when one edit touches multiple schema paths",
    async () => {
      const { env, log, project } = await autoDiffFixture(["schemas/one", "schemas/two"]);
      await writeFile(join(project, "schemas", "one", "one.sql"), "CREATE TABLE app.one (id int);");
      await writeFile(join(project, "schemas", "two", "two.sql"), "CREATE TABLE app.two (id int);");
      const result = await runHook(
        script,
        {
          cwd: project,
          tool_input: {
            patch:
              "*** Begin Patch\n" +
              "*** Update File: schemas/one/one.sql\n" +
              "@@\n-old\n+new\n" +
              "*** Update File: schemas/two/two.sql\n" +
              "@@\n-old\n+new\n" +
              "*** End Patch",
          },
          tool_name: "apply_patch",
        },
        { cwd: project, env }
      );

      expect(result.code).toBe(0);
      expect(result.stdout).toContain("multi-root schemaPaths");
      expect(await readFakeCalls(log)).toEqual([]);
    }
  );

  it.skipIf(process.platform === "win32")(
    "skips auto-diff while install path confirmation is pending",
    async () => {
      const { env, log, project } = await autoDiffFixture(["apps/api/schemas"], undefined, {
        writeConfig: false,
      });
      await mkdir(join(project, ".supaschema"), { recursive: true });
      await mkdir(join(project, "packages", "db", "schemas"), {
        recursive: true,
      });
      await writeFile(
        join(project, ".supaschema", "install.json"),
        JSON.stringify({
          candidates: {
            migrationsDirs: ["apps/api/migrations", "packages/db/migrations"],
            schemaPaths: ["apps/api/schemas", "packages/db/schemas"],
          },
          migrationsDir: "apps/api/migrations",
          pathConfirmationNeeded: true,
          schemaPaths: ["apps/api/schemas"],
        })
      );
      await writeFile(
        join(project, "apps", "api", "schemas", "accounts.sql"),
        "CREATE TABLE app.t (id int);"
      );
      const result = await runHook(
        script,
        {
          cwd: project,
          tool_input: {
            file_path: join(project, "apps", "api", "schemas", "accounts.sql"),
          },
          tool_name: "Edit",
        },
        { cwd: project, env }
      );

      expect(result.code).toBe(0);
      expect(result.stdout).toContain("path confirmation is pending");
      expect(result.stdout).toContain(".supaschema/install.json");
      expect(await readFakeCalls(log)).toEqual([]);
    }
  );

  it.skipIf(process.platform === "win32")(
    "resumes auto-diff once config confirms all path fields despite a stale pending flag",
    async () => {
      const { env, log, project } = await autoDiffFixture(["apps/api/schemas"]);
      await writeFile(
        join(project, "supaschema.config.json"),
        JSON.stringify({
          migrationsDir: "apps/api/migrations",
          schemaPaths: ["apps/api/schemas"],
          sources: { from: "auto", to: "dir:apps/api/schemas" },
        })
      );
      await mkdir(join(project, ".supaschema"), { recursive: true });
      await writeFile(
        join(project, ".supaschema", "install.json"),
        JSON.stringify({
          candidates: {
            migrationsDirs: ["apps/api/migrations", "packages/db/migrations"],
            schemaPaths: ["apps/api/schemas", "packages/db/schemas"],
          },
          migrationsDir: "apps/api/migrations",
          pathConfirmationNeeded: true,
          schemaPaths: ["apps/api/schemas"],
        })
      );
      await writeFile(
        join(project, "apps", "api", "schemas", "accounts.sql"),
        "CREATE TABLE app.t (id int);"
      );
      const result = await runHook(
        script,
        {
          cwd: project,
          tool_input: {
            file_path: join(project, "apps", "api", "schemas", "accounts.sql"),
          },
          tool_name: "Edit",
        },
        { cwd: project, env }
      );

      expect(result.code).toBe(0);
      expect(result.stdout).not.toContain("path confirmation is pending");
      expect(await readFakeCalls(log)).toEqual([
        ["diff", "--to", "dir:apps/api/schemas"],
        ["check"],
      ]);
    }
  );

  it.skipIf(process.platform === "win32")(
    "redacts secrets from raw supaschema output",
    async () => {
      const jwt = "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIn0.signature";
      const { env, project } = await autoDiffFixture(
        ["supabase/schemas"],
        `#!/usr/bin/env node
import { appendFileSync } from "node:fs";

appendFileSync(process.env.SUPASCHEMA_FAKE_LOG, JSON.stringify(process.argv.slice(2)) + "\\n");
if (process.argv[2] === "diff") {
  process.stderr.write("failed postgresql://postgres:super-secret@localhost/db token=abc123 ${jwt}\\n");
  process.exit(1);
}
process.exit(0);
`
      );
      await writeFile(
        join(project, "supabase", "schemas", "accounts.sql"),
        "CREATE TABLE app.t (id int);"
      );
      const result = await runHook(
        script,
        {
          cwd: project,
          tool_input: {
            file_path: join(project, "supabase", "schemas", "accounts.sql"),
          },
          tool_name: "Edit",
        },
        { cwd: project, env }
      );

      expect(result.code).toBe(0);
      const output = JSON.parse(result.stdout) as {
        hookSpecificOutput?: { additionalContext?: string };
      };
      const context = output.hookSpecificOutput?.additionalContext ?? "";
      expect(context).toContain("postgresql://postgres:[redacted]@localhost/db");
      expect(context).toContain("token=[redacted]");
      expect(context).toContain("[redacted-jwt]");
      expect(context).not.toContain("super-secret");
      expect(context).not.toContain("abc123");
      expect(context).not.toContain("eyJhbGci");
    }
  );
});
