import { mkdir, mkdtemp, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { pathToFileURL } from "node:url";
import {
  createProgram,
  formatDiagnosticsWithColorAndContext,
  getPreEmitDiagnostics,
  ModuleKind,
  ModuleResolutionKind,
  ScriptTarget,
} from "typescript";
import { describe, expect, it } from "vitest";
import { extractSourceModel } from "../src/source/extract.js";
import { generateDatabaseTypes } from "../src/typegen/database.js";
import { collectSchemaShapes } from "../src/typegen/model.js";
import { generateZodSchemas } from "../src/typegen/zod.js";

const treeSql = `CREATE SCHEMA app;
CREATE TYPE app.status AS ENUM ('draft', 'active');
CREATE TABLE app.accounts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  email text,
  score numeric(10, 2) DEFAULT 0,
  tags text[] NOT NULL DEFAULT '{}',
  payload jsonb,
  state app.status NOT NULL DEFAULT 'draft',
  active boolean NOT NULL DEFAULT true,
  doubled integer GENERATED ALWAYS AS (1 + 1) STORED
);
CREATE TABLE app.events (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  account_id bigint NOT NULL CONSTRAINT events_account_fk REFERENCES app.accounts (id)
);
CREATE VIEW app.account_names AS SELECT id, name AS label FROM app.accounts;
CREATE VIEW app.account_all AS SELECT * FROM app.accounts;
CREATE VIEW app.account_rollups AS
WITH base AS (
  SELECT a.id,
    a.name,
    COALESCE(a.payload, '{}'::jsonb) AS payload,
    COALESCE(a.state, 'draft'::app.status) AS state,
    row_number() OVER (ORDER BY a.id) AS rank
  FROM app.accounts a
)
SELECT id,
  name AS account_name,
  payload,
  state,
  rank,
  NULLIF(payload ->> 'note'::text, ''::text) AS note
FROM base;
`;

const helperSql = `CREATE SCHEMA app;
CREATE TYPE public.visibility AS ENUM ('private', 'public');
CREATE TYPE app.status AS ENUM ('draft', 'active');
CREATE TYPE app.address AS (street text, zip int);
CREATE TABLE public.movies (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  visibility public.visibility NOT NULL DEFAULT 'public'
);
CREATE VIEW public.movie_names AS SELECT id, name FROM public.movies;
CREATE TABLE app.accounts (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  state app.status NOT NULL DEFAULT 'draft',
  home app.address
);
`;

const nestedViewSql = `CREATE SCHEMA messaging;
CREATE TABLE messaging.threads (
  id bigint,
  contact_email text,
  contact_id text,
  sms_recipients text[],
  primary_contact_id bigint
);
CREATE VIEW messaging.v_thread_message_summaries AS
WITH summary_contract AS (
  SELECT id, contact_email, contact_id, sms_recipients, primary_contact_id
  FROM messaging.threads
)
SELECT
  reply_recipients,
  chat_participant_ids,
  has_sms_consent,
  cardinality(reply_recipients) > 0 AS can_send_email,
  cardinality(chat_participant_ids) > 0 AS can_send_chat,
  primary_contact_id IS NOT NULL
    AND cardinality(sms_recipients) > 0
    AND has_sms_consent AS can_send_sms
FROM (
  SELECT
    sc.primary_contact_id,
    sc.sms_recipients,
    recipients.reply_recipients,
    recipients.chat_participant_ids,
    EXISTS (
      SELECT 1
      FROM messaging.threads check_thread
      WHERE check_thread.id = sc.id
    ) AS has_sms_consent
  FROM summary_contract sc
  LEFT JOIN LATERAL (
    WITH human_participants AS (
      SELECT sc.contact_email AS email, sc.contact_id AS id
    )
    SELECT
      COALESCE(ARRAY(
        SELECT DISTINCT lower(btrim(human_participants.email))
        FROM human_participants
        WHERE NULLIF(btrim(human_participants.email), ''::text) IS NOT NULL
      ), ARRAY[]::text[]) AS reply_recipients,
      COALESCE(ARRAY(
        SELECT DISTINCT btrim(human_participants.id)
        FROM human_participants
        WHERE NULLIF(btrim(human_participants.id), ''::text) IS NOT NULL
      ), ARRAY[]::text[]) AS chat_participant_ids
  ) recipients ON true
) source_rows;
`;

async function typesFor(sql: string): Promise<string> {
  const model = await modelFor(sql, "supa-typegen-");
  return generateDatabaseTypes(await collectSchemaShapes(model));
}

async function modelFor(sql: string, prefix: string) {
  const root = await mkdtemp(join(tmpdir(), prefix));
  await writeFile(join(root, "001_app.sql"), sql);
  const model = await extractSourceModel(`dir:${root}`);
  const errors = model.diagnostics.filter((item) => item.severity === "error");
  if (errors.length > 0) {
    throw new Error(`expected source extraction to succeed: ${JSON.stringify(errors)}`);
  }
  return model;
}

function collapseWhitespace(value: string): string {
  const words: string[] = [];
  let current = "";
  for (const char of value) {
    if (isWhitespace(char)) {
      if (current.length > 0) {
        words.push(current);
        current = "";
      }
    } else {
      current += char;
    }
  }
  if (current.length > 0) {
    words.push(current);
  }
  return words.join(" ");
}

function isWhitespace(char: string): boolean {
  return char === " " || char === "\n" || char === "\r" || char === "\t" || char === "\f";
}

function viewTypeBlock(types: string, name: string): string {
  const start = types.indexOf(`      ${name}: {`);
  if (start === -1) {
    return "";
  }
  const end = types.indexOf("\n      };", start);
  return end === -1 ? types.slice(start) : types.slice(start, end);
}

async function expectTypeScriptAccepts(source: string): Promise<void> {
  const tmpRoot = join(process.cwd(), ".tmp");
  await mkdir(tmpRoot, { recursive: true });
  const root = await mkdtemp(join(tmpRoot, "supa-typegen-ts-"));
  const file = join(root, "generated-types.ts");
  await writeFile(file, source);
  const program = createProgram([file], {
    module: ModuleKind.NodeNext,
    moduleResolution: ModuleResolutionKind.NodeNext,
    noEmit: true,
    strict: true,
    target: ScriptTarget.ES2022,
  });
  const diagnostics = getPreEmitDiagnostics(program);
  if (diagnostics.length > 0) {
    throw new Error(
      formatDiagnosticsWithColorAndContext(diagnostics, {
        getCanonicalFileName: (name) => name,
        getCurrentDirectory: () => root,
        getNewLine: () => "\n",
      })
    );
  }
}

describe("database type generation", () => {
  it("types tables, enums, views, and relationships without a database", async () => {
    const types = await typesFor(treeSql);

    expect(types).toContain("export type Database = {");
    expect(types).toContain('"draft" | "active"');
    expect(types).toContain("id: number;");
    expect(types).toContain("name: string;");
    expect(types).toContain("email: string | null;");
    expect(types).toContain("score: number | null;");
    expect(types).toContain("tags: string[];");
    expect(types).toContain("payload: Json | null;");
    expect(types).toContain('state: Database["app"]["Enums"]["status"];');
    expect(types).toContain("active: boolean;");
    expect(types).toContain('foreignKeyName: "events_account_fk"');
    expect(types).toContain('referencedRelation: "accounts"');
  });

  it("derives insert and update optionality from defaults, identity, and nullability", async () => {
    const types = await typesFor(treeSql);
    const insert = types.slice(types.indexOf("Insert: {"), types.indexOf("Update: {"));

    expect(insert).toContain("id?: number;");
    expect(insert).toContain("name: string;");
    expect(insert).toContain("email?: string | null;");
    expect(insert).toContain("score?: number | null;");
    expect(insert).toContain("doubled?: never;");
    const update = types.slice(types.indexOf("Update: {"), types.indexOf("Relationships:"));
    expect(update).toContain("name?: string;");
    expect(update).toContain("doubled?: never;");
  });

  it("resolves view columns through their source table and expands star selects", async () => {
    const types = await typesFor(treeSql);
    const views = types.slice(types.indexOf("Views: {"), types.indexOf("Enums: {"));

    expect(views).toContain("id: number | null;");
    expect(views).toContain("label: string | null;");
    expect(views).toContain("payload: Json | null;");
  });

  it("resolves CTE-backed view columns and typed expressions", async () => {
    const types = await typesFor(treeSql);
    const rollup = types.slice(types.indexOf("Views: {"), types.indexOf("Enums: {"));

    expect(rollup).toContain("id: number | null;");
    expect(rollup).toContain("account_name: string | null;");
    expect(rollup).toContain("payload: Json | null;");
    expect(rollup).toContain('state: Database["app"]["Enums"]["status"] | null;');
    expect(rollup).toContain("rank: number | null;");
    expect(rollup).toContain("note: string | null;");
  });

  it("resolves nested view columns from subqueries, array sublinks, and boolean expressions", async () => {
    const types = await typesFor(nestedViewSql);
    const views = types.slice(types.indexOf("Views: {"), types.indexOf("Enums: {"));

    expect(views).toContain("reply_recipients: string[] | null;");
    expect(views).toContain("chat_participant_ids: string[] | null;");
    expect(views).toContain("has_sms_consent: boolean | null;");
    expect(views).toContain("can_send_email: boolean | null;");
    expect(views).toContain("can_send_chat: boolean | null;");
    expect(views).toContain("can_send_sms: boolean | null;");
  });

  it("keeps CTE names from shadowing schema-qualified table references", async () => {
    const types = await typesFor(`CREATE SCHEMA app;
CREATE TABLE app.source (id bigint, app_value text);
CREATE VIEW app.v_collision AS
WITH source AS (SELECT 1::integer AS id, 'cte'::text AS cte_value)
SELECT app.source.app_value FROM app.source;
`);
    const views = types.slice(types.indexOf("Views: {"), types.indexOf("Enums: {"));

    expect(views).toContain("app_value: string | null;");
    expect(views).not.toContain("app_value: unknown | null;");
  });

  it("keeps qualified star expansion scoped to the matched join source", async () => {
    const types = await typesFor(`CREATE SCHEMA app;
CREATE TABLE app.accounts (id bigint, name text);
CREATE TABLE app.events (id bigint, account_id bigint, payload jsonb);
CREATE VIEW app.account_only AS
SELECT a.* FROM app.accounts a JOIN app.events e ON e.account_id = a.id;
`);
    const accountOnly = viewTypeBlock(types, "account_only");

    expect(accountOnly).toContain("id: number | null;");
    expect(accountOnly).toContain("name: string | null;");
    expect(accountOnly).not.toContain("account_id:");
    expect(accountOnly).not.toContain("payload:");
  });

  it("merges USING and NATURAL join keys once for unqualified stars", async () => {
    const types = await typesFor(`CREATE SCHEMA app;
CREATE TABLE app.left_items (id bigint, left_name text);
CREATE TABLE app.right_items (id bigint, right_name text);
CREATE VIEW app.using_join AS
SELECT * FROM app.left_items JOIN app.right_items USING (id);
CREATE VIEW app.natural_join AS
SELECT * FROM app.left_items NATURAL JOIN app.right_items;
`);
    const usingJoin = viewTypeBlock(types, "using_join");
    const naturalJoin = viewTypeBlock(types, "natural_join");

    expect(
      usingJoin.split("\n").filter((line) => line === "          id: number | null;")
    ).toHaveLength(1);
    expect(usingJoin).toContain("left_name: string | null;");
    expect(usingJoin).toContain("right_name: string | null;");
    expect(
      naturalJoin.split("\n").filter((line) => line === "          id: number | null;")
    ).toHaveLength(1);
  });

  it("preserves aliases on joined FROM items", async () => {
    const types = await typesFor(`CREATE SCHEMA app;
CREATE TABLE app.accounts (id bigint, email text);
CREATE TABLE app.profiles (id bigint, display_name text);
CREATE VIEW app.join_alias AS
SELECT j.* FROM (app.accounts JOIN app.profiles USING (id)) AS j;
CREATE VIEW app.join_alias_columns AS
SELECT j.email, j.display_name FROM (app.accounts JOIN app.profiles USING (id)) AS j;
`);
    const star = viewTypeBlock(types, "join_alias");
    const columns = viewTypeBlock(types, "join_alias_columns");

    expect(star.split("\n").filter((line) => line === "          id: number | null;")).toHaveLength(
      1
    );
    expect(star).toContain("email: string | null;");
    expect(star).toContain("display_name: string | null;");
    expect(columns).toContain("email: string | null;");
    expect(columns).toContain("display_name: string | null;");
    expect(columns).not.toContain("unknown | null;");
  });

  it("threads left-side scope into lateral subselects", async () => {
    const types = await typesFor(`CREATE SCHEMA app;
CREATE TABLE app.accounts (id bigint, email text);
CREATE VIEW app.lateral_email AS
SELECT x.email FROM app.accounts a LEFT JOIN LATERAL (SELECT a.email AS email) x ON true;
`);
    const view = viewTypeBlock(types, "lateral_email");

    expect(view).toContain("email: string | null;");
    expect(view).not.toContain("email: unknown | null;");
  });

  it("applies derived-table column aliases positionally", async () => {
    const types = await typesFor(`CREATE SCHEMA app;
CREATE TABLE app.accounts (id bigint, name text);
CREATE VIEW app.partial_aliases AS
SELECT * FROM (SELECT id, name FROM app.accounts) AS source(account_id);
`);
    const view = viewTypeBlock(types, "partial_aliases");

    expect(view).toContain("account_id: number | null;");
    expect(view).toContain("name: string | null;");
    expect(view).not.toContain("\n          id: number | null;");
  });

  it("preserves schema qualifiers when resolving column references", async () => {
    const types = await typesFor(`CREATE SCHEMA app;
CREATE SCHEMA audit;
CREATE TABLE app.accounts (id bigint);
CREATE TABLE audit.accounts (id text);
CREATE VIEW app.qualified_account AS
SELECT app.accounts.id AS account_id FROM app.accounts JOIN audit.accounts ON true;
`);
    const view = viewTypeBlock(types, "qualified_account");

    expect(view).toContain("account_id: number | null;");
    expect(view).not.toContain("account_id: string | null;");
  });

  it("treats predicate sublinks as boolean expressions", async () => {
    const types = await typesFor(`CREATE SCHEMA app;
CREATE TABLE app.accounts (id bigint);
CREATE VIEW app.account_matches AS
SELECT id IN (SELECT id FROM app.accounts) AS has_match FROM app.accounts;
`);
    const view = viewTypeBlock(types, "account_matches");

    expect(view).toContain("has_match: boolean | null;");
    expect(view).not.toContain("has_match: number | null;");
  });

  it("resolves visible function overloads before builtin names", async () => {
    const types =
      await typesFor(`CREATE FUNCTION public.lower(value integer) RETURNS integer LANGUAGE sql AS $$ SELECT value $$;
CREATE VIEW public.custom_lower AS SELECT lower(1) AS lowered;
`);
    const view = viewTypeBlock(types, "custom_lower");

    expect(view).toContain("lowered: number | null;");
    expect(view).not.toContain("lowered: string | null;");
  });

  it("falls back to builtin function metadata when no visible project overload exists", async () => {
    const types = await typesFor(`CREATE SCHEMA app;
CREATE TABLE app.accounts (id bigint, name text);
CREATE FUNCTION app.echo_int(value integer) RETURNS integer LANGUAGE sql AS $$ SELECT value $$;
CREATE VIEW app.builtin_lower AS SELECT lower(name) AS lowered FROM app.accounts;
CREATE VIEW app.custom_function AS SELECT app.echo_int(1) AS value FROM app.accounts;
`);
    const builtin = viewTypeBlock(types, "builtin_lower");
    const custom = viewTypeBlock(types, "custom_function");

    expect(builtin).toContain("lowered: string | null;");
    expect(custom).toContain("value: number | null;");
  });

  it("returns unknown after visible overload mismatch", async () => {
    const types =
      await typesFor(`CREATE FUNCTION public.lower(value bigint) RETURNS bigint LANGUAGE sql AS $$ SELECT value $$;
CREATE VIEW public.custom_lower_mismatch AS SELECT lower(1) AS lowered;
`);
    const view = viewTypeBlock(types, "custom_lower_mismatch");

    expect(view).toContain("lowered: unknown | null;");
    expect(view).not.toContain("lowered: string | null;");
    expect(view).not.toContain("lowered: number | null;");
  });

  it("emits the Constants enum tuples and Supabase-compatible helper shorthands", async () => {
    const types = await typesFor(treeSql);

    expect(types).toContain("export const Constants = {");
    expect(types).toContain('status: ["draft", "active"],');
    expect(types).toContain('type PublicSchema = Database[Extract<keyof Database, "public">];');
    expect(types).toContain("export type Tables<");
    expect(types).toContain("PublicTableNameOrOptions");
    expect(types).toContain("export type CompositeTypes<");
    expect(types).not.toContain("export type Tables<S extends");
    expect(types).not.toContain("export type Views<");
  });

  it("type-checks public helper shorthands and schema-qualified non-public helpers", async () => {
    const types = await typesFor(helperSql);

    await expectTypeScriptAccepts(`${types}
type Movie = Tables<"movies">;
type MovieView = Tables<"movie_names">;
type MovieInsert = TablesInsert<"movies">;
type MovieUpdate = TablesUpdate<"movies">;
type Visibility = Enums<"visibility">;
type Account = Tables<{ schema: "app" }, "accounts">;
type AccountInsert = TablesInsert<{ schema: "app" }, "accounts">;
type AccountUpdate = TablesUpdate<{ schema: "app" }, "accounts">;
type Status = Enums<{ schema: "app" }, "status">;
type Address = CompositeTypes<{ schema: "app" }, "address">;

const movie: Movie = { id: 1, name: "Heat", visibility: "public" };
const movieView: MovieView = { id: 1, name: "Heat" };
const movieInsert: MovieInsert = { name: "Heat" };
const movieUpdate: MovieUpdate = { name: "Thief" };
const visibility: Visibility = "private";
const account: Account = { id: 1, state: "active", home: { street: "Main", zip: 1 } };
const accountInsert: AccountInsert = { state: "draft" };
const accountUpdate: AccountUpdate = { state: "active" };
const status: Status = "draft";
const address: Address = { street: "Main", zip: 1 };
void movie;
void movieView;
void movieInsert;
void movieUpdate;
void visibility;
void account;
void accountInsert;
void accountUpdate;
void status;
void address;
`);
  }, 15_000);

  it("emits TypeScript and Zod output from one precomputed shape graph", async () => {
    const model = await modelFor(treeSql, "supa-typegen-shapes-");
    const shapes = await collectSchemaShapes(model);

    expect(generateDatabaseTypes(shapes)).toContain("export type Database = {");
    expect(generateZodSchemas(shapes)).toContain("export const Tables = {");
  });
});

const hardenedSql = `CREATE SCHEMA app;
CREATE SCHEMA audit;
CREATE DOMAIN app.email AS text;
CREATE TYPE app.status AS ENUM ('draft', 'active');
CREATE TYPE audit.status AS ENUM ('ok', 'bad');
CREATE TABLE app.users (
  id bigint GENERATED ALWAYS AS IDENTITY,
  contact app.email NOT NULL,
  state status NOT NULL
);
ALTER TABLE ONLY app.users ADD CONSTRAINT users_pkey PRIMARY KEY (id);
CREATE TABLE audit.logs (
  id bigint PRIMARY KEY,
  state status NOT NULL,
  user_id bigint UNIQUE REFERENCES app.users
);
CREATE VIEW app.user_emails (uid, mail) AS SELECT id, contact FROM app.users;
CREATE VIEW app.all_users AS SELECT u.* FROM app.users u;
CREATE FUNCTION app.get_user(uid bigint, fallback text DEFAULT 'none') RETURNS SETOF text LANGUAGE sql AS $$ SELECT contact FROM app.users $$;
`;

describe("review-hardened typegen", () => {
  it("treats always-generated identity as never and standalone primary keys as not null", async () => {
    const types = await typesFor(hardenedSql);
    const users = types.slice(types.indexOf("users: {"), types.indexOf("user_emails"));

    expect(users).toContain("id: number;");
    expect(users).toContain("id?: never;");
  });

  it("maps domains to their base type and resolves shadowed enums schema-locally", async () => {
    const types = await typesFor(hardenedSql);

    expect(types).toContain("contact: string;");
    const users = types.slice(types.indexOf("users: {"), types.indexOf("Views"));
    expect(users).toContain('state: Database["app"]["Enums"]["status"];');
    const logs = types.slice(types.indexOf("logs: {"));
    expect(logs).toContain('state: Database["audit"]["Enums"]["status"];');
  });

  it("resolves shorthand foreign keys to the target primary key and marks unique FKs one-to-one", async () => {
    const types = await typesFor(hardenedSql);

    expect(types).toContain('referencedRelation: "users"');
    expect(types).toContain('referencedColumns: ["id"]');
    expect(types).toContain("isOneToOne: true");
  });

  it("maps alias-list view columns positionally and expands qualified star selects", async () => {
    const types = await typesFor(hardenedSql);
    const views = types.slice(types.indexOf("Views: {"), types.indexOf("Enums: {"));

    expect(views).toContain("uid: number | null;");
    expect(views).toContain("mail: string | null;");
    expect(views).toContain("contact: string | null;");
  });

  it("populates Functions with named args, optionality, and setof returns", async () => {
    const types = await typesFor(hardenedSql);

    expect(types).toContain(
      "get_user: { Args: { uid: number; fallback?: string }; Returns: string[] };"
    );
  });
});

const overloadedSql = `CREATE SCHEMA app;
CREATE FUNCTION app.f(a integer) RETURNS integer LANGUAGE sql AS $$ SELECT a $$;
CREATE FUNCTION app.f(a text) RETURNS text LANGUAGE sql AS $$ SELECT a $$;
`;

describe("overloaded function typegen", () => {
  it("unions every overload instead of silently keeping the first", async () => {
    const types = await typesFor(overloadedSql);

    expect(types).toContain(
      "f: { Args: { a: number } | { a: string }; Returns: number | string };"
    );
  });
});

const compositeSql = `CREATE SCHEMA app;
CREATE TYPE app.address AS (street text, zip int);
CREATE TYPE app.intrange AS RANGE (subtype = int4);
CREATE TABLE app.people (id bigint, home app.address);
`;

describe("composite and range type typegen", () => {
  it("resolves a column of a declared composite type to its CompositeTypes entry", async () => {
    const types = await typesFor(compositeSql);

    expect(types).toContain('home: Database["app"]["CompositeTypes"]["address"] | null;');
    expect(types).toContain("CompositeTypes: {");
    expect(collapseWhitespace(types)).toContain(
      "address: { street: string | null; zip: number | null;"
    );
  });

  it("does not emit a range type as an empty composite", async () => {
    const types = await typesFor(compositeSql);

    expect(collapseWhitespace(types)).not.toContain("intrange: {}");
  });

  it("prefers a schema-local composite over a same-named enum in another schema", async () => {
    const types = await typesFor(
      `CREATE SCHEMA app;
CREATE TYPE app.address AS (street text, zip int);
CREATE TYPE public.address AS ENUM ('home', 'work');
CREATE TABLE app.people (id bigint, home address);
`
    );

    expect(types).toContain('home: Database["app"]["CompositeTypes"]["address"] | null;');
    expect(types).not.toContain('home: Database["public"]["Enums"]["address"] | null;');
  });

  it("treats a bare name shared by an enum and a composite as ambiguous (unknown)", async () => {
    const types = await typesFor(
      `CREATE SCHEMA app;
CREATE SCHEMA a;
CREATE SCHEMA b;
CREATE TYPE a.thing AS ENUM ('x');
CREATE TYPE b.thing AS (n int);
CREATE TABLE app.t (id bigint, v thing);
`
    );

    expect(types).toContain("v: unknown | null;");
    expect(types).not.toContain('Database["a"]["Enums"]["thing"]');
  });
});

const returnShapeSql = `CREATE SCHEMA app;
CREATE FUNCTION app.list_people() RETURNS TABLE (id bigint, label text) LANGUAGE sql AS $$ SELECT 1::bigint, 'x'::text $$;
CREATE FUNCTION app.one_row(OUT a int, OUT b text) LANGUAGE sql AS $$ SELECT 1, 'y' $$;
CREATE FUNCTION app.single_out(OUT x int) LANGUAGE sql AS $$ SELECT 1 $$;
`;

describe("function return row typegen", () => {
  it("preserves RETURNS TABLE and OUT-parameter row shapes", async () => {
    const types = await typesFor(returnShapeSql);

    expect(types).toContain(
      "list_people: { Args: Record<PropertyKey, never>; Returns: { id: number; label: string }[] };"
    );
    expect(types).toContain(
      "one_row: { Args: Record<PropertyKey, never>; Returns: { a: number; b: string } };"
    );
  });

  it("keeps a single OUT parameter scalar instead of a one-field record", async () => {
    const types = await typesFor(returnShapeSql);

    expect(types).toContain("single_out: { Args: Record<PropertyKey, never>; Returns: number };");
    expect(types).not.toContain("single_out: { Args: Record<PropertyKey, never>; Returns: { x:");
  });
});

describe("zod schema generation", () => {
  async function zodFor(sql: string): Promise<string> {
    const model = await modelFor(sql, "supa-zodgen-");
    return generateZodSchemas(await collectSchemaShapes(model));
  }

  it("emits runtime validators mirroring the generated types", async () => {
    const zod = await zodFor(treeSql);

    expect(zod).toContain('import { z } from "zod";');
    expect(zod).toContain('const app_status = z.enum(["draft", "active"]);');
    expect(zod).toContain("export const jsonSchema: z.ZodType<Json>");
    expect(zod).toContain("name: z.string(),");
    expect(zod).toContain("email: z.string().nullable(),");
    expect(zod).toContain("tags: z.array(z.string()),");
    expect(zod).toContain("payload: jsonSchema.nullable(),");
    expect(zod).toContain("state: app_status,");
    expect(zod).toContain("export const Tables = {");
    expect(zod).toContain("export const TablesInsert = {");
    expect(zod).toContain("export const TablesUpdate = {");
    expect(zod).toContain("export const Enums = {");
    expect(zod).toContain("export const CompositeTypes = {");
    expect(zod).toContain("account_names");
    expect(zod).toContain("export type Tables<");
    expect(zod).toContain("export type TablesInsert<");
    expect(zod).toContain("export type Enums<");
    expect(zod).not.toContain("export const schemas = {");
    expect(zod).not.toContain("export type TableRow<");
    expect(zod).not.toContain("export type EnumValue<");
  });

  it("type-checks direct runtime owners and Supabase-shaped Zod helper aliases", async () => {
    const zod = await zodFor(helperSql);

    await expectTypeScriptAccepts(`${zod}
type Movie = Tables<"movies">;
type MovieView = Tables<"movie_names">;
type MovieInsert = TablesInsert<"movies">;
type MovieUpdate = TablesUpdate<"movies">;
type Visibility = Enums<"visibility">;
type Account = Tables<{ schema: "app" }, "accounts">;
type AccountInsert = TablesInsert<{ schema: "app" }, "accounts">;
type AccountUpdate = TablesUpdate<{ schema: "app" }, "accounts">;
type Status = Enums<{ schema: "app" }, "status">;
type Address = CompositeTypes<{ schema: "app" }, "address">;

const movie: Movie = Tables.public.movies.Row.parse({ id: 1, name: "Heat", visibility: "public" });
const movieView: MovieView = Tables.public.movie_names.Row.parse({ id: 1, name: "Heat" });
const movieInsert: MovieInsert = TablesInsert.public.movies.parse({ name: "Heat" });
const movieUpdate: MovieUpdate = TablesUpdate.public.movies.parse({ name: "Thief" });
const visibility: Visibility = Enums.public.visibility.parse("private");
const account: Account = Tables.app.accounts.Row.parse({
  id: 1,
  state: "active",
  home: { street: "Main", zip: 1 },
});
const accountInsert: AccountInsert = TablesInsert.app.accounts.parse({ state: "draft" });
const accountUpdate: AccountUpdate = TablesUpdate.app.accounts.parse({ state: "active" });
const status: Status = Enums.app.status.parse("draft");
const address: Address = CompositeTypes.app.address.parse({ street: "Main", zip: 1 });
void movie;
void movieView;
void movieInsert;
void movieUpdate;
void visibility;
void account;
void accountInsert;
void accountUpdate;
void status;
void address;
`);
  }, 15_000);

  it("uses one identifier namespace for enum and composite validators", async () => {
    const zod = await zodFor(`CREATE SCHEMA "tenant-a";
CREATE SCHEMA tenant_a;
CREATE TYPE "tenant-a".status AS ENUM ('active');
CREATE TYPE tenant_a.status AS (value text);
`);

    expect(zod).toContain('const tenant_a_status = z.enum(["active"]);');
    expect(zod).toContain("const tenant_a_status_2 = z.object({");
    const lines = zod.split("\n");
    expect(lines.filter((line) => line.startsWith("const tenant_a_status ="))).toHaveLength(1);
    expect(lines.filter((line) => line.startsWith("const tenant_a_status_2 ="))).toHaveLength(1);
  });

  it("validates composite-typed columns with generated composite object schemas", async () => {
    const zod = await zodFor(
      `CREATE SCHEMA app;
CREATE TYPE app.address AS (street text, zip int);
CREATE TABLE app.people (id bigint, home app.address);
`
    );

    expect(zod).not.toContain("z.composite()");
    expect(zod).toContain("const app_address = z.object({");
    expect(zod).toContain("street: z.string().nullable(),");
    expect(zod).toContain("zip: z.number().nullable(),");
    expect(zod).toContain("export const CompositeTypes = {");
    expect(zod).toContain("home: app_address.nullable(),");
    expect(zod).toContain("export type CompositeTypes<");
  });

  it("defers composite references so declaration order cannot trigger TDZ", async () => {
    const zod = await zodFor(
      `CREATE SCHEMA app;
CREATE TYPE app.z AS (value text);
CREATE TYPE app.a AS (z app.z);
`
    );
    const typescript = await import("typescript");
    const root = join(process.cwd(), ".tmp");
    await mkdir(root, { recursive: true });
    const modulePath = join(await mkdtemp(join(root, "supa-zod-runtime-")), "schemas.mjs");
    const js = typescript.transpileModule(zod, {
      compilerOptions: {
        module: typescript.ModuleKind.ES2022,
        target: typescript.ScriptTarget.ES2022,
      },
    }).outputText;

    expect(zod).toContain("get z() {");
    await writeFile(modulePath, js);
    const imported = await import(`${pathToFileURL(modulePath).href}?t=${Date.now()}`);
    expect(imported.CompositeTypes.app.a.parse({ z: { value: "ok" } })).toEqual({
      z: { value: "ok" },
    });
  });

  it("derives insert optionality and omits generated columns from writes", async () => {
    const zod = await zodFor(treeSql);
    const account = zod.slice(zod.indexOf("accounts: {"), zod.indexOf("events: {"));
    const insert = account.slice(
      account.indexOf("Insert: z.object({"),
      account.indexOf("Update: z.object({")
    );

    expect(insert).toContain("id: z.number().optional(),");
    expect(insert).toContain("name: z.string(),");
    expect(insert).toContain("email: z.string().nullable().optional(),");
    expect(insert).not.toContain("doubled");
    const update = account.slice(account.indexOf("Update: z.object({"));
    expect(update).toContain("name: z.string().optional(),");
    expect(update).not.toContain("doubled");
  });
});
