import { mkdtemp, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { extractSourceModel } from "../src/source.js";
import { generateDatabaseTypes } from "../src/typegen.js";
import { generateZodSchemas } from "../src/typegen-zod.js";

const treeSql = `CREATE SCHEMA app;
CREATE TYPE app.status AS ENUM ('draft', 'active');
CREATE TABLE app.accounts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  email text,
  score numeric(10, 2) DEFAULT 0,
  tags text[] NOT NULL DEFAULT '{}',
  payload jsonb,
  state app.status NOT NULL DEFAULT 'draft',
  active boolean NOT NULL DEFAULT true,
  doubled integer GENERATED ALWAYS AS (1 + 1) STORED
);
CREATE TABLE app.events (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  account_id bigint NOT NULL CONSTRAINT events_account_fk REFERENCES app.accounts (id)
);
CREATE VIEW app.account_names AS SELECT id, name AS label FROM app.accounts;
CREATE VIEW app.account_all AS SELECT * FROM app.accounts;
`;

async function typesFor(sql: string): Promise<string> {
  const root = await mkdtemp(join(tmpdir(), "supa-typegen-"));
  await writeFile(join(root, "001_app.sql"), sql);
  const model = await extractSourceModel(`dir:${root}`);
  expect(model.diagnostics.filter((item) => item.severity === "error")).toEqual([]);
  return await generateDatabaseTypes(model);
}

describe("database type generation", () => {
  it("types tables, enums, views, and relationships without a database", async () => {
    const types = await typesFor(treeSql);

    expect(types).toContain("export type Database = {");
    expect(types).toContain('"draft" | "active"');
    expect(types).toContain("id: number;");
    expect(types).toContain("name: string;");
    expect(types).toContain("email: string | null;");
    expect(types).toContain("score: number | null;");
    expect(types).toContain("tags: string[];");
    expect(types).toContain("payload: Json | null;");
    expect(types).toContain('state: Database["app"]["Enums"]["status"];');
    expect(types).toContain("active: boolean;");
    expect(types).toContain('foreignKeyName: "events_account_fk"');
    expect(types).toContain('referencedRelation: "accounts"');
  });

  it("derives insert and update optionality from defaults, identity, and nullability", async () => {
    const types = await typesFor(treeSql);
    const insert = types.slice(types.indexOf("Insert: {"), types.indexOf("Update: {"));

    expect(insert).toContain("id?: number;");
    expect(insert).toContain("name: string;");
    expect(insert).toContain("email?: string | null;");
    expect(insert).toContain("score?: number | null;");
    expect(insert).toContain("doubled?: never;");
    const update = types.slice(types.indexOf("Update: {"), types.indexOf("Relationships:"));
    expect(update).toContain("name?: string;");
    expect(update).toContain("doubled?: never;");
  });

  it("resolves view columns through their source table and expands star selects", async () => {
    const types = await typesFor(treeSql);
    const views = types.slice(types.indexOf("Views: {"), types.indexOf("Enums: {"));

    expect(views).toContain("id: number | null;");
    expect(views).toContain("label: string | null;");
    expect(views).toContain("payload: Json | null;");
  });

  it("emits the Constants enum tuples and helper generics", async () => {
    const types = await typesFor(treeSql);

    expect(types).toContain("export const Constants = {");
    expect(types).toContain('status: ["draft", "active"],');
    expect(types).toContain("export type Tables<");
    expect(types).toContain("export type Enums<");
  });
});

const hardenedSql = `CREATE SCHEMA app;
CREATE SCHEMA audit;
CREATE DOMAIN app.email AS text;
CREATE TYPE app.status AS ENUM ('draft', 'active');
CREATE TYPE audit.status AS ENUM ('ok', 'bad');
CREATE TABLE app.users (
  id bigint GENERATED ALWAYS AS IDENTITY,
  contact app.email NOT NULL,
  state status NOT NULL
);
ALTER TABLE ONLY app.users ADD CONSTRAINT users_pkey PRIMARY KEY (id);
CREATE TABLE audit.logs (
  id bigint PRIMARY KEY,
  state status NOT NULL,
  user_id bigint UNIQUE REFERENCES app.users
);
CREATE VIEW app.user_emails (uid, mail) AS SELECT id, contact FROM app.users;
CREATE VIEW app.all_users AS SELECT u.* FROM app.users u;
CREATE FUNCTION app.get_user(uid bigint, fallback text DEFAULT 'none') RETURNS SETOF text LANGUAGE sql AS $$ SELECT contact FROM app.users $$;
`;

describe("review-hardened typegen", () => {
  it("treats always-generated identity as never and standalone primary keys as not null", async () => {
    const types = await typesFor(hardenedSql);
    const users = types.slice(types.indexOf("users: {"), types.indexOf("user_emails"));

    expect(users).toContain("id: number;");
    expect(users).toContain("id?: never;");
  });

  it("maps domains to their base type and resolves shadowed enums schema-locally", async () => {
    const types = await typesFor(hardenedSql);

    expect(types).toContain("contact: string;");
    const users = types.slice(types.indexOf("users: {"), types.indexOf("Views"));
    expect(users).toContain('state: Database["app"]["Enums"]["status"];');
    const logs = types.slice(types.indexOf("logs: {"));
    expect(logs).toContain('state: Database["audit"]["Enums"]["status"];');
  });

  it("resolves shorthand foreign keys to the target primary key and marks unique FKs one-to-one", async () => {
    const types = await typesFor(hardenedSql);

    expect(types).toContain('referencedRelation: "users"');
    expect(types).toContain('referencedColumns: ["id"]');
    expect(types).toContain("isOneToOne: true");
  });

  it("maps alias-list view columns positionally and expands qualified star selects", async () => {
    const types = await typesFor(hardenedSql);
    const views = types.slice(types.indexOf("Views: {"), types.indexOf("Enums: {"));

    expect(views).toContain("uid: number | null;");
    expect(views).toContain("mail: string | null;");
    expect(views).toContain("contact: string | null;");
  });

  it("populates Functions with named args, optionality, and setof returns", async () => {
    const types = await typesFor(hardenedSql);

    expect(types).toContain(
      "get_user: { Args: { uid: number; fallback?: string }; Returns: string[] };",
    );
  });
});

const overloadedSql = `CREATE SCHEMA app;
CREATE FUNCTION app.f(a integer) RETURNS integer LANGUAGE sql AS $$ SELECT a $$;
CREATE FUNCTION app.f(a text) RETURNS text LANGUAGE sql AS $$ SELECT a $$;
`;

describe("overloaded function typegen", () => {
  it("unions every overload instead of silently keeping the first", async () => {
    const types = await typesFor(overloadedSql);

    expect(types).toContain(
      "f: { Args: { a: number } | { a: string }; Returns: number | string };",
    );
  });
});

describe("zod schema generation", () => {
  async function zodFor(sql: string): Promise<string> {
    const root = await mkdtemp(join(tmpdir(), "supa-zodgen-"));
    await writeFile(join(root, "001_app.sql"), sql);
    const model = await extractSourceModel(`dir:${root}`);
    expect(model.diagnostics.filter((item) => item.severity === "error")).toEqual([]);
    return await generateZodSchemas(model);
  }

  it("emits runtime validators mirroring the generated types", async () => {
    const zod = await zodFor(treeSql);

    expect(zod).toContain('import { z } from "zod";');
    expect(zod).toContain('const app_status = z.enum(["draft", "active"]);');
    expect(zod).toContain("export const jsonSchema: z.ZodType<Json>");
    expect(zod).toContain("name: z.string(),");
    expect(zod).toContain("email: z.string().nullable(),");
    expect(zod).toContain("tags: z.array(z.string()),");
    expect(zod).toContain("payload: jsonSchema.nullable(),");
    expect(zod).toContain("state: app_status,");
  });

  it("derives insert optionality and omits generated columns from writes", async () => {
    const zod = await zodFor(treeSql);
    const insert = zod.slice(zod.indexOf("Insert: z.object({"), zod.indexOf("Update: z.object({"));

    expect(insert).toContain("id: z.number().optional(),");
    expect(insert).toContain("name: z.string(),");
    expect(insert).toContain("email: z.string().nullable().optional(),");
    expect(insert).not.toContain("doubled");
    const update = zod.slice(zod.indexOf("Update: z.object({"), zod.indexOf("Views: {"));
    expect(update).toContain("name: z.string().optional(),");
    expect(update).not.toContain("doubled");
  });
});
