import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { resolveConfig } from "../../src/config/schema.js";
import { generateTypeContracts } from "../../src/typegen/contracts.js";

const tempRoots: string[] = [];

afterEach(async () => {
  await Promise.all(tempRoots.splice(0).map((root) => rm(root, { force: true, recursive: true })));
});

async function contractProject() {
  const root = await mkdtemp(join(tmpdir(), "supa-typegen-check-"));
  tempRoots.push(root);
  const schemas = join(root, "schemas");
  await mkdir(schemas);
  await writeFile(
    join(schemas, "app.sql"),
    "CREATE TABLE public.items (id bigint, name text NOT NULL);\n"
  );
  const typesFile = join(root, "database.types.ts");
  const zodFile = join(root, "database.zod.ts");
  const config = resolveConfig({
    schemaPaths: [schemas],
    typesFile,
    workflow: { type_generation: "create_or_refresh", zod_generation: "create_or_refresh" },
    zodFile,
  });
  return { config, root, typesFile, zodFile };
}

describe("generateTypeContracts check mode", () => {
  it("stamps a provenance header into written and stdout contracts", async () => {
    const { config, typesFile } = await contractProject();

    await generateTypeContracts({ config });
    const written = await readFile(typesFile, "utf8");
    expect(written).toContain("// Generated by supaschema");
    expect(written).toContain("// Fingerprint: ");
    expect(written).toContain("Regenerate with: supaschema types");

    const stdoutResult = await generateTypeContracts({ config, out: "stdout" });
    expect(stdoutResult.stdout).toContain("// Generated by supaschema");
    expect(stdoutResult.stdout).toContain("// Fingerprint: ");
  });

  it("passes when on-disk contracts match regenerated output", async () => {
    const { config, typesFile, zodFile } = await contractProject();
    await generateTypeContracts({ config });

    const result = await generateTypeContracts({ check: true, config });

    expect(result.diagnostics.filter((item) => item.severity === "error")).toEqual([]);
    expect(result.checked).toEqual([typesFile, zodFile]);
    expect(result.written).toEqual([]);
  });

  it("reports drift without writing when a contract changed", async () => {
    const { config, typesFile, zodFile } = await contractProject();
    await generateTypeContracts({ config });
    const before = await readFile(typesFile, "utf8");
    await writeFile(typesFile, `${before}// local edit\n`);

    const result = await generateTypeContracts({ check: true, config });

    const drift = result.diagnostics.filter(
      (item) => item.code === "SUPA_TYPES_CONTRACT_DRIFT" && item.severity === "error"
    );
    expect(drift).toHaveLength(1);
    expect(drift[0]?.file).toBe(typesFile);
    expect(drift[0]?.message).toContain("regeneration would change");
    expect(result.checked).toEqual([zodFile]);
    expect(await readFile(typesFile, "utf8")).toBe(`${before}// local edit\n`);
  });

  it("reports a missing contract as drift without creating it", async () => {
    const { config, typesFile } = await contractProject();

    const result = await generateTypeContracts({ check: true, config });

    const drift = result.diagnostics.filter(
      (item) => item.code === "SUPA_TYPES_CONTRACT_DRIFT" && item.severity === "error"
    );
    expect(drift.map((item) => item.file)).toContain(typesFile);
    expect(drift.some((item) => item.message.includes("regeneration would create"))).toBe(true);
    expect(result.checked).toEqual([]);
    await expect(readFile(typesFile, "utf8")).rejects.toThrow();
  });
});
