import { execFile } from "node:child_process";
import { mkdir, mkdtemp, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { pathToFileURL } from "node:url";
import { promisify } from "node:util";
import ts from "typescript-compiler-api";
import { describe, expect, it } from "vitest";
import type { Diagnostic } from "../../src/core.js";
import { extractSourceModel } from "../../src/source/extract.js";
import { extractObjectsFromSql } from "../../src/sql/extract.js";
import { generateDatabaseTypes, quoteCodeString } from "../../src/typegen/database.js";
import { collectSchemaShapes } from "../../src/typegen/model.js";
import { generateZodSchemas } from "../../src/typegen/zod.js";

const execFileAsync = promisify(execFile);

const treeSql = `CREATE SCHEMA app;
CREATE TYPE app.status AS ENUM ('draft', 'active');
CREATE TABLE app.accounts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  email text,
  score numeric(10, 2) DEFAULT 0,
  tags text[] NOT NULL DEFAULT '{}',
  payload jsonb,
  state app.status NOT NULL DEFAULT 'draft',
  active boolean NOT NULL DEFAULT true,
  doubled integer GENERATED ALWAYS AS (1 + 1) STORED
);
CREATE TABLE app.events (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  account_id bigint NOT NULL CONSTRAINT events_account_fk REFERENCES app.accounts (id)
);
CREATE VIEW app.account_names AS SELECT id, name AS label FROM app.accounts;
CREATE VIEW app.account_all AS SELECT * FROM app.accounts;
CREATE VIEW app.account_rollups AS
WITH base AS (
  SELECT a.id,
    a.name,
    COALESCE(a.payload, '{}'::jsonb) AS payload,
    COALESCE(a.state, 'draft'::app.status) AS state,
    row_number() OVER (ORDER BY a.id) AS rank
  FROM app.accounts a
)
SELECT id,
  name AS account_name,
  payload,
  state,
  rank,
  NULLIF(payload ->> 'note'::text, ''::text) AS note
FROM base;
`;

const helperSql = `CREATE SCHEMA app;
CREATE TYPE public.visibility AS ENUM ('private', 'public');
CREATE TYPE app.status AS ENUM ('draft', 'active');
CREATE TYPE app.address AS (street text, zip int);
CREATE TABLE public.movies (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  visibility public.visibility NOT NULL DEFAULT 'public'
);
CREATE VIEW public.movie_names AS SELECT id, name FROM public.movies;
CREATE TABLE app.accounts (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  state app.status NOT NULL DEFAULT 'draft',
  home app.address
);
`;

const nestedViewSql = `CREATE SCHEMA messaging;
CREATE TABLE messaging.threads (
  id bigint,
  contact_email text,
  contact_id text,
  sms_recipients text[],
  primary_contact_id bigint
);
CREATE VIEW messaging.v_thread_message_summaries AS
WITH summary_contract AS (
  SELECT id, contact_email, contact_id, sms_recipients, primary_contact_id
  FROM messaging.threads
)
SELECT
  reply_recipients,
  chat_participant_ids,
  has_sms_consent,
  cardinality(reply_recipients) > 0 AS can_send_email,
  cardinality(chat_participant_ids) > 0 AS can_send_chat,
  primary_contact_id IS NOT NULL
    AND cardinality(sms_recipients) > 0
    AND has_sms_consent AS can_send_sms
FROM (
  SELECT
    sc.primary_contact_id,
    sc.sms_recipients,
    recipients.reply_recipients,
    recipients.chat_participant_ids,
    EXISTS (
      SELECT 1
      FROM messaging.threads check_thread
      WHERE check_thread.id = sc.id
    ) AS has_sms_consent
  FROM summary_contract sc
  LEFT JOIN LATERAL (
    WITH human_participants AS (
      SELECT sc.contact_email AS email, sc.contact_id AS id
    )
    SELECT
      COALESCE(ARRAY(
        SELECT DISTINCT lower(btrim(human_participants.email))
        FROM human_participants
        WHERE NULLIF(btrim(human_participants.email), ''::text) IS NOT NULL
      ), ARRAY[]::text[]) AS reply_recipients,
      COALESCE(ARRAY(
        SELECT DISTINCT btrim(human_participants.id)
        FROM human_participants
        WHERE NULLIF(btrim(human_participants.id), ''::text) IS NOT NULL
      ), ARRAY[]::text[]) AS chat_participant_ids
  ) recipients ON true
) source_rows;
`;

async function typesFor(sql: string): Promise<string> {
  const model = await modelFor(sql, "supa-typegen-");
  return generateDatabaseTypes(await collectSchemaShapes(model));
}

async function modelFor(sql: string, prefix: string) {
  const root = await mkdtemp(join(tmpdir(), prefix));
  await writeFile(join(root, "001_app.sql"), sql);
  const model = await extractSourceModel(`dir:${root}`);
  const errors = model.diagnostics.filter((item) => item.severity === "error");
  if (errors.length > 0) {
    throw new Error(`expected source extraction to succeed: ${JSON.stringify(errors)}`);
  }
  return model;
}

function collapseWhitespace(value: string): string {
  const words: string[] = [];
  let current = "";
  for (const char of value) {
    if (isWhitespace(char)) {
      if (current.length > 0) {
        words.push(current);
        current = "";
      }
    } else {
      current += char;
    }
  }
  if (current.length > 0) {
    words.push(current);
  }
  return words.join(" ");
}

function isWhitespace(char: string): boolean {
  return char === " " || char === "\n" || char === "\r" || char === "\t" || char === "\f";
}

function viewTypeBlock(types: string, name: string): string {
  return generatedTypeBlock(types, name, "Row");
}

function generatedTypeBlock(
  types: string,
  name: string,
  shape: "Insert" | "Row" | "Update"
): string {
  const relationStart = types.indexOf(`      ${name}: {`);
  if (relationStart === -1) {
    return "";
  }
  const relationEnd = types.indexOf("\n      };", relationStart);
  const start = types.indexOf(`        ${shape}: {`, relationStart);
  if (start === -1 || (relationEnd !== -1 && start > relationEnd)) {
    return "";
  }
  const end = types.indexOf("\n        };", start);
  return end === -1 ? types.slice(start) : types.slice(start, end + 3);
}

async function expectTypeScriptAccepts(source: string): Promise<void> {
  const tmpRoot = join(process.cwd(), ".tmp");
  await mkdir(tmpRoot, { recursive: true });
  const root = await mkdtemp(join(tmpRoot, "supa-typegen-ts-"));
  const file = join(root, "generated-types.ts");
  const config = join(root, "tsconfig.json");
  await writeFile(file, source);
  await writeFile(
    config,
    `${JSON.stringify(
      {
        compilerOptions: {
          module: "NodeNext",
          moduleResolution: "NodeNext",
          noEmit: true,
          skipLibCheck: true,
          strict: true,
          target: "ES2022",
        },
        files: ["generated-types.ts"],
      },
      null,
      2
    )}\n`
  );
  try {
    await execFileAsync(
      process.execPath,
      [typescriptCompilerPath(), "--project", config, "--pretty", "false"],
      {
        cwd: root,
        maxBuffer: 1024 * 1024,
      }
    );
  } catch (error) {
    throw new Error(commandErrorOutput(error), { cause: error });
  }
}

function typescriptCompilerPath(): string {
  return join(process.cwd(), "node_modules", "typescript", "bin", "tsc");
}

function commandErrorOutput(error: unknown): string {
  if (error instanceof Error) {
    return [commandErrorField(error, "stdout"), commandErrorField(error, "stderr"), error.message]
      .filter(Boolean)
      .join("\n");
  }
  return String(error);
}

function commandErrorField(error: Error, field: "stderr" | "stdout"): string | undefined {
  const value = Reflect.get(error, field);
  return typeof value === "string" ? value : undefined;
}

function canonicalDeclaration(source: string, name: string): string | undefined {
  const sourceFile = ts.createSourceFile(
    "database.types.ts",
    source,
    ts.ScriptTarget.Latest,
    true,
    ts.ScriptKind.TS
  );
  const statement = sourceFile.statements.find((candidate) => {
    if (ts.isTypeAliasDeclaration(candidate)) {
      return candidate.name.text === name;
    }
    return (
      ts.isVariableStatement(candidate) &&
      candidate.declarationList.declarations.some(
        (declaration) => ts.isIdentifier(declaration.name) && declaration.name.text === name
      )
    );
  });
  return statement
    ? ts
        .createPrinter({ removeComments: true })
        .printNode(ts.EmitHint.Unspecified, statement, sourceFile)
    : undefined;
}

describe("database type generation", () => {
  it("types tables, enums, views, and relationships without a database", async () => {
    const types = await typesFor(treeSql);

    expect(types).toContain("export type Database = {");
    expect(types).toContain('"draft" | "active"');
    expect(types).toContain("id: number;");
    expect(types).toContain("name: string;");
    expect(types).toContain("email: string | null;");
    expect(types).toContain("score: number | null;");
    expect(types).toContain("tags: string[];");
    expect(types).toContain("payload: Json | null;");
    expect(types).toContain('state: Database["app"]["Enums"]["status"];');
    expect(types).toContain("active: boolean;");
    expect(types).toContain('foreignKeyName: "events_account_fk"');
    expect(types).toContain('referencedRelation: "accounts"');
  });

  it("derives insert and update optionality from defaults, identity, and nullability", async () => {
    const types = await typesFor(treeSql);
    const insert = generatedTypeBlock(types, "accounts", "Insert");

    expect(insert).toContain("id?: number;");
    expect(insert).toContain("name: string;");
    expect(insert).toContain("email?: string | null;");
    expect(insert).toContain("score?: number | null;");
    expect(insert).toContain("doubled?: never;");
    const update = generatedTypeBlock(types, "accounts", "Update");
    expect(update).toContain("name?: string;");
    expect(update).toContain("doubled?: never;");
  });

  it("resolves view columns through their source table and expands star selects", async () => {
    const types = await typesFor(treeSql);
    const views = `${viewTypeBlock(types, "account_names")}\n${viewTypeBlock(types, "account_all")}`;

    expect(views).toContain("id: number | null;");
    expect(views).toContain("label: string | null;");
    expect(views).toContain("payload: Json | null;");
    expect(types).toContain("Relationships: [];");
  });

  it("emits write contracts only for automatically updatable views", async () => {
    const types = await typesFor(`CREATE SCHEMA app;
CREATE TABLE app.accounts (id bigint, name text);
CREATE FUNCTION app.expand_id(bigint) RETURNS SETOF bigint LANGUAGE sql AS $$ SELECT $1 $$;
CREATE VIEW app.account_labels AS SELECT id, upper(name) AS label FROM app.accounts;
CREATE VIEW app.account_aliases (account_id, account_name) AS SELECT id, name FROM app.accounts;
CREATE VIEW app.account_expanded AS SELECT *, upper(name) AS label FROM app.accounts;
CREATE VIEW app.account_expanded_implicit AS SELECT *, upper(name) FROM app.accounts;
CREATE VIEW app.account_custom_series AS SELECT app.expand_id(id) AS id FROM app.accounts;
CREATE VIEW app.account_totals AS SELECT count(id) AS total FROM app.accounts;
CREATE VIEW app.account_ranks AS SELECT row_number() OVER () AS rank FROM app.accounts;
CREATE VIEW app.account_series AS SELECT generate_series(1, 2) AS value FROM app.accounts;
CREATE MATERIALIZED VIEW app.account_snapshot AS SELECT id, name FROM app.accounts;
`);
    const insert = generatedTypeBlock(types, "account_labels", "Insert");
    const update = generatedTypeBlock(types, "account_labels", "Update");

    expect(insert).toContain("id?: number | null;");
    expect(insert).toContain("label?: never;");
    expect(update).toContain("id?: number | null;");
    expect(update).toContain("label?: never;");
    const aliasesInsert = generatedTypeBlock(types, "account_aliases", "Insert");
    expect(aliasesInsert).toContain("account_id?: number | null;");
    expect(aliasesInsert).toContain("account_name?: string | null;");
    const expandedInsert = generatedTypeBlock(types, "account_expanded", "Insert");
    expect(expandedInsert).toContain("id?: number | null;");
    expect(expandedInsert).toContain("name?: string | null;");
    expect(expandedInsert).toContain("label?: never;");
    const implicitInsert = generatedTypeBlock(types, "account_expanded_implicit", "Insert");
    expect(implicitInsert).toContain("id?: number | null;");
    expect(implicitInsert).toContain("upper?: never;");
    expect(generatedTypeBlock(types, "account_totals", "Insert")).toBe("");
    expect(generatedTypeBlock(types, "account_totals", "Update")).toBe("");
    expect(generatedTypeBlock(types, "account_ranks", "Insert")).toBe("");
    expect(generatedTypeBlock(types, "account_series", "Insert")).toBe("");
    expect(generatedTypeBlock(types, "account_custom_series", "Insert")).toBe("");
    expect(generatedTypeBlock(types, "account_snapshot", "Insert")).toBe("");
    expect(generatedTypeBlock(types, "account_snapshot", "Update")).toBe("");
  });

  it("matches upstream scalar mappings and unknown fallbacks", async () => {
    const types = await typesFor(`CREATE SCHEMA app;
CREATE TABLE app.scalar_types (
  embedding vector(3),
  unsupported_half halfvec,
  unsupported_oid oid,
  unsupported_inet inet,
  unsupported_cidr cidr,
  unsupported_mac macaddr,
  unsupported_name name,
  unsupported_xml xml
);
CREATE FUNCTION app.returns_void() RETURNS void LANGUAGE sql AS $$ SELECT NULL::void $$;
CREATE FUNCTION app.returns_record() RETURNS record LANGUAGE sql AS $$ SELECT ROW(1) $$;
`);

    expect(types).toContain("embedding: string | null;");
    for (const column of [
      "unsupported_half",
      "unsupported_oid",
      "unsupported_inet",
      "unsupported_cidr",
      "unsupported_mac",
      "unsupported_name",
      "unsupported_xml",
    ]) {
      expect(types).toContain(`${column}: unknown;`);
    }
    expect(types).toContain("returns_void: { Args: never; Returns: undefined };");
    expect(types).toContain("returns_record: { Args: never; Returns: Record<string, unknown> };");
  });

  it("keeps view rows nullable across outer joins", async () => {
    const types = await typesFor(`CREATE SCHEMA app;
CREATE TABLE app.accounts (id bigint NOT NULL);
CREATE TABLE app.profiles (profile_id bigint NOT NULL, account_id bigint NOT NULL);
CREATE VIEW app.account_profiles AS
SELECT accounts.id AS account_id, profiles.profile_id
FROM app.accounts
LEFT JOIN app.profiles ON profiles.account_id = accounts.id;
`);
    const row = viewTypeBlock(types, "account_profiles");

    expect(row).toContain("account_id: number | null;");
    expect(row).toContain("profile_id: number | null;");
  });

  it("resolves CTE-backed view columns and typed expressions", async () => {
    const types = await typesFor(treeSql);
    const rollup = viewTypeBlock(types, "account_rollups");

    expect(rollup).toContain("id: number | null;");
    expect(rollup).toContain("account_name: string | null;");
    expect(rollup).toContain("payload: Json | null;");
    expect(rollup).toContain('state: Database["app"]["Enums"]["status"] | null;');
    expect(rollup).toContain("rank: number | null;");
    expect(rollup).toContain("note: string | null;");
  });

  it("resolves nested view columns from subqueries, array sublinks, and boolean expressions", async () => {
    const types = await typesFor(nestedViewSql);
    const views = viewTypeBlock(types, "v_thread_message_summaries");

    expect(views).toContain("reply_recipients: string[] | null;");
    expect(views).toContain("chat_participant_ids: string[] | null;");
    expect(views).toContain("has_sms_consent: boolean | null;");
    expect(views).toContain("can_send_email: boolean | null;");
    expect(views).toContain("can_send_chat: boolean | null;");
    expect(views).toContain("can_send_sms: boolean | null;");
  });

  it("keeps CTE names from shadowing schema-qualified table references", async () => {
    const types = await typesFor(`CREATE SCHEMA app;
CREATE TABLE app.source (id bigint, app_value text);
CREATE VIEW app.v_collision AS
WITH source AS (SELECT 1::integer AS id, 'cte'::text AS cte_value)
SELECT app.source.app_value FROM app.source;
`);
    const views = viewTypeBlock(types, "v_collision");

    expect(views).toContain("app_value: string | null;");
    expect(views).not.toContain("app_value: unknown | null;");
  });

  it("resolves top-level CTEs used inside set-operation views", async () => {
    const types = await typesFor(`CREATE SCHEMA app;
CREATE TABLE app.events (id bigint, payload jsonb);
CREATE VIEW app.v_event_payloads AS
WITH source AS (SELECT id, payload FROM app.events)
SELECT id, payload FROM source
UNION ALL
SELECT id, payload FROM app.events;
`);
    const view = viewTypeBlock(types, "v_event_payloads");

    expect(view).toContain("id: number | null;");
    expect(view).toContain("payload: Json | null;");
    expect(view).not.toContain("unknown | null;");
  });

  it("types jsonb concat view expressions as Json", async () => {
    const types = await typesFor(`CREATE SCHEMA app;
CREATE TABLE app.events (payload jsonb);
CREATE VIEW app.v_event_payloads AS
SELECT payload || '{"source":"app"}'::jsonb AS merged_payload FROM app.events;
`);
    const view = viewTypeBlock(types, "v_event_payloads");

    expect(view).toContain("merged_payload: Json | null;");
    expect(view).not.toContain("merged_payload: string | null;");
    expect(view).not.toContain("merged_payload: unknown | null;");
  });

  it("keeps qualified star expansion scoped to the matched join source", async () => {
    const types = await typesFor(`CREATE SCHEMA app;
CREATE TABLE app.accounts (id bigint, name text);
CREATE TABLE app.events (id bigint, account_id bigint, payload jsonb);
CREATE VIEW app.account_only AS
SELECT a.* FROM app.accounts a JOIN app.events e ON e.account_id = a.id;
`);
    const accountOnly = viewTypeBlock(types, "account_only");

    expect(accountOnly).toContain("id: number | null;");
    expect(accountOnly).toContain("name: string | null;");
    expect(accountOnly).not.toContain("account_id:");
    expect(accountOnly).not.toContain("payload:");
  });

  it("merges USING and NATURAL join keys once for unqualified stars", async () => {
    const types = await typesFor(`CREATE SCHEMA app;
CREATE TABLE app.left_items (id bigint, left_name text);
CREATE TABLE app.right_items (id bigint, right_name text);
CREATE VIEW app.using_join AS
SELECT * FROM app.left_items JOIN app.right_items USING (id);
CREATE VIEW app.natural_join AS
SELECT * FROM app.left_items NATURAL JOIN app.right_items;
`);
    const usingJoin = viewTypeBlock(types, "using_join");
    const naturalJoin = viewTypeBlock(types, "natural_join");

    expect(
      usingJoin.split("\n").filter((line) => line.trim() === "id: number | null;")
    ).toHaveLength(1);
    expect(usingJoin).toContain("left_name: string | null;");
    expect(usingJoin).toContain("right_name: string | null;");
    expect(
      naturalJoin.split("\n").filter((line) => line.trim() === "id: number | null;")
    ).toHaveLength(1);
  });

  it("preserves aliases on joined FROM items", async () => {
    const types = await typesFor(`CREATE SCHEMA app;
CREATE TABLE app.accounts (id bigint, email text);
CREATE TABLE app.profiles (id bigint, display_name text);
CREATE VIEW app.join_alias AS
SELECT j.* FROM (app.accounts JOIN app.profiles USING (id)) AS j;
CREATE VIEW app.join_alias_columns AS
SELECT j.email, j.display_name FROM (app.accounts JOIN app.profiles USING (id)) AS j;
`);
    const star = viewTypeBlock(types, "join_alias");
    const columns = viewTypeBlock(types, "join_alias_columns");

    expect(star.split("\n").filter((line) => line.trim() === "id: number | null;")).toHaveLength(1);
    expect(star).toContain("email: string | null;");
    expect(star).toContain("display_name: string | null;");
    expect(columns).toContain("email: string | null;");
    expect(columns).toContain("display_name: string | null;");
    expect(columns).not.toContain("unknown | null;");
  });

  it("threads left-side scope into lateral subselects", async () => {
    const types = await typesFor(`CREATE SCHEMA app;
CREATE TABLE app.accounts (id bigint, email text);
CREATE VIEW app.lateral_email AS
SELECT x.email FROM app.accounts a LEFT JOIN LATERAL (SELECT a.email AS email) x ON true;
`);
    const view = viewTypeBlock(types, "lateral_email");

    expect(view).toContain("email: string | null;");
    expect(view).not.toContain("email: unknown | null;");
  });

  it("resolves schema relation and expression sources used by views", async () => {
    const types = await typesFor(`CREATE SCHEMA app;
CREATE TYPE app.status AS ENUM ('active', 'inactive');
CREATE TABLE app.users (id bigint, email text, payload jsonb, created_at timestamp with time zone);
CREATE TABLE app.embedding_items (id bigint, embedding extensions.vector(3), email extensions.citext);
CREATE FUNCTION app.current_session_context() RETURNS TABLE (subject_id uuid, access_level text) LANGUAGE sql AS $function$ SELECT NULL::uuid, NULL::text $function$;
CREATE FUNCTION app.business_day_diff(start_at date, end_at date) RETURNS integer LANGUAGE sql AS $function$ SELECT 1 $function$;
CREATE FUNCTION app.accept_user(p_user app.users) RETURNS void LANGUAGE sql AS $function$ SELECT NULL::void $function$;
CREATE VIEW app.from_late_view AS SELECT late.email FROM app.late_view late;
CREATE VIEW app.v_users AS SELECT id AS user_id, email FROM app.users;
CREATE TYPE app.user_payload AS (users app.v_users[], owner app.users);
CREATE VIEW app.from_view AS SELECT v.user_id, v.email FROM app.v_users v;
CREATE MATERIALIZED VIEW app.mv_users AS SELECT id, email FROM app.users;
CREATE VIEW app.from_matview AS SELECT m.id, m.email FROM app.mv_users m;
CREATE VIEW app.from_values AS
SELECT disclosure_key, display_order
FROM (VALUES ('credit'::text, 10)) packet(disclosure_key, display_order);
CREATE VIEW app.from_function AS SELECT g.n FROM generate_series(1, 3) AS g(n);
CREATE VIEW app.from_table_function AS
SELECT ctx.subject_id, ctx.access_level FROM app.current_session_context() ctx(subject_id, access_level);
CREATE VIEW app.from_unnest AS SELECT status FROM unnest(enum_range(NULL::app.status)) statuses(status);
CREATE VIEW app.from_set_operation AS
SELECT id, email FROM app.users
UNION
SELECT id, email FROM app.users;
CREATE VIEW app.from_sample AS SELECT users.id FROM app.users TABLESAMPLE SYSTEM (10);
CREATE VIEW app.from_concat AS SELECT concat(email, ':x'::text) AS membership_id FROM app.users;
CREATE VIEW app.from_arithmetic AS SELECT id - 1 AS prior_id FROM app.users;
CREATE VIEW app.from_literals AS SELECT 0 AS emails_sent, true AS enabled, 'label'::text AS label FROM app.users;
CREATE VIEW app.from_scalar_subquery AS SELECT (SELECT count(*) FROM app.users u WHERE u.id = users.id) AS participant_count FROM app.users;
CREATE VIEW app.from_expressions AS
SELECT
  percentile_cont(0.95::double precision) WITHIN GROUP (ORDER BY id::double precision) AS p95_id,
  round(avg(id), 2) AS avg_id,
  (array_agg(email ORDER BY created_at))[1] AS first_email,
  array_fill(0, ARRAY[30]) AS touchpoints,
  NULLIF(payload #>> '{contact,id}'::text[], ''::text) AS contact_id,
  jsonb_array_length(payload #> '{items}'::text[]) AS item_count,
  format('%s:%s'::text, id, email) AS formatted_id,
  substr(replace(upper(email), '@', ':'), 1, 4) AS email_prefix,
  app.business_day_diff(CURRENT_DATE, CURRENT_DATE) AS business_days
FROM app.users
GROUP BY id, email, payload;
CREATE VIEW app.from_pg_catalog AS SELECT c.oid AS object_oid, c.relname AS relation_name FROM pg_class c;
CREATE VIEW app.from_pg_cron AS SELECT job.jobid, job.jobname FROM cron.job job;
CREATE VIEW app.late_view AS SELECT email FROM app.users;
`);

    const fromLateView = viewTypeBlock(types, "from_late_view");
    const fromView = viewTypeBlock(types, "from_view");
    const fromMatview = viewTypeBlock(types, "from_matview");
    const fromValues = viewTypeBlock(types, "from_values");
    const fromFunction = viewTypeBlock(types, "from_function");
    const fromTableFunction = viewTypeBlock(types, "from_table_function");
    const fromUnnest = viewTypeBlock(types, "from_unnest");
    const fromSetOperation = viewTypeBlock(types, "from_set_operation");
    const fromSample = viewTypeBlock(types, "from_sample");
    const fromConcat = viewTypeBlock(types, "from_concat");
    const fromArithmetic = viewTypeBlock(types, "from_arithmetic");
    const fromLiterals = viewTypeBlock(types, "from_literals");
    const fromScalarSubquery = viewTypeBlock(types, "from_scalar_subquery");
    const fromExpressions = viewTypeBlock(types, "from_expressions");
    const fromPgCatalog = viewTypeBlock(types, "from_pg_catalog");
    const fromPgCron = viewTypeBlock(types, "from_pg_cron");

    expect(types).toContain("embedding: string | null;");
    expect(types).toContain("email: string | null;");
    expect(types).toContain('p_user: Database["app"]["Tables"]["users"]["Row"]');
    expect(types).toContain("accept_user: { Args:");
    expect(types).toContain("Returns: undefined");
    expect(types).toContain('users: Database["app"]["Views"]["v_users"]["Row"][] | null;');
    expect(types).toContain('owner: Database["app"]["Tables"]["users"]["Row"] | null;');
    expect(fromLateView).toContain("email: string | null;");
    expect(fromView).toContain("user_id: number | null;");
    expect(fromView).toContain("email: string | null;");
    expect(fromMatview).toContain("id: number | null;");
    expect(fromMatview).toContain("email: string | null;");
    expect(fromValues).toContain("disclosure_key: string | null;");
    expect(fromValues).toContain("display_order: number | null;");
    expect(fromFunction).toContain("n: number | null;");
    expect(fromTableFunction).toContain("subject_id: string | null;");
    expect(fromTableFunction).toContain("access_level: string | null;");
    expect(fromUnnest).toContain('status: Database["app"]["Enums"]["status"] | null;');
    expect(fromSetOperation).toContain("id: number | null;");
    expect(fromSetOperation).toContain("email: string | null;");
    expect(fromSample).toContain("id: number | null;");
    expect(fromConcat).toContain("membership_id: string | null;");
    expect(fromArithmetic).toContain("prior_id: number | null;");
    expect(fromLiterals).toContain("emails_sent: number | null;");
    expect(fromLiterals).toContain("enabled: boolean | null;");
    expect(fromLiterals).toContain("label: string | null;");
    expect(fromScalarSubquery).toContain("participant_count: number | null;");
    expect(fromExpressions).toContain("p95_id: number | null;");
    expect(fromExpressions).toContain("avg_id: number | null;");
    expect(fromExpressions).toContain("first_email: string | null;");
    expect(fromExpressions).toContain("touchpoints: number[] | null;");
    expect(fromExpressions).toContain("contact_id: string | null;");
    expect(fromExpressions).toContain("item_count: number | null;");
    expect(fromExpressions).toContain("formatted_id: string | null;");
    expect(fromExpressions).toContain("email_prefix: string | null;");
    expect(fromExpressions).toContain("business_days: number | null;");
    expect(fromPgCatalog).toContain("object_oid: unknown;");
    expect(fromPgCatalog).toContain("relation_name: unknown;");
    expect(fromPgCron).toContain("jobid: number | null;");
    expect(fromPgCron).toContain("jobname: string | null;");
    expect(
      [
        fromLateView,
        fromView,
        fromMatview,
        fromValues,
        fromFunction,
        fromTableFunction,
        fromUnnest,
        fromSetOperation,
        fromSample,
        fromConcat,
        fromArithmetic,
        fromLiterals,
        fromScalarSubquery,
        fromExpressions,
        fromPgCatalog,
        fromPgCron,
      ].join("\n")
    ).not.toContain("unknown | null;");
  });

  it("applies derived-table column aliases positionally", async () => {
    const types = await typesFor(`CREATE SCHEMA app;
CREATE TABLE app.accounts (id bigint, name text);
CREATE VIEW app.partial_aliases AS
SELECT * FROM (SELECT id, name FROM app.accounts) AS source(account_id);
`);
    const view = viewTypeBlock(types, "partial_aliases");

    expect(view).toContain("account_id: number | null;");
    expect(view).toContain("name: string | null;");
    expect(view).not.toContain("\n          id: number | null;");
  });

  it("preserves schema qualifiers when resolving column references", async () => {
    const types = await typesFor(`CREATE SCHEMA app;
CREATE SCHEMA audit;
CREATE TABLE app.accounts (id bigint);
CREATE TABLE audit.accounts (id text);
CREATE VIEW app.qualified_account AS
SELECT app.accounts.id AS account_id FROM app.accounts JOIN audit.accounts ON true;
`);
    const view = viewTypeBlock(types, "qualified_account");

    expect(view).toContain("account_id: number | null;");
    expect(view).not.toContain("account_id: string | null;");
  });

  it("treats predicate sublinks as boolean expressions", async () => {
    const types = await typesFor(`CREATE SCHEMA app;
CREATE TABLE app.accounts (id bigint);
CREATE VIEW app.account_matches AS
SELECT id IN (SELECT id FROM app.accounts) AS has_match FROM app.accounts;
`);
    const view = viewTypeBlock(types, "account_matches");

    expect(view).toContain("has_match: boolean | null;");
    expect(view).not.toContain("has_match: number | null;");
  });

  it("resolves visible function overloads before builtin names", async () => {
    const types =
      await typesFor(`CREATE FUNCTION public.lower(value integer) RETURNS integer LANGUAGE sql AS $$ SELECT value $$;
CREATE VIEW public.custom_lower AS SELECT lower(1) AS lowered;
`);
    const view = viewTypeBlock(types, "custom_lower");

    expect(view).toContain("lowered: number | null;");
    expect(view).not.toContain("lowered: string | null;");
  });

  it("falls back to builtin function metadata when no visible project overload exists", async () => {
    const types = await typesFor(`CREATE SCHEMA app;
CREATE TABLE app.accounts (id bigint, name text);
CREATE FUNCTION app.echo_int(value integer) RETURNS integer LANGUAGE sql AS $$ SELECT value $$;
CREATE VIEW app.builtin_lower AS SELECT lower(name) AS lowered FROM app.accounts;
CREATE VIEW app.custom_function AS SELECT app.echo_int(1) AS value FROM app.accounts;
`);
    const builtin = viewTypeBlock(types, "builtin_lower");
    const custom = viewTypeBlock(types, "custom_function");

    expect(builtin).toContain("lowered: string | null;");
    expect(custom).toContain("value: number | null;");
  });

  it("returns unknown after visible overload mismatch", async () => {
    const types =
      await typesFor(`CREATE FUNCTION public.lower(value bigint) RETURNS bigint LANGUAGE sql AS $$ SELECT value $$;
CREATE VIEW public.custom_lower_mismatch AS SELECT lower(1) AS lowered;
`);
    const view = viewTypeBlock(types, "custom_lower_mismatch");

    expect(view).toContain("lowered: unknown;");
    expect(view).not.toContain("lowered: string | null;");
    expect(view).not.toContain("lowered: number | null;");
  });

  it("emits upstream helper types and enum constants without direct aliases", async () => {
    const types = await typesFor(treeSql);

    expect(types).toContain('status: "draft" | "active";');
    expect(types).toContain("export type Tables<");
    expect(types).toContain("export type TablesInsert<");
    expect(types).toContain("export type TablesUpdate<");
    expect(types).toContain("export type Enums<");
    expect(types).toContain("export type CompositeTypes<");
    expect(types).toContain("export const Constants = {");
    expect(types).toContain('status: ["draft", "active"],');
  });

  it("escapes code-sensitive string literal characters", () => {
    expect(quoteCodeString("</script>\u2028\u2029")).toBe('"\\u003c/script>\\u2028\\u2029"');
  });

  it("matches the checked-in official postgres-meta contract", async () => {
    const sql = `CREATE TYPE public.visibility AS ENUM ('public', 'private');
CREATE TYPE public.address AS (street text, zip bigint);
CREATE TABLE public.movies (id bigint NOT NULL, name text NOT NULL, visibility visibility NOT NULL);
CREATE VIEW public.movie_names AS SELECT id, name FROM public.movies;
`;
    const model = await modelFor(sql, "supa-typegen-official-parity-");
    const generated = generateDatabaseTypes(await collectSchemaShapes(model), {
      postgrestVersion: "12",
    });
    const official = await readFile(
      join(process.cwd(), "tests/fixtures/typegen/supabase-official.types.txt"),
      "utf8"
    );

    for (const name of [
      "Json",
      "Database",
      "DatabaseWithoutInternals",
      "DefaultSchema",
      "Tables",
      "TablesInsert",
      "TablesUpdate",
      "Enums",
      "CompositeTypes",
      "Constants",
    ]) {
      expect(canonicalDeclaration(generated, name), name).toBe(
        canonicalDeclaration(official, name)
      );
    }
  });

  it("matches checked-in official postgres-meta RPC metadata", async () => {
    const sql = `CREATE TABLE public.movies (id bigint, name text);
CREATE FUNCTION public.movie_label(public.movies) RETURNS text LANGUAGE sql AS $$ SELECT $1.name $$;
CREATE FUNCTION public.movie_rows(public.movies) RETURNS SETOF public.movies ROWS 2 LANGUAGE sql AS $$ SELECT $1 $$;
CREATE FUNCTION public.named_movie(row_arg public.movies) RETURNS text LANGUAGE sql AS $$ SELECT row_arg.name $$;
CREATE FUNCTION public.relation_return() RETURNS public.movies LANGUAGE sql AS $$ SELECT ROW(1, 'x')::public.movies $$;
CREATE FUNCTION public.multi_out(OUT a integer, OUT b text) LANGUAGE sql AS $$ SELECT 1, 'x'::text $$;
CREATE FUNCTION public.ordered(z integer, a text) RETURNS text LANGUAGE sql AS $$ SELECT a $$;
CREATE FUNCTION public.conflict(value boolean) RETURNS boolean LANGUAGE sql AS $$ SELECT value $$;
CREATE FUNCTION public.conflict(value bigint) RETURNS bigint LANGUAGE sql AS $$ SELECT value $$;
CREATE FUNCTION public.join_labels(VARIADIC labels text[]) RETURNS text LANGUAGE sql AS $$ SELECT array_to_string(labels, ',') $$;
CREATE FUNCTION public.take_text_array(text[]) RETURNS text LANGUAGE sql AS $$ SELECT ''::text $$;
CREATE FUNCTION public.take_movie_array(public.movies[]) RETURNS text LANGUAGE sql AS $$ SELECT ''::text $$;
`;
    const generated = await typesFor(sql);
    const official = await readFile(
      join(process.cwd(), "tests/fixtures/typegen/supabase-official-rpc.types.txt"),
      "utf8"
    );

    expect(canonicalDeclaration(generated, "Database")).toBe(
      canonicalDeclaration(official, "Database")
    );
  });

  it("emits internals and upstream empty collection sentinels", async () => {
    const model = await modelFor(
      `CREATE SCHEMA app;
CREATE TYPE app.status AS ENUM ('draft');
CREATE TABLE public.movies (id bigint);
`,
      "supa-typegen-empty-"
    );
    const types = generateDatabaseTypes(await collectSchemaShapes(model), {
      postgrestVersion: "12",
    });

    expect(types).toContain("  __InternalSupabase: {");
    expect(types).toContain('    PostgrestVersion: "12";');
    expect(types).toContain(
      'type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">;'
    );
    expect(types).toContain(
      'type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">];'
    );
    expect(types.split("[_ in never]: never;")).toHaveLength(9);
  });

  it("type-checks upstream helper contracts", async () => {
    const types = await typesFor(helperSql);

    await expectTypeScriptAccepts(`${types}
const movie: Tables<"movies"> = { id: 1, name: "Heat", visibility: "public" };
const movieView: Tables<"movie_names"> = { id: 1, name: "Heat" };
const movieInsert: TablesInsert<"movies"> = { name: "Heat" };
const movieUpdate: TablesUpdate<"movies"> = { name: "Thief" };
const visibility: Enums<"visibility"> = "private";
const account: Tables<{ schema: "app" }, "accounts"> = { id: 1, state: "active", home: { street: "Main", zip: 1 } };
const accountInsert: TablesInsert<{ schema: "app" }, "accounts"> = { state: "draft" };
const accountUpdate: TablesUpdate<{ schema: "app" }, "accounts"> = { state: "active" };
const status: Enums<{ schema: "app" }, "status"> = "draft";
const address: CompositeTypes<{ schema: "app" }, "address"> = { street: "Main", zip: 1 };
void movie;
void movieView;
void movieInsert;
void movieUpdate;
void visibility;
void account;
void accountInsert;
void accountUpdate;
void status;
void address;
`);
  }, 15_000);

  it("type-checks schema-qualified helpers without a public schema", async () => {
    const types = await typesFor(`CREATE SCHEMA app;
CREATE TABLE app.accounts (id bigint);
`);

    await expectTypeScriptAccepts(`${types}
const account: Tables<{ schema: "app" }, "accounts"> = { id: 1 };
const accountInsert: TablesInsert<{ schema: "app" }, "accounts"> = { id: 1 };
const accountUpdate: TablesUpdate<{ schema: "app" }, "accounts"> = { id: 2 };
void account;
void accountInsert;
void accountUpdate;
`);
  }, 15_000);

  it("emits TypeScript and Zod output from one precomputed shape graph", async () => {
    const model = await modelFor(treeSql, "supa-typegen-shapes-");
    const shapes = await collectSchemaShapes(model);
    const types = generateDatabaseTypes(shapes);
    const zod = generateZodSchemas(shapes, "./database.types.js");

    expect(types).toContain("export type Database = {");
    expect(zod).toContain("export const SupaschemaZod");
    expect(types.endsWith("\n")).toBe(true);
    expect(types.endsWith("\n\n")).toBe(false);
    expect(zod.endsWith("\n")).toBe(true);
    expect(zod.endsWith("\n\n")).toBe(false);
  });
});

const hardenedSql = `CREATE SCHEMA app;
CREATE SCHEMA audit;
CREATE DOMAIN app.email AS text;
CREATE TYPE app.status AS ENUM ('draft', 'active');
CREATE TYPE audit.status AS ENUM ('ok', 'bad');
CREATE TABLE app.users (
  id bigint GENERATED ALWAYS AS IDENTITY,
  contact app.email NOT NULL,
  state status NOT NULL
);
ALTER TABLE ONLY app.users ADD CONSTRAINT users_pkey PRIMARY KEY (id);
CREATE TABLE audit.logs (
  id bigint PRIMARY KEY,
  state status NOT NULL,
  user_id bigint UNIQUE REFERENCES app.users
);
CREATE VIEW app.user_emails (uid, mail) AS SELECT id, contact FROM app.users;
CREATE VIEW app.all_users AS SELECT u.* FROM app.users u;
CREATE FUNCTION app.get_user(uid bigint, fallback text DEFAULT 'none') RETURNS SETOF text LANGUAGE sql AS $$ SELECT contact FROM app.users $$;
`;

describe("review-hardened typegen", () => {
  it("treats always-generated identity as never and standalone primary keys as not null", async () => {
    const types = await typesFor(hardenedSql);
    const users = `${generatedTypeBlock(types, "users", "Row")}\n${generatedTypeBlock(types, "users", "Insert")}`;

    expect(users).toContain("id: number;");
    expect(users).toContain("id?: never;");
  });

  it("maps domains to their base type and resolves shadowed enums schema-locally", async () => {
    const types = await typesFor(hardenedSql);

    expect(types).toContain("contact: string;");
    expect(generatedTypeBlock(types, "users", "Row")).toContain(
      'state: Database["app"]["Enums"]["status"];'
    );
    expect(generatedTypeBlock(types, "logs", "Row")).toContain(
      'state: Database["audit"]["Enums"]["status"];'
    );
  });

  it("filters cross-schema relationships like postgres-meta", async () => {
    const types = await typesFor(hardenedSql);
    const logsStart = types.indexOf("      logs: {");
    const relationshipsStart = types.indexOf("        Relationships:", logsStart);
    const relationshipsEnd = types.indexOf("\n", relationshipsStart);
    const relationships = types.slice(relationshipsStart, relationshipsEnd);

    expect(relationships).toBe("        Relationships: [];");
  });

  it("maps alias-list view columns positionally and expands qualified star selects", async () => {
    const types = await typesFor(hardenedSql);
    const views = `${viewTypeBlock(types, "user_emails")}\n${viewTypeBlock(types, "all_users")}`;

    expect(views).toContain("uid: number | null;");
    expect(views).toContain("mail: string | null;");
    expect(views).toContain("contact: string | null;");
  });

  it("populates Functions with named args, optionality, and setof returns", async () => {
    const types = await typesFor(hardenedSql);

    expect(types).toContain(
      "get_user: { Args: { fallback?: string; uid: number }; Returns: string[] };"
    );
  });
});

const overloadedSql = `CREATE SCHEMA app;
CREATE TABLE public.default_schema_anchor (id bigint);
CREATE FUNCTION app.f(a integer) RETURNS integer LANGUAGE sql AS $$ SELECT a $$;
CREATE FUNCTION app.f(b text) RETURNS text LANGUAGE sql AS $$ SELECT b $$;
`;

describe("overloaded function typegen", () => {
  it("unions every overload instead of silently keeping the first", async () => {
    const types = await typesFor(overloadedSql);

    expect(types).toContain("f: { Args: { a: number }; Returns:");
    expect(types).toContain("{ Args: { b: string }; Returns:");
    await expectTypeScriptAccepts(`${types}
const numeric: Database["app"]["Functions"]["f"] = { Args: { a: 1 }, Returns: 1 };
const textual: Database["app"]["Functions"]["f"] = { Args: { b: "x" }, Returns: "x" };
// @ts-expect-error Returns must stay correlated with the matching Args overload.
const invalid: Database["app"]["Functions"]["f"] = { Args: { a: 1 }, Returns: "x" };
void numeric;
void textual;
void invalid;
`);
  });

  it("emits upstream conflict signatures for same-named arguments", async () => {
    const types = await typesFor(`CREATE SCHEMA app;
CREATE FUNCTION app.ambiguous(value integer) RETURNS integer LANGUAGE sql AS $$ SELECT value $$;
CREATE FUNCTION app.ambiguous(value text) RETURNS text LANGUAGE sql AS $$ SELECT value $$;
`);

    expect(types).toContain(
      "Could not choose the best candidate function between: app.ambiguous(value => int4), app.ambiguous(value => text). Try renaming the parameters or the function itself in the database so function overloading can be resolved"
    );
    expect(types.split("Returns: { error: true }")).toHaveLength(3);
  });
});

const compositeSql = `CREATE SCHEMA app;
CREATE TYPE app.address AS (street text, zip int);
CREATE TYPE app.intrange AS RANGE (subtype = int4);
CREATE TABLE app.people (id bigint, home app.address);
`;

describe("composite and range type typegen", () => {
  it("resolves a column of a declared composite type to its direct contract", async () => {
    const types = await typesFor(compositeSql);

    expect(types).toContain('home: Database["app"]["CompositeTypes"]["address"] | null;');
    expect(types).toContain("CompositeTypes: {");
    expect(collapseWhitespace(types)).toContain(
      "address: { street: string | null; zip: number | null;"
    );
  });

  it("does not emit a range type as an empty composite", async () => {
    const types = await typesFor(compositeSql);

    expect(collapseWhitespace(types)).not.toContain("intrange: {}");
  });

  it("prefers a schema-local composite over a same-named enum in another schema", async () => {
    const types = await typesFor(
      `CREATE SCHEMA app;
CREATE TYPE app.address AS (street text, zip int);
CREATE TYPE public.address AS ENUM ('home', 'work');
CREATE TABLE app.people (id bigint, home address);
`
    );

    expect(types).toContain('home: Database["app"]["CompositeTypes"]["address"] | null;');
    expect(types).not.toContain('home: Database["public"]["Enums"]["address"] | null;');
  });

  it("treats a bare name shared by an enum and a composite as ambiguous (unknown)", async () => {
    const types = await typesFor(
      `CREATE SCHEMA app;
CREATE SCHEMA a;
CREATE SCHEMA b;
CREATE TYPE a.thing AS ENUM ('x');
CREATE TYPE b.thing AS (n int);
CREATE TABLE app.t (id bigint, v thing);
`
    );

    expect(types).toContain("v: unknown;");
    expect(types).not.toContain("v: AThing | null;");
  });
});

const returnShapeSql = `CREATE SCHEMA app;
CREATE FUNCTION app.list_people() RETURNS TABLE (id bigint, label text) LANGUAGE sql AS $$ SELECT 1::bigint, 'x'::text $$;
CREATE FUNCTION app.one_row(OUT a int, OUT b text) LANGUAGE sql AS $$ SELECT 1, 'y' $$;
CREATE FUNCTION app.single_out(OUT x int) LANGUAGE sql AS $$ SELECT 1 $$;
`;

describe("function return row typegen", () => {
  it("preserves RETURNS TABLE and uses upstream record metadata for multiple OUT parameters", async () => {
    const types = await typesFor(returnShapeSql);

    expect(types).toContain(
      "list_people: { Args: never; Returns: { id: number; label: string }[] };"
    );
    expect(types).toContain("one_row: { Args: never; Returns: Record<string, unknown> };");
  });

  it("keeps a single OUT parameter scalar instead of a one-field record", async () => {
    const types = await typesFor(returnShapeSql);

    expect(types).toContain("single_out: { Args: never; Returns: number };");
    expect(types).not.toContain("single_out: { Args: never; Returns: { x:");
  });

  it("uses the PostgreSQL row estimate for set-returning function cardinality", async () => {
    const types = await typesFor(`CREATE SCHEMA app;
CREATE TABLE app.accounts (id bigint);
CREATE FUNCTION app.one_account(app.accounts) RETURNS SETOF app.accounts ROWS 1 LANGUAGE sql AS $$ SELECT $1 $$;
CREATE FUNCTION app.many_accounts(app.accounts) RETURNS SETOF app.accounts ROWS 2 LANGUAGE sql AS $$ SELECT $1 $$;
`);

    expect(types).toContain(
      'one_account: { Args: { "": Database["app"]["Tables"]["accounts"]["Row"] }; Returns: { id: number | null }; SetofOptions: { from: "app.accounts"; to: "accounts"; isOneToOne: true; isSetofReturn: true } };'
    );
    expect(types).toContain(
      'many_accounts: { Args: { "": Database["app"]["Tables"]["accounts"]["Row"] }; Returns: { id: number | null }[]; SetofOptions: { from: "app.accounts"; to: "accounts"; isOneToOne: false; isSetofReturn: true } };'
    );
  });
});

describe("PostgREST function metadata", () => {
  it("keeps valid unnamed scalar and relation-row arguments", async () => {
    const types = await typesFor(`CREATE SCHEMA app;
CREATE TYPE app.address AS (street text);
CREATE TABLE app.accounts (id bigint);
CREATE FUNCTION app.take_json(json) RETURNS json LANGUAGE sql AS $$ SELECT $1 $$;
CREATE FUNCTION app.take_jsonb(jsonb) RETURNS jsonb LANGUAGE sql AS $$ SELECT $1 $$;
CREATE FUNCTION app.take_text(text) RETURNS text LANGUAGE sql AS $$ SELECT $1 $$;
CREATE FUNCTION app.take_text_array(text[]) RETURNS text LANGUAGE sql AS $$ SELECT ''::text $$;
CREATE FUNCTION app.take_integer(integer) RETURNS integer LANGUAGE sql AS $$ SELECT $1 $$;
CREATE FUNCTION app.take_address(app.address) RETURNS app.address LANGUAGE sql AS $$ SELECT $1 $$;
CREATE FUNCTION app.take_account_array(app.accounts[]) RETURNS text LANGUAGE sql AS $$ SELECT ''::text $$;
CREATE DOMAIN app.account_domain AS app.accounts;
CREATE FUNCTION app.take_account_domain(app.account_domain) RETURNS text LANGUAGE sql AS $$ SELECT ''::text $$;
CREATE FUNCTION app.join_labels(VARIADIC labels text[]) RETURNS text LANGUAGE sql AS $$ SELECT array_to_string(labels, ',') $$;
CREATE FUNCTION app.invalid_mixed(label text, app.address DEFAULT NULL) RETURNS text LANGUAGE sql AS $$ SELECT label $$;
CREATE FUNCTION app.account_label(app.accounts) RETURNS text LANGUAGE sql AS $$ SELECT 'account'::text $$;
`);

    expect(types).toContain('take_json: { Args: { "": Json }; Returns: Json };');
    expect(types).toContain('take_jsonb: { Args: { "": Json }; Returns: Json };');
    expect(types).toContain('take_text: { Args: { "": string }; Returns: string };');
    expect(types).not.toContain("take_text_array:");
    expect(types).not.toContain("take_account_array:");
    expect(types).not.toContain("take_account_domain:");
    expect(types).not.toContain("take_integer:");
    expect(types).not.toContain("invalid_mixed:");
    expect(types).toContain("join_labels: { Args: { labels: string[] }; Returns: string };");
    expect(generatedTypeBlock(types, "accounts", "Row")).not.toContain("take_account_array");
    expect(types).toContain(
      'take_address: { Args: { "": Database["app"]["CompositeTypes"]["address"] }; Returns: Database["app"]["CompositeTypes"]["address"]; SetofOptions: { from: "app.address"; to: "address"; isOneToOne: true; isSetofReturn: false } };'
    );
    expect(generatedTypeBlock(types, "accounts", "Row")).not.toContain("account_label");
    expect(types).toContain(
      'Returns: { error: true } & "the function app.account_label with parameter or with a single unnamed json/jsonb parameter, but no matches were found in the schema cache"'
    );
  });
});

describe("zod schema generation", () => {
  async function zodFor(sql: string): Promise<string> {
    const model = await modelFor(sql, "supa-zodgen-");
    return generateZodSchemas(await collectSchemaShapes(model), "./database.types.js");
  }

  it("emits runtime validators mirroring the generated types", async () => {
    const zod = await zodFor(treeSql);

    expect(zod).toContain('import type { Database, Json } from "./database.types.js";');
    expect(zod).toContain('import { z } from "zod";');
    expect(zod).toContain("export const JsonSchema: z.ZodType<Json>");
    expect(zod).toContain("export const SupaschemaZod = {");
    expect(zod).toContain("} as const satisfies SupaschemaZodShape;");
    expect(zod).toContain('status: z.enum(["draft", "active"]),');
    expect(zod).toContain("name: z.string(),");
    expect(zod).toContain("email: z.string().nullable(),");
    expect(zod).toContain("tags: z.array(z.string()),");
    expect(zod).toContain("payload: JsonSchema.nullable(),");
    expect(zod).toContain(
      'state: z.lazy((): z.ZodType<Database["app"]["Enums"]["status"]> => SupaschemaZod["app"]["Enums"]["status"]),'
    );
    expect(zod).toContain("accounts: {");
    expect(zod).toContain("Row: z.object({");
    expect(zod).toContain("Insert: z.object({");
    expect(zod).toContain("Update: z.object({");
    expect(zod).toContain("account_names: {");
    expect(zod).toContain("label: z.string().nullable(),");
  });

  it("type-checks SupaschemaZod runtime schema owners", async () => {
    const types = await typesFor(helperSql);
    const zod = await zodFor(helperSql);
    const zodWithoutJsonImport = zod.split("\n").slice(1).join("\n");

    await expectTypeScriptAccepts(`${types}${zodWithoutJsonImport}
const movie: Tables<"movies"> = SupaschemaZod.public.Tables.movies.Row.parse({ id: 1, name: "Heat", visibility: "public" });
const movieView: Tables<"movie_names"> = SupaschemaZod.public.Views.movie_names.Row.parse({ id: 1, name: "Heat" });
const movieInsert: TablesInsert<"movies"> = SupaschemaZod.public.Tables.movies.Insert.parse({ name: "Heat" });
const movieUpdate: TablesUpdate<"movies"> = SupaschemaZod.public.Tables.movies.Update.parse({ name: "Thief" });
const visibility: Enums<"visibility"> = SupaschemaZod.public.Enums.visibility.parse("private");
const account: Tables<{ schema: "app" }, "accounts"> = SupaschemaZod.app.Tables.accounts.Row.parse({
  id: 1,
  state: "active",
  home: { street: "Main", zip: 1 },
});
const accountInsert: TablesInsert<{ schema: "app" }, "accounts"> = SupaschemaZod.app.Tables.accounts.Insert.parse({ state: "draft" });
const accountUpdate: TablesUpdate<{ schema: "app" }, "accounts"> = SupaschemaZod.app.Tables.accounts.Update.parse({ state: "active" });
const status: Enums<{ schema: "app" }, "status"> = SupaschemaZod.app.Enums.status.parse("draft");
const address: CompositeTypes<{ schema: "app" }, "address"> = SupaschemaZod.app.CompositeTypes.address.parse({ street: "Main", zip: 1 });
const movieName = SupaschemaZod.public.Tables.movies.Row.pick({ name: true }).parse({ name: "Heat" });
const parsedName: string = movieName.name;
// @ts-expect-error Parsed rows retain their generated output type rather than any.
const wrong: { missing: string } = SupaschemaZod.public.Tables.movies.Row.parse({ id: 1, name: "Heat", visibility: "public" });
void movie;
void movieView;
void movieInsert;
void movieUpdate;
void visibility;
void account;
void accountInsert;
void accountUpdate;
void status;
void address;
void parsedName;
void wrong;
`);
  }, 15_000);

  it("omits an unused Database import from scalar-only schemas", async () => {
    const sql = `CREATE TABLE public.items (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  "Database[" text,
  payload jsonb
);
`;
    const types = await typesFor(sql);
    const zod = await zodFor(sql);
    const root = join(process.cwd(), ".tmp");
    await mkdir(root, { recursive: true });
    const moduleRoot = await mkdtemp(join(root, "supa-zod-scalar-"));
    await writeFile(join(moduleRoot, "package.json"), '{"type":"module"}\n');
    await writeFile(join(moduleRoot, "database.types.ts"), types);
    await writeFile(join(moduleRoot, "schemas.ts"), zod);
    await writeFile(
      join(moduleRoot, "tsconfig.json"),
      `${JSON.stringify(
        {
          compilerOptions: {
            module: "NodeNext",
            moduleResolution: "NodeNext",
            noEmit: true,
            noUnusedLocals: true,
            skipLibCheck: true,
            strict: true,
            target: "ES2022",
          },
          files: ["database.types.ts", "schemas.ts"],
        },
        null,
        2
      )}\n`
    );

    expect(zod).toContain('import type { Json } from "./database.types.js";');
    expect(zod).toContain('"Database[": z.string().nullable(),');
    expect(zod).not.toContain("import type { Database");
    await execFileAsync(
      process.execPath,
      [
        typescriptCompilerPath(),
        "--project",
        join(moduleRoot, "tsconfig.json"),
        "--pretty",
        "false",
      ],
      {
        cwd: moduleRoot,
        maxBuffer: 1024 * 1024,
      }
    );
  }, 15_000);

  it("keeps recursive Zod-only schemas self-contained and strictly compilable", async () => {
    const model = await modelFor(helperSql, "supa-zod-only-");
    const shapes = await collectSchemaShapes(model);
    const zod = generateZodSchemas(shapes);

    expect(generateZodSchemas(shapes, "")).toBe(zod);
    expect(zod).toContain("export const SupaschemaZod: SupaschemaZodShape = {");
    expect(zod).not.toContain("satisfies SupaschemaZodShape");
    expect(zod).not.toContain("Database[");
    expect(zod).toContain('state: z.lazy(() => SupaschemaZod["app"]["Enums"]["status"]),');
    expect(zod).toContain(
      'home: z.lazy(() => SupaschemaZod["app"]["CompositeTypes"]["address"]).nullable(),'
    );
    await expectTypeScriptAccepts(`${zod}
const account = SupaschemaZod.app.Tables.accounts.Row.parse({
  id: 1,
  state: "active",
  home: { street: "Main", zip: 1 },
});
void account;
`);
  }, 15_000);

  it("keeps computed relationship validators aligned with generated rows", async () => {
    const sql = `CREATE TABLE public.accounts (id bigint);
CREATE TABLE public.related_accounts (id bigint);
CREATE FUNCTION public.account_label(public.accounts) RETURNS text LANGUAGE sql AS $$ SELECT 'account'::text $$;
CREATE FUNCTION public.related_account(public.accounts) RETURNS public.related_accounts LANGUAGE sql AS $$ SELECT ROW(1)::public.related_accounts $$;
`;
    const types = await typesFor(sql);
    const zod = await zodFor(sql);
    const zodWithoutTypesImport = zod.split("\n").slice(1).join("\n");

    expect(zod).toContain("account_label: z.string().nullable(),");
    expect(zod).toContain(
      'related_account: z.lazy((): z.ZodType<Database["public"]["Tables"]["related_accounts"]["Row"]> => SupaschemaZod["public"]["Tables"]["related_accounts"].Row).nullable(),'
    );
    await expectTypeScriptAccepts(`${types}${zodWithoutTypesImport}
const account: Tables<"accounts"> = SupaschemaZod.public.Tables.accounts.Row.parse({
  id: 1,
  account_label: null,
  related_account: null,
});
void account;
`);
  }, 15_000);

  it("separates same-named enum and composite validators by schema/object namespace", async () => {
    const zod = await zodFor(`CREATE SCHEMA "tenant-a";
CREATE SCHEMA tenant_a;
CREATE TYPE "tenant-a".status AS ENUM ('active');
CREATE TYPE tenant_a.status AS (value text);
`);

    expect(zod).toContain('status: z.enum(["active"]),');
    expect(zod).toContain("status: z.object({");
    expect(zod).toContain('"tenant-a": {');
    expect(zod).toContain("tenant_a: {");
  });

  it("validates composite-typed columns with generated composite object schemas", async () => {
    const zod = await zodFor(
      `CREATE SCHEMA app;
CREATE TYPE app.address AS (street text, zip int);
CREATE TABLE app.people (id bigint, home app.address);
`
    );

    expect(zod).not.toContain("z.composite()");
    expect(zod).toContain("address: z.object({");
    expect(zod).toContain("street: z.string().nullable(),");
    expect(zod).toContain("zip: z.number().nullable(),");
    expect(zod).toContain(
      'home: z.lazy((): z.ZodType<Database["app"]["CompositeTypes"]["address"]> => SupaschemaZod["app"]["CompositeTypes"]["address"]).nullable(),'
    );
    expect(zod).not.toContain("export const CompositeTypes =");
  });

  it("defers composite references so declaration order cannot trigger TDZ", async () => {
    const sql = `CREATE SCHEMA app;
CREATE TYPE app.z AS (value text);
CREATE TYPE app.a AS (z app.z);
`;
    const zod = await zodFor(sql);
    const types = await typesFor(sql);
    const root = join(process.cwd(), ".tmp");
    await mkdir(root, { recursive: true });
    const moduleRoot = await mkdtemp(join(root, "supa-zod-runtime-"));
    const outDir = join(moduleRoot, "dist");
    await writeFile(join(moduleRoot, "package.json"), '{"type":"module"}\n');
    await writeFile(join(moduleRoot, "database.types.ts"), types);
    await writeFile(join(moduleRoot, "schemas.ts"), zod);
    await writeFile(
      join(moduleRoot, "tsconfig.json"),
      `${JSON.stringify(
        {
          compilerOptions: {
            module: "NodeNext",
            moduleResolution: "NodeNext",
            outDir: "dist",
            skipLibCheck: true,
            strict: true,
            target: "ES2022",
          },
          files: ["database.types.ts", "schemas.ts"],
        },
        null,
        2
      )}\n`
    );

    expect(zod).toContain(
      'z: z.lazy((): z.ZodType<Database["app"]["CompositeTypes"]["z"]> => SupaschemaZod["app"]["CompositeTypes"]["z"]).nullable(),'
    );
    await execFileAsync(
      process.execPath,
      [
        typescriptCompilerPath(),
        "--project",
        join(moduleRoot, "tsconfig.json"),
        "--pretty",
        "false",
      ],
      {
        cwd: moduleRoot,
        maxBuffer: 1024 * 1024,
      }
    );
    const modulePath = join(outDir, "schemas.js");
    const imported = await import(`${pathToFileURL(modulePath).href}?t=${Date.now()}`);
    expect(imported.SupaschemaZod.app.CompositeTypes.a.parse({ z: { value: "ok" } })).toEqual({
      z: { value: "ok" },
    });
  });

  it("derives insert optionality and omits generated columns from writes", async () => {
    const zod = await zodFor(treeSql);
    const accountsStart = zod.indexOf("accounts: {", zod.indexOf("export const SupaschemaZod"));
    const insertStart = zod.indexOf("Insert: z.object({", accountsStart);
    const insertEnd = zod.indexOf("Update: z.object({", accountsStart);
    const insert = zod.slice(insertStart, insertEnd);

    expect(insert).toContain("id: z.number().optional(),");
    expect(insert).toContain("name: z.string(),");
    expect(insert).toContain("email: z.string().nullable().optional(),");
    expect(insert).not.toContain("doubled");
    const update = zod.slice(insertEnd, zod.indexOf("events: {", accountsStart));
    expect(update).toContain("name: z.string().optional(),");
    expect(update).not.toContain("doubled");
  });
});

describe("unknown relation diagnostics", () => {
  async function shapeDiagnosticsFor(sql: string): Promise<Diagnostic[]> {
    const extracted = await extractObjectsFromSql(sql);
    const errors = extracted.diagnostics.filter((item) => item.severity === "error");
    if (errors.length > 0) {
      throw new Error(`expected extraction to succeed: ${JSON.stringify(errors)}`);
    }
    const diagnostics: Diagnostic[] = [];
    await collectSchemaShapes(
      { diagnostics: [], fingerprint: "test", objects: extracted.objects, source: "test" },
      diagnostics
    );
    return diagnostics;
  }

  it("warns when a view resolves unknown columns from an unmodeled relation", async () => {
    const diagnostics = await shapeDiagnosticsFor(
      "CREATE SCHEMA app;\nCREATE VIEW app.v_user_sessions AS SELECT s.id AS id FROM auth.sessions s;"
    );

    const warning = diagnostics.find((item) => item.code === "SUPA_TYPEGEN_UNKNOWN_RELATION");
    expect(warning).toBeDefined();
    expect(warning?.severity).toBe("warning");
    expect(warning?.message).toContain("app.v_user_sessions");
    expect(warning?.message).toContain("auth.sessions");
    expect(warning?.hint).toContain("cast");
  });

  it("stays quiet when explicit casts give every column a concrete type", async () => {
    const diagnostics = await shapeDiagnosticsFor(
      "CREATE SCHEMA app;\nCREATE VIEW app.v_user_sessions AS SELECT (s.id)::uuid AS id FROM auth.sessions s;"
    );

    expect(diagnostics.some((item) => item.code === "SUPA_TYPEGEN_UNKNOWN_RELATION")).toBe(false);
  });
});
