import { access, mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, extname, relative, resolve } from "node:path";
import { type BuildInfo, readBuildInfo } from "../build-info.js";
import { hasErrors } from "../diagnostics/diagnostics.js";
import { extractSourceModel } from "../source/extract.js";
import { defaultTreeSource } from "../source/resolve.js";
import type { Diagnostic, SupaschemaConfig } from "../types.js";
import { generateDatabaseTypes } from "./database.js";
import { collectSchemaShapes } from "./model.js";
import { generateZodSchemas } from "./zod.js";

interface GeneratedContractsOptions {
  check?: boolean;
  config: SupaschemaConfig;
  honorWorkflowPolicy?: boolean;
  out?: string;
  source?: string;
}

interface GeneratedContractsResult {
  checked: string[];
  diagnostics: Diagnostic[];
  skipped: string[];
  stdout?: string;
  written: string[];
}

export async function generateTypeContracts(
  options: GeneratedContractsOptions
): Promise<GeneratedContractsResult> {
  const check = options.check === true;
  const source = options.source ?? defaultTreeSource(options.config);
  const target = options.out ?? options.config.typesFile;
  const typesPath = target === "stdout" ? "stdout" : resolve(process.cwd(), target);
  const zodPath = resolve(process.cwd(), options.config.zodFile);
  const typesPolicy = options.config.workflow.type_generation;
  const zodPolicy = options.config.workflow.zod_generation;
  const writeTypes =
    target !== "stdout" &&
    (await shouldWriteGeneratedOutput(typesPath, typesPolicy, options.honorWorkflowPolicy, check));
  const writeZod =
    target !== "stdout" &&
    (await shouldWriteGeneratedOutput(zodPath, zodPolicy, options.honorWorkflowPolicy, check));
  if (target !== "stdout" && !writeTypes && !writeZod) {
    return {
      checked: [],
      diagnostics: [],
      skipped: skippedGeneratedOutputs(typesPath, typesPolicy, zodPath, zodPolicy),
      written: [],
    };
  }
  const model = await extractSourceModel(source, { config: options.config });
  if (hasErrors(model.diagnostics)) {
    return { checked: [], diagnostics: model.diagnostics, skipped: [], written: [] };
  }
  const shapeDiagnostics: Diagnostic[] = [];
  const shapes = await collectSchemaShapes(model, shapeDiagnostics);
  const diagnostics = [...model.diagnostics, ...shapeDiagnostics];
  const buildInfo = await readBuildInfo();
  const types = withGeneratedHeader(generateDatabaseTypes(shapes), buildInfo, model.fingerprint);
  if (target === "stdout") {
    return { checked: [], diagnostics, skipped: [], stdout: types, written: [] };
  }
  if (check) {
    const driftDiagnostics: Diagnostic[] = [];
    const checked: string[] = [];
    if (writeTypes) {
      checked.push(...(await compareGeneratedOutput(typesPath, types, driftDiagnostics)));
    }
    if (writeZod) {
      const zod = withGeneratedHeader(
        generateZodSchemas(shapes, zodImportPath(options, writeTypes, zodPath, typesPath)),
        buildInfo,
        model.fingerprint
      );
      checked.push(...(await compareGeneratedOutput(zodPath, zod, driftDiagnostics)));
    }
    return {
      checked,
      diagnostics: [...diagnostics, ...driftDiagnostics],
      skipped: [],
      written: [],
    };
  }
  const written: string[] = [];
  if (writeTypes) {
    written.push(await writeGeneratedOutput(typesPath, types));
  }
  if (writeZod) {
    written.push(
      await writeGeneratedOutput(
        zodPath,
        withGeneratedHeader(
          generateZodSchemas(shapes, zodImportPath(options, writeTypes, zodPath, typesPath)),
          buildInfo,
          model.fingerprint
        )
      )
    );
  }
  return { checked: [], diagnostics, skipped: [], written };
}

function zodImportPath(
  options: GeneratedContractsOptions,
  writeTypes: boolean,
  zodPath: string,
  typesPath: string
): string | undefined {
  return (
    options.config.zodTypesImportPath ??
    (writeTypes ? typesModulePath(zodPath, typesPath) : undefined)
  );
}

function withGeneratedHeader(contents: string, info: BuildInfo, fingerprint: string): string {
  const commit = info.commit === null ? undefined : info.commit.slice(0, 12);
  const build = commit === undefined ? info.version : `${info.version} (${commit})`;
  return `// Generated by supaschema ${build}. Regenerate with: supaschema types\n// Fingerprint: ${fingerprint}\n\n${contents}`;
}

async function compareGeneratedOutput(
  path: string,
  contents: string,
  diagnostics: Diagnostic[]
): Promise<string[]> {
  const existing = await readFile(path, "utf8").catch(() => null);
  if (existing === contents) {
    return [path];
  }
  diagnostics.push({
    code: "SUPA_TYPES_CONTRACT_DRIFT",
    file: path,
    message:
      existing === null
        ? `regeneration would create ${path}; run supaschema types to write it`
        : `regeneration would change ${path}; run supaschema types to refresh it`,
    severity: "error",
  });
  return [];
}

function typesModulePath(zodPath: string, typesPath: string): string {
  const fromZod = relative(dirname(zodPath), typesPath).split("\\").join("/");
  const extension = extname(fromZod);
  const withoutExtension = extension.length === 0 ? fromZod : fromZod.slice(0, -extension.length);
  const modulePath = `${withoutExtension}.js`;
  return modulePath.startsWith(".") ? modulePath : `./${modulePath}`;
}

async function writeGeneratedOutput(path: string, contents: string): Promise<string> {
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, contents);
  return path;
}

async function shouldWriteGeneratedOutput(
  path: string,
  policy: SupaschemaConfig["workflow"]["type_generation"],
  honorWorkflowPolicy: boolean | undefined,
  checkMode = false
): Promise<boolean> {
  if (honorWorkflowPolicy !== true) {
    return true;
  }
  if (policy === "disabled") {
    return false;
  }
  if (policy === "create_or_refresh") {
    return true;
  }
  if (checkMode) {
    return true;
  }
  return await pathExists(path);
}

function skippedGeneratedOutputs(
  typesPath: string,
  typesPolicy: SupaschemaConfig["workflow"]["type_generation"],
  zodPath: string,
  zodPolicy: SupaschemaConfig["workflow"]["zod_generation"]
): string[] {
  const skipped: string[] = [];
  if (typesPolicy === "disabled") {
    skipped.push(`types: skipped ${typesPath} because workflow.type_generation is "disabled"`);
  } else if (typesPolicy === "refresh_existing") {
    skipped.push(`types: skipped ${typesPath} because it does not exist`);
  }
  if (zodPolicy === "disabled") {
    skipped.push(`zod: skipped ${zodPath} because workflow.zod_generation is "disabled"`);
  } else if (zodPolicy === "refresh_existing") {
    skipped.push(`zod: skipped ${zodPath} because it does not exist`);
  }
  return skipped;
}

async function pathExists(path: string): Promise<boolean> {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}
