CREATE SCHEMA app;

CREATE TYPE app.account_status AS ENUM ('active', 'suspended');

CREATE TABLE app.accounts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  status app.account_status DEFAULT 'active'::app.account_status NOT NULL
);

ALTER TABLE app.accounts ENABLE ROW LEVEL SECURITY;

CREATE POLICY accounts_select ON app.accounts
  FOR SELECT
  TO public
  USING (true);

CREATE OR REPLACE VIEW app.account_names AS
  SELECT id, name FROM app.accounts;

COMMENT ON TABLE app.accounts IS 'Customer accounts';
