import { parseFrontmatter, scalar } from "../lib/frontmatter.mjs";

export function renderCodexAgent(sourceText, sourcePath = "agent.md") {
  const parsed = parseClaudeAgent(sourceText, sourcePath);
  const lines = [
    `# Generated by npm run sync:llm from ${parsed.relativeSource}.`,
    "# Do not edit directly; update the Claude agent source and re-run sync.",
    `name = ${tomlString(parsed.name)}`,
    `description = ${tomlString(parsed.description)}`,
  ];

  const sandboxMode = codexSandboxMode(parsed.tools);
  if (sandboxMode) {
    lines.push(`sandbox_mode = ${tomlString(sandboxMode)}`);
  }

  lines.push(`developer_instructions = ${tomlString(parsed.body.trim())}`);
  return `${lines.join("\n")}\n`;
}

export function renderCodexRule(sourceText, sourcePath = "rule.md") {
  const entries = codexExecPolicyEntries(sourceText, sourcePath);
  const lines = [
    `# Generated by npm run sync:llm from ${sourcePath}.`,
    "# Do not edit directly; update the Claude rule source and re-run sync.",
    `# Canonical rule owner: ${sourcePath}.`,
    "# Full Markdown policy stays in the Claude rule source; this file contains Codex command policy only.",
    "",
  ];

  if (entries.length === 0) {
    lines.push("# No codexExecPolicy entries declared by the canonical rule.");
    return `${lines.join("\n").trimEnd()}\n`;
  }

  lines.push("# codexExecPolicy entries generated below.");
  for (const entry of entries) {
    lines.push("", renderPrefixRule(entry));
  }
  return `${lines.join("\n").trimEnd()}\n`;
}

export function codexExecPolicyEntries(sourceText, sourcePath = "rule.md") {
  if (!(sourceText.startsWith("---\n") || sourceText.startsWith("---\r\n"))) {
    return [];
  }
  const { frontmatter } = parseFrontmatter(sourceText, sourcePath);
  const raw = scalar(frontmatter, "codexExecPolicy");
  if (!raw) {
    return [];
  }

  let parsed;
  try {
    parsed = JSON.parse(raw);
  } catch (error) {
    throw new Error(
      `${sourcePath} codexExecPolicy must be valid JSON: ${error instanceof Error ? error.message : String(error)}`
    );
  }
  if (!Array.isArray(parsed)) {
    throw new Error(`${sourcePath} codexExecPolicy must be a JSON array`);
  }
  return parsed.map((entry, index) => normalizeExecPolicyEntry(entry, sourcePath, index));
}

function normalizeExecPolicyEntry(entry, sourcePath, index) {
  const context = `${sourcePath} codexExecPolicy[${index}]`;
  if (!entry || typeof entry !== "object" || Array.isArray(entry)) {
    throw new Error(`${context} must be an object`);
  }
  const pattern = normalizePattern(entry.pattern, `${context}.pattern`);
  const decision = stringField(entry, "decision", context);
  if (!["allow", "prompt", "forbidden"].includes(decision)) {
    throw new Error(`${context}.decision must be allow, prompt, or forbidden`);
  }
  const justification = stringField(entry, "justification", context);
  return {
    decision,
    justification,
    match: optionalStringArray(entry.match, `${context}.match`),
    not_match: optionalStringArray(entry.not_match, `${context}.not_match`),
    pattern,
  };
}

function normalizePattern(value, context) {
  if (!Array.isArray(value) || value.length === 0) {
    throw new Error(`${context} must be a non-empty array`);
  }
  return value.map((item, index) => {
    const itemContext = `${context}[${index}]`;
    if (typeof item === "string" && item.length > 0) {
      return item;
    }
    if (
      Array.isArray(item) &&
      item.length > 0 &&
      item.every((candidate) => typeof candidate === "string" && candidate.length > 0)
    ) {
      return item;
    }
    throw new Error(`${itemContext} must be a non-empty string or non-empty string array`);
  });
}

function stringField(entry, key, context) {
  const value = entry[key];
  if (typeof value !== "string" || value.length === 0) {
    throw new Error(`${context}.${key} must be a non-empty string`);
  }
  return value;
}

function optionalStringArray(value, context) {
  if (value === undefined) {
    return [];
  }
  if (!(Array.isArray(value) && value.every((item) => typeof item === "string"))) {
    throw new Error(`${context} must be a string array`);
  }
  return value;
}

function renderPrefixRule(entry) {
  const lines = [
    "prefix_rule(",
    `    pattern = ${starlarkValue(entry.pattern)},`,
    `    decision = ${starlarkValue(entry.decision)},`,
    `    justification = ${starlarkValue(entry.justification)},`,
  ];
  if (entry.match.length > 0) {
    lines.push(`    match = ${starlarkValue(entry.match)},`);
  }
  if (entry.not_match.length > 0) {
    lines.push(`    not_match = ${starlarkValue(entry.not_match)},`);
  }
  lines.push(")");
  return lines.join("\n");
}

function starlarkValue(value) {
  if (typeof value === "string") {
    return JSON.stringify(value);
  }
  if (Array.isArray(value)) {
    return `[${value.map(starlarkValue).join(", ")}]`;
  }
  throw new Error(`unsupported Starlark value: ${String(value)}`);
}

function parseClaudeAgent(sourceText, sourcePath) {
  const { body, frontmatter } = parseFrontmatter(sourceText, sourcePath);
  const name = scalar(frontmatter, "name");
  const description = scalar(frontmatter, "description");
  if (!name) {
    throw new Error(`missing agent name in ${sourcePath}`);
  }
  if (!description) {
    throw new Error(`missing agent description in ${sourcePath}`);
  }
  return {
    body,
    description,
    name,
    relativeSource: sourcePath,
    tools: splitTools(scalar(frontmatter, "tools")),
  };
}

function splitTools(value) {
  if (!value) {
    return [];
  }
  return value
    .split(",")
    .map((item) => item.trim())
    .filter(Boolean);
}

function codexSandboxMode(tools) {
  if (tools.length === 0) {
    return;
  }
  if (tools.includes("*")) {
    return "workspace-write";
  }
  const writeTools = new Set(["Write", "Edit", "MultiEdit", "NotebookEdit", "apply_patch"]);
  return tools.some((tool) => writeTools.has(tool)) ? "workspace-write" : "read-only";
}

function tomlString(value) {
  return JSON.stringify(stripTomlUnsafeControls(value));
}

function stripTomlUnsafeControls(value) {
  let out = "";
  for (const char of value) {
    const code = char.charCodeAt(0);
    if (code === 0x09 || code === 0x0a || code === 0x0d || code >= 0x20) {
      out += char;
    }
  }
  return out;
}
