#!/usr/bin/env node
import { randomUUID } from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

export const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..");

export const agentSurfaceManifest = {
  hooks: [
    {
      source: ".claude/hooks/guards/bash-policy-checks.mjs",
      target: ".codex/hooks/guards/bash-policy-checks.mjs",
    },
    {
      source: ".claude/hooks/sync-llm-on-claude-surface-change.mjs",
      target: ".codex/hooks/sync-llm-on-claude-surface-change.mjs",
    },
  ],
  publicSkills: {
    sourceRoot: ".claude/skills/supaschema",
    targetRoot: "skills/supaschema",
  },
  rules: {
    source: ".claude/rules/supaschema.md",
    target: ".codex/rules/supaschema.rules",
  },
  skills: {
    sourceRoot: ".claude/skills/supaschema",
    targetRoot: ".agents/skills/supaschema",
  },
};

export function runCli(argv = process.argv.slice(2), root = ROOT) {
  const args = new Set(argv);
  const unknown = argv.filter((arg) => arg !== "--check");
  if (unknown.length > 0) {
    process.stderr.write(`Unknown sync:llm argument(s): ${unknown.join(", ")}\n`);
    process.exit(2);
  }

  if (args.has("--check")) {
    const errors = checkAgentSurfaces({ root });
    if (errors.length > 0) {
      process.stderr.write(`${errors.join("\n")}\n`);
      process.exit(1);
    }
    process.stdout.write("SYNC_LLM_CHECK_OK\n");
    return;
  }

  const result = syncAgentSurfaces({ root });
  process.stdout.write(
    `SYNC_LLM_OK skills=${result.skills} publicSkills=${result.publicSkills} hooks=${result.hooks} rules=${result.rules}\n`
  );
}

export function syncAgentSurfaces({ root = ROOT } = {}) {
  const skills = syncDirectoryMirror(root, agentSurfaceManifest.skills).files;
  const publicSkills = syncDirectoryMirror(root, agentSurfaceManifest.publicSkills).files;
  const hooks = syncFileMirrors(root, agentSurfaceManifest.hooks);
  const rules = syncCodexRule(root);
  return { hooks, publicSkills, rules, skills };
}

export function checkAgentSurfaces({ root = ROOT } = {}) {
  const errors = [];
  checkDirectoryMirror(root, agentSurfaceManifest.skills, errors);
  checkDirectoryMirror(root, agentSurfaceManifest.publicSkills, errors);
  checkFileMirrors(root, agentSurfaceManifest.hooks, errors);
  checkCodexRule(root, errors);
  return errors;
}

export function renderCodexRule(sourceText, sourcePath = "rule.md") {
  const lines = [
    `# Generated by npm run sync:llm from ${sourcePath}.`,
    "# Do not edit directly; update the Claude rule source and re-run sync.",
    "# Codex .rules files are command-policy programs, so Claude Markdown policy is mirrored as comments.",
    "",
    ...splitLines(sourceText).map((line) => `#${line ? ` ${line}` : ""}`),
  ];
  return `${lines.join("\n").trimEnd()}\n`;
}

function syncCodexRule(root) {
  const source = path.join(root, agentSurfaceManifest.rules.source);
  const target = path.join(root, agentSurfaceManifest.rules.target);
  assertFile(source, `missing source rule ${agentSurfaceManifest.rules.source}`);
  syncTextFiles(
    path.dirname(target),
    new Map([
      [
        path.basename(target),
        renderCodexRule(fs.readFileSync(source, "utf8"), agentSurfaceManifest.rules.source),
      ],
    ])
  );
  return 1;
}

function checkCodexRule(root, errors) {
  const source = path.join(root, agentSurfaceManifest.rules.source);
  const target = path.join(root, agentSurfaceManifest.rules.target);
  if (!fs.existsSync(source)) {
    errors.push(`missing source rule ${agentSurfaceManifest.rules.source}`);
    return;
  }
  if (!fs.existsSync(target)) {
    errors.push(`missing rendered rule ${agentSurfaceManifest.rules.target}`);
    return;
  }
  const expected = renderCodexRule(
    fs.readFileSync(source, "utf8"),
    agentSurfaceManifest.rules.source
  );
  const actual = fs.readFileSync(target, "utf8");
  if (actual !== expected) {
    errors.push(`rendered rule drifted for ${agentSurfaceManifest.rules.target}`);
  }
}

function syncFileMirrors(root, pairs) {
  const files = new Map();
  for (const pair of pairs) {
    const source = path.join(root, pair.source);
    assertFile(source, `missing source file ${pair.source}`);
    files.set(pair.target, fs.readFileSync(source));
  }
  for (const [target, content] of files) {
    writeFileAtomic(path.join(root, target), content);
  }
  return files.size;
}

function checkFileMirrors(root, pairs, errors) {
  for (const pair of pairs) {
    const source = path.join(root, pair.source);
    const target = path.join(root, pair.target);
    if (!fs.existsSync(source)) {
      errors.push(`missing source file ${pair.source}`);
      continue;
    }
    if (!fs.existsSync(target)) {
      errors.push(`missing mirror file ${pair.target}`);
      continue;
    }
    if (!fs.readFileSync(source).equals(fs.readFileSync(target))) {
      errors.push(`mirror drifted for ${pair.target}`);
    }
  }
}

function syncDirectoryMirror(root, surface) {
  const sourceRootPath = path.join(root, surface.sourceRoot);
  const targetRootPath = path.join(root, surface.targetRoot);
  assertDirectory(sourceRootPath, `missing source dir ${surface.sourceRoot}`);
  const sourceFiles = listFiles(sourceRootPath);
  syncCopiedFiles(sourceRootPath, targetRootPath, sourceFiles);
  return { files: sourceFiles.length };
}

function checkDirectoryMirror(root, surface, errors) {
  const sourceRootPath = path.join(root, surface.sourceRoot);
  const targetRootPath = path.join(root, surface.targetRoot);
  if (!fs.existsSync(sourceRootPath)) {
    errors.push(`missing source dir ${surface.sourceRoot}`);
    return;
  }
  if (!fs.existsSync(targetRootPath)) {
    errors.push(`missing mirror dir ${surface.targetRoot}`);
    return;
  }

  const sourceFiles = listFiles(sourceRootPath);
  const targetFiles = listFiles(targetRootPath);
  pushFileSetErrors(surface, sourceFiles, targetFiles, errors);

  for (const file of sourceFiles.filter((item) => targetFiles.includes(item))) {
    const sourceFile = path.join(sourceRootPath, file);
    const targetFile = path.join(targetRootPath, file);
    if (!fs.readFileSync(sourceFile).equals(fs.readFileSync(targetFile))) {
      errors.push(`mirror drifted for ${surface.targetRoot}: ${file}`);
    }
  }
}

function pushFileSetErrors(surface, expectedFiles, actualFiles, errors) {
  const missing = expectedFiles.filter((file) => !actualFiles.includes(file));
  const extra = actualFiles.filter((file) => !expectedFiles.includes(file));
  if (missing.length > 0) {
    errors.push(`mirror ${surface.targetRoot} missing files: ${missing.join(", ")}`);
  }
  if (extra.length > 0) {
    errors.push(`mirror ${surface.targetRoot} has unmanaged files: ${extra.join(", ")}`);
  }
}

function syncCopiedFiles(sourceRootPath, targetRootPath, sourceFiles) {
  const renderedFiles = new Map();
  for (const file of sourceFiles) {
    renderedFiles.set(file, fs.readFileSync(path.join(sourceRootPath, file)));
  }
  syncBinaryFiles(targetRootPath, renderedFiles);
}

function syncTextFiles(targetRootPath, renderedFiles) {
  syncBinaryFiles(
    targetRootPath,
    new Map([...renderedFiles].map(([file, content]) => [file, Buffer.from(content)]))
  );
}

function syncBinaryFiles(targetRootPath, renderedFiles) {
  fs.mkdirSync(targetRootPath, { recursive: true });
  for (const stale of listFiles(targetRootPath)) {
    if (!renderedFiles.has(stale)) {
      fs.rmSync(path.join(targetRootPath, stale));
    }
  }
  for (const [file, content] of renderedFiles) {
    writeFileAtomic(path.join(targetRootPath, file), content);
  }
}

function writeFileAtomic(targetPath, content) {
  fs.mkdirSync(path.dirname(targetPath), { recursive: true });
  const tempPath = path.join(path.dirname(targetPath), `.tmp-${process.pid}-${randomUUID()}`);
  fs.writeFileSync(tempPath, content, { flag: "wx" });
  fs.renameSync(tempPath, targetPath);
}

function listFiles(root) {
  const out = [];
  if (!fs.existsSync(root)) {
    return out;
  }
  const visit = (dir) => {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const absolute = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        visit(absolute);
      } else if (entry.isFile()) {
        out.push(path.relative(root, absolute).split(path.sep).join("/"));
      }
    }
  };
  visit(root);
  return out.sort();
}

function splitLines(text) {
  return text.split("\r\n").join("\n").split("\n");
}

function assertDirectory(dir, message) {
  if (!(fs.existsSync(dir) && fs.statSync(dir).isDirectory())) {
    throw new Error(message);
  }
}

function assertFile(file, message) {
  if (!(fs.existsSync(file) && fs.statSync(file).isFile())) {
    throw new Error(message);
  }
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  runCli();
}
