#!/usr/bin/env node
import { randomUUID } from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  hookConfigsFor,
  localRunnerForPackageManager,
  materializeCodexRunner,
} from "../../bin/scaffold.mjs";
import { parseFrontmatter, scalar } from "../lib/frontmatter.mjs";

export const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..");

export const agentSurfaceManifest = {
  agents: {
    sourceRoot: ".claude/agents",
    targetRoot: ".codex/agents",
  },
  hooks: {
    sourceRoot: ".claude/hooks",
    targetRoot: ".codex/hooks",
  },
  publicSkills: {
    sourceRoot: ".claude/skills/supaschema",
    targetRoot: "skills/supaschema",
  },
  agentBundle: {
    targetRoot: "agent-bundle",
  },
  rules: {
    sourceRoot: ".claude/rules",
    targetRoot: ".codex/rules",
  },
  skills: {
    sourceRoot: ".claude/skills",
    targetRoots: [".agents/skills"],
  },
};

export function runCli(argv = process.argv.slice(2), root = ROOT) {
  const args = new Set(argv);
  const unknown = argv.filter((arg) => arg !== "--check");
  if (unknown.length > 0) {
    process.stderr.write(`Unknown sync:llm argument(s): ${unknown.join(", ")}\n`);
    process.exit(2);
  }

  if (args.has("--check")) {
    const errors = checkAgentSurfaces({ root });
    if (errors.length > 0) {
      process.stderr.write(`${errors.join("\n")}\n`);
      process.exit(1);
    }
    process.stdout.write("SYNC_LLM_CHECK_OK\n");
    return;
  }

  const result = syncAgentSurfaces({ root });
  process.stdout.write(
    `SYNC_LLM_OK skills=${result.skills} skillTargets=${result.skillTargets} publicSkills=${result.publicSkills} agents=${result.agents} hooks=${result.hooks} rules=${result.rules} agentBundle=${result.agentBundle}\n`
  );
}

export function syncAgentSurfaces({ root = ROOT } = {}) {
  const skillResult = syncSkills(root);
  const publicSkillResult = syncPublicSkills(root);
  const hookResult = syncDirectoryMirror(root, agentSurfaceManifest.hooks);
  const agentResult = syncCodexAgents(root);
  const ruleResult = syncCodexRules(root);
  const agentBundleResult = syncAgentBundle(root);

  return {
    agentBundle: agentBundleResult.files,
    agents: agentResult.files,
    hooks: hookResult.files,
    publicSkills: publicSkillResult.files,
    rules: ruleResult.files,
    skillTargets: skillResult.targets,
    skills: skillResult.files,
  };
}

export function checkAgentSurfaces({ root = ROOT } = {}) {
  const errors = [];
  checkSkills(root, errors);
  checkPublicSkills(root, errors);
  checkDirectoryMirror(root, agentSurfaceManifest.hooks, errors);
  checkCodexAgents(root, errors);
  checkCodexRules(root, errors);
  checkAgentBundle(root, errors);
  return errors;
}

export function renderCodexAgent(sourceText, sourcePath = "agent.md") {
  const parsed = parseClaudeAgent(sourceText, sourcePath);
  const lines = [
    `# Generated by npm run sync:llm from ${parsed.relativeSource}.`,
    "# Do not edit directly; update the Claude agent source and re-run sync.",
    `name = ${tomlString(parsed.name)}`,
    `description = ${tomlString(parsed.description)}`,
  ];

  const sandboxMode = codexSandboxMode(parsed.tools);
  if (sandboxMode) {
    lines.push(`sandbox_mode = ${tomlString(sandboxMode)}`);
  }

  lines.push(`developer_instructions = ${tomlString(parsed.body.trim())}`);
  return `${lines.join("\n")}\n`;
}

export function renderCodexRule(sourceText, sourcePath = "rule.md") {
  const lines = [
    `# Generated by npm run sync:llm from ${sourcePath}.`,
    "# Do not edit directly; update the Claude rule source and re-run sync.",
    "# Codex .rules files are command-policy programs, so Claude Markdown policy is mirrored as comments.",
    "",
    ...splitLines(sourceText).map((line) => `#${line ? ` ${line}` : ""}`),
  ];
  return `${lines.join("\n").trimEnd()}\n`;
}

function syncSkills(root) {
  const { sourceRoot, targetRoots } = agentSurfaceManifest.skills;
  let files = 0;
  let targets = 0;

  for (const targetRoot of targetRoots) {
    const result = syncDirectoryMirror(root, { sourceRoot, targetRoot });
    files = result.files;
    targets += 1;
  }

  return { files, targets };
}

function syncPublicSkills(root) {
  return syncDirectoryMirror(root, agentSurfaceManifest.publicSkills);
}

function syncAgentBundle(root) {
  const targetRootPath = path.join(root, agentSurfaceManifest.agentBundle.targetRoot);
  const files = agentBundleFiles(root);
  syncTextFiles(targetRootPath, files);
  return { files: files.size };
}

function checkAgentBundle(root, errors) {
  const targetRootPath = path.join(root, agentSurfaceManifest.agentBundle.targetRoot);
  if (!fs.existsSync(targetRootPath)) {
    errors.push(`missing raw agent bundle dir ${agentSurfaceManifest.agentBundle.targetRoot}`);
    return;
  }
  const expected = safeAgentBundleFiles(root, errors);
  if (expected.size === 0) {
    return;
  }
  const actualFiles = listFiles(targetRootPath);
  pushFileSetErrors(
    { targetRoot: agentSurfaceManifest.agentBundle.targetRoot },
    [...expected.keys()],
    actualFiles,
    errors
  );
  for (const [file, expectedText] of expected) {
    if (!actualFiles.includes(file)) {
      continue;
    }
    const actualText = fs.readFileSync(path.join(targetRootPath, file), "utf8");
    if (actualText !== expectedText) {
      errors.push(`raw agent bundle drifted: ${file}`);
    }
  }
}

function safeAgentBundleFiles(root, errors) {
  try {
    return agentBundleFiles(root);
  } catch (error) {
    errors.push(
      error instanceof Error ? `raw agent bundle input missing: ${error.message}` : String(error)
    );
    return new Map();
  }
}

function agentBundleFiles(root) {
  const files = new Map([
    ["INSTALL.md", fs.readFileSync(path.join(root, "agent-bundle", "INSTALL.md"), "utf8")],
    [
      "agents/prompts/supaschema-install.md",
      fs.readFileSync(path.join(root, ".agents/prompts/supaschema-install.md"), "utf8"),
    ],
    [
      "agents/skills/supaschema/SKILL.md",
      fs.readFileSync(path.join(root, ".agents/skills/supaschema/SKILL.md"), "utf8"),
    ],
    [
      "claude/hooks/guards/bash-policy-checks.mjs",
      fs.readFileSync(path.join(root, ".claude/hooks/guards/bash-policy-checks.mjs"), "utf8"),
    ],
    [
      "claude/hooks/sync-llm-on-claude-surface-change.mjs",
      fs.readFileSync(
        path.join(root, ".claude/hooks/sync-llm-on-claude-surface-change.mjs"),
        "utf8"
      ),
    ],
    [
      "claude/rules/supaschema.md",
      fs.readFileSync(path.join(root, ".claude/rules/supaschema.md"), "utf8"),
    ],
    [
      "claude/skills/supaschema/SKILL.md",
      fs.readFileSync(path.join(root, ".claude/skills/supaschema/SKILL.md"), "utf8"),
    ],
    [
      "codex/hooks/general-guard.mjs",
      fs.readFileSync(path.join(root, ".codex/hooks/general-guard.mjs"), "utf8"),
    ],
    [
      "codex/hooks/guards/bash-policy-checks.mjs",
      fs.readFileSync(path.join(root, ".codex/hooks/guards/bash-policy-checks.mjs"), "utf8"),
    ],
    [
      "codex/hooks/sync-llm-on-claude-surface-change.mjs",
      fs.readFileSync(
        path.join(root, ".codex/hooks/sync-llm-on-claude-surface-change.mjs"),
        "utf8"
      ),
    ],
    [
      "codex/rules/supaschema.rules",
      fs.readFileSync(path.join(root, ".codex/rules/supaschema.rules"), "utf8"),
    ],
  ]);

  for (const packageManager of ["npm", "pnpm", "yarn", "bun"]) {
    const runner = localRunnerForPackageManager(packageManager);
    const claudeSettings = hookConfigsFor(root, packageManager).find(
      (config) => config.path === ".claude/settings.json"
    )?.config;
    const codexHooks = materializeCodexRunner(
      consumerCodexHooks(JSON.parse(fs.readFileSync(path.join(root, ".codex/hooks.json"), "utf8"))),
      runner
    );
    files.set(`claude/settings.${packageManager}.json`, jsonText(claudeSettings));
    files.set(`codex/hooks.${packageManager}.json`, jsonText(codexHooks));
  }

  return files;
}

function jsonText(value) {
  return `${JSON.stringify(value, null, 2)}\n`;
}

function consumerCodexHooks(config) {
  const next = structuredClone(config);
  const hooks = next?.hooks;
  if (!hooks || typeof hooks !== "object") {
    return next;
  }
  for (const [eventName, entries] of Object.entries(hooks)) {
    if (!Array.isArray(entries)) {
      continue;
    }
    hooks[eventName] = entries
      .map(withoutRepoLocalCodexHooks)
      .filter((entry) => entry !== undefined);
  }
  return next;
}

function withoutRepoLocalCodexHooks(entry) {
  if (!entry || typeof entry !== "object") {
    return entry;
  }
  if (isRepoLocalCodexHook(entry)) {
    return;
  }
  if (!Array.isArray(entry.hooks)) {
    return entry;
  }
  const hooks = entry.hooks.filter((hook) => !isRepoLocalCodexHook(hook));
  return hooks.length > 0 ? { ...entry, hooks } : undefined;
}

function isRepoLocalCodexHook(hook) {
  return (
    hook &&
    typeof hook === "object" &&
    typeof hook.command === "string" &&
    hook.command.includes("scripts/github/ci-inbox.mjs")
  );
}

function syncDirectoryMirror(root, surface) {
  const sourceRootPath = path.join(root, surface.sourceRoot);
  const targetRootPath = path.join(root, surface.targetRoot);
  assertDirectory(sourceRootPath, `missing source dir ${surface.sourceRoot}`);
  const sourceFiles = listFiles(sourceRootPath);
  syncCopiedFiles(sourceRootPath, targetRootPath, sourceFiles);
  return { files: sourceFiles.length };
}

function syncCodexAgents(root) {
  const { sourceRoot, targetRoot } = agentSurfaceManifest.agents;
  const sourceRootPath = path.join(root, sourceRoot);
  const targetRootPath = path.join(root, targetRoot);
  assertDirectory(sourceRootPath, `missing source agent dir ${sourceRoot}`);

  const sourceFiles = listFiles(sourceRootPath);
  const renderedFiles = new Map();
  for (const file of sourceFiles) {
    assertMarkdownFile(sourceRoot, file, "agent");
    const sourcePath = path.join(sourceRootPath, file);
    renderedFiles.set(
      codexTargetPath(file, ".toml"),
      renderCodexAgent(fs.readFileSync(sourcePath, "utf8"), display(root, sourcePath))
    );
  }
  syncTextFiles(targetRootPath, renderedFiles);

  return { files: sourceFiles.length };
}

function syncCodexRules(root) {
  const { sourceRoot, targetRoot } = agentSurfaceManifest.rules;
  const sourceRootPath = path.join(root, sourceRoot);
  const targetRootPath = path.join(root, targetRoot);
  assertDirectory(sourceRootPath, `missing source rule dir ${sourceRoot}`);

  const sourceFiles = listFiles(sourceRootPath);
  const renderedFiles = new Map();
  for (const file of sourceFiles) {
    assertMarkdownFile(sourceRoot, file, "rule");
    const sourcePath = path.join(sourceRootPath, file);
    renderedFiles.set(
      codexTargetPath(file, ".rules"),
      renderCodexRule(fs.readFileSync(sourcePath, "utf8"), display(root, sourcePath))
    );
  }
  syncTextFiles(targetRootPath, renderedFiles);

  return { files: sourceFiles.length };
}

function checkSkills(root, errors) {
  const { sourceRoot, targetRoots } = agentSurfaceManifest.skills;
  for (const targetRoot of targetRoots) {
    checkDirectoryMirror(root, { sourceRoot, targetRoot }, errors);
  }
}

function checkPublicSkills(root, errors) {
  checkDirectoryMirror(root, agentSurfaceManifest.publicSkills, errors);
}

function checkDirectoryMirror(root, surface, errors) {
  const sourceRootPath = path.join(root, surface.sourceRoot);
  const targetRootPath = path.join(root, surface.targetRoot);
  if (!fs.existsSync(sourceRootPath)) {
    errors.push(`missing source dir ${surface.sourceRoot}`);
    return;
  }
  if (!fs.existsSync(targetRootPath)) {
    errors.push(`missing mirror dir ${surface.targetRoot}`);
    return;
  }

  const sourceFiles = listFiles(sourceRootPath);
  const targetFiles = listFiles(targetRootPath);
  pushFileSetErrors(surface, sourceFiles, targetFiles, errors);

  for (const file of sourceFiles.filter((item) => targetFiles.includes(item))) {
    const sourceFile = path.join(sourceRootPath, file);
    const targetFile = path.join(targetRootPath, file);
    if (!fs.readFileSync(sourceFile).equals(fs.readFileSync(targetFile))) {
      errors.push(`mirror drifted for ${surface.targetRoot}: ${file}`);
    }
  }
}

function checkCodexAgents(root, errors) {
  const { sourceRoot, targetRoot } = agentSurfaceManifest.agents;
  checkRenderedMirror(
    root,
    { extension: ".toml", sourceRoot, targetRoot },
    renderCodexAgent,
    errors
  );
}

function checkCodexRules(root, errors) {
  const { sourceRoot, targetRoot } = agentSurfaceManifest.rules;
  checkRenderedMirror(
    root,
    { extension: ".rules", sourceRoot, targetRoot },
    renderCodexRule,
    errors
  );
}

function checkRenderedMirror(root, surface, render, errors) {
  const sourceRootPath = path.join(root, surface.sourceRoot);
  const targetRootPath = path.join(root, surface.targetRoot);
  if (!fs.existsSync(sourceRootPath)) {
    errors.push(`missing source dir ${surface.sourceRoot}`);
    return;
  }
  if (!fs.existsSync(targetRootPath)) {
    errors.push(`missing rendered mirror dir ${surface.targetRoot}`);
    return;
  }

  const sourceFiles = listFiles(sourceRootPath);
  for (const file of sourceFiles) {
    try {
      assertMarkdownFile(surface.sourceRoot, file, "source");
    } catch (error) {
      errors.push(error instanceof Error ? error.message : String(error));
    }
  }
  const expectedFiles = sourceFiles.map((file) => codexTargetPath(file, surface.extension));
  const targetFiles = listFiles(targetRootPath);
  pushFileSetErrors(surface, expectedFiles, targetFiles, errors);

  for (const file of sourceFiles) {
    const targetFile = codexTargetPath(file, surface.extension);
    if (!targetFiles.includes(targetFile)) {
      continue;
    }
    const sourcePath = path.join(sourceRootPath, file);
    const expected = render(fs.readFileSync(sourcePath, "utf8"), display(root, sourcePath));
    const actual = fs.readFileSync(path.join(targetRootPath, targetFile), "utf8");
    if (actual !== expected) {
      errors.push(`rendered mirror drifted for ${surface.targetRoot}: ${targetFile}`);
    }
  }
}

function pushFileSetErrors(surface, expectedFiles, actualFiles, errors) {
  const missing = expectedFiles.filter((file) => !actualFiles.includes(file));
  const extra = actualFiles.filter((file) => !expectedFiles.includes(file));
  if (missing.length > 0) {
    errors.push(`mirror ${surface.targetRoot} missing files: ${missing.join(", ")}`);
  }
  if (extra.length > 0) {
    errors.push(`mirror ${surface.targetRoot} has unmanaged files: ${extra.join(", ")}`);
  }
}

function parseClaudeAgent(sourceText, sourcePath) {
  const { body, frontmatter } = parseFrontmatter(sourceText, sourcePath);
  const name = scalar(frontmatter, "name");
  const description = scalar(frontmatter, "description");
  if (!name) {
    throw new Error(`missing agent name in ${sourcePath}`);
  }
  if (!description) {
    throw new Error(`missing agent description in ${sourcePath}`);
  }
  return {
    body,
    description,
    name,
    relativeSource: sourcePath,
    tools: splitTools(scalar(frontmatter, "tools")),
  };
}

function splitTools(value) {
  if (!value) {
    return [];
  }
  return value
    .split(",")
    .map((item) => item.trim())
    .filter(Boolean);
}

function codexSandboxMode(tools) {
  if (tools.length === 0) {
    return;
  }
  if (tools.includes("*")) {
    return "workspace-write";
  }
  const writeTools = new Set(["Write", "Edit", "MultiEdit", "NotebookEdit", "apply_patch"]);
  return tools.some((tool) => writeTools.has(tool)) ? "workspace-write" : "read-only";
}

function assertDirectory(dir, message) {
  if (!fs.existsSync(dir)) {
    throw new Error(message);
  }
}

function assertMarkdownFile(root, file, kind) {
  if (!file.endsWith(".md")) {
    throw new Error(`${kind} mirror only supports Markdown sources under ${root}: ${file}`);
  }
}

function writeFileIfChanged(file, text) {
  const current = readExistingFile(file, "utf8");
  if (current === text) {
    return;
  }
  writeFileAtomic(file, text);
}

function syncCopiedFiles(sourceRootPath, targetRootPath, sourceFiles) {
  fs.mkdirSync(targetRootPath, { recursive: true });
  for (const file of sourceFiles) {
    copyFileIfChanged(path.join(sourceRootPath, file), path.join(targetRootPath, file));
  }
  removeUnmanagedFiles(targetRootPath, new Set(sourceFiles));
}

function syncTextFiles(targetRootPath, filesToText) {
  fs.mkdirSync(targetRootPath, { recursive: true });
  for (const [file, text] of filesToText) {
    writeFileIfChanged(path.join(targetRootPath, file), text);
  }
  removeUnmanagedFiles(targetRootPath, new Set(filesToText.keys()));
}

function copyFileIfChanged(sourceFile, targetFile) {
  const sourceBytes = fs.readFileSync(sourceFile);
  const currentBytes = readExistingFile(targetFile);
  if (currentBytes?.equals(sourceBytes)) {
    return;
  }
  writeFileAtomic(targetFile, sourceBytes);
}

function readExistingFile(file, encoding) {
  try {
    return encoding ? fs.readFileSync(file, encoding) : fs.readFileSync(file);
  } catch (error) {
    if (isNotFoundError(error)) {
      return;
    }
    throw error;
  }
}

function writeFileAtomic(file, content) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  const tempFile = createExclusiveTempFile(path.dirname(file), path.basename(file), content);
  try {
    fs.renameSync(tempFile, file);
  } catch (error) {
    fs.rmSync(tempFile, { force: true });
    throw error;
  }
}

function createExclusiveTempFile(dir, basename, content) {
  for (let attempt = 0; attempt < 10; attempt += 1) {
    const tempFile = path.join(dir, `.${basename}.${process.pid}.${randomUUID()}.tmp`);
    try {
      fs.writeFileSync(tempFile, content, { flag: "wx" });
      return tempFile;
    } catch (error) {
      if (isAlreadyExistsError(error)) {
        continue;
      }
      throw error;
    }
  }
  throw new Error(`unable to create exclusive temp file for ${path.join(dir, basename)}`);
}

function isNotFoundError(error) {
  return Boolean(error && typeof error === "object" && error.code === "ENOENT");
}

function isAlreadyExistsError(error) {
  return Boolean(error && typeof error === "object" && error.code === "EEXIST");
}

function removeUnmanagedFiles(targetRootPath, expectedFiles) {
  for (const file of listFiles(targetRootPath)) {
    if (!expectedFiles.has(file)) {
      fs.rmSync(path.join(targetRootPath, file), { force: true });
    }
  }
  pruneEmptyDirectories(targetRootPath);
  fs.mkdirSync(targetRootPath, { recursive: true });
}

function pruneEmptyDirectories(root) {
  if (!fs.existsSync(root)) {
    return;
  }

  const visit = (dir) => {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      if (entry.isDirectory()) {
        visit(path.join(dir, entry.name));
      }
    }
    if (dir !== root && fs.readdirSync(dir).length === 0) {
      fs.rmdirSync(dir);
    }
  };
  visit(root);
}

function listFiles(root) {
  if (!fs.existsSync(root)) {
    return [];
  }
  const out = [];
  const visit = (dir) => {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const absolute = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        visit(absolute);
      } else if (entry.isFile()) {
        out.push(path.relative(root, absolute).split(path.sep).join("/"));
      }
    }
  };
  visit(root);
  return out.sort();
}

function codexTargetPath(file, extension) {
  return file.endsWith(".md") ? `${file.slice(0, -3)}${extension}` : `${file}${extension}`;
}

function tomlString(value) {
  return JSON.stringify(stripTomlUnsafeControls(value));
}

function stripTomlUnsafeControls(value) {
  let out = "";
  for (const char of value) {
    const code = char.charCodeAt(0);
    if (code === 0x09 || code === 0x0a || code === 0x0d || code >= 0x20) {
      out += char;
    }
  }
  return out;
}

function splitLines(value) {
  return value.split("\n").map((line) => (line.endsWith("\r") ? line.slice(0, -1) : line));
}

function display(root, file) {
  return path.relative(root, file).split(path.sep).join("/");
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  runCli();
}
