#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

export const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..");

export const agentSurfaceManifest = {
  agents: {
    sourceRoot: ".claude/agents",
    targetRoot: ".codex/agents",
  },
  hooks: {
    sourceRoot: ".claude/hooks",
    targetRoot: ".codex/hooks",
  },
  rules: {
    sourceRoot: ".claude/rules",
    targetRoot: ".codex/rules",
  },
  skills: {
    sourceRoot: ".claude/skills",
    targetRoots: [".agents/skills", ".codex/skills"],
  },
};

const frontmatterLinePattern = /\r?\n/;
const listItemPattern = /^\s+-\s+(.+)\s*$/;
const listStartPattern = /^([A-Za-z][A-Za-z0-9]*):\s*$/;
const rootScalarStartPattern = /^[A-Za-z][A-Za-z0-9]*:/;
const scalarLinePattern = /^([A-Za-z][A-Za-z0-9]*):\s*(.*)\s*$/;
const leadingWhitespacePattern = /^\s*/;
const markdownExtensionPattern = /\.md$/;

export function runCli(argv = process.argv.slice(2), root = ROOT) {
  const args = new Set(argv);
  const unknown = argv.filter((arg) => arg !== "--check");
  if (unknown.length > 0) {
    process.stderr.write(`Unknown sync:llm argument(s): ${unknown.join(", ")}\n`);
    process.exit(2);
  }

  if (args.has("--check")) {
    const errors = checkAgentSurfaces({ root });
    if (errors.length > 0) {
      process.stderr.write(`${errors.join("\n")}\n`);
      process.exit(1);
    }
    process.stdout.write("SYNC_LLM_CHECK_OK\n");
    return;
  }

  const result = syncAgentSurfaces({ root });
  process.stdout.write(
    `SYNC_LLM_OK skills=${result.skills} skillTargets=${result.skillTargets} agents=${result.agents} hooks=${result.hooks} rules=${result.rules}\n`
  );
}

export function syncAgentSurfaces({ root = ROOT } = {}) {
  const skillResult = syncSkills(root);
  const hookResult = syncDirectoryMirror(root, agentSurfaceManifest.hooks);
  const agentResult = syncCodexAgents(root);
  const ruleResult = syncCodexRules(root);

  return {
    agents: agentResult.files,
    hooks: hookResult.files,
    rules: ruleResult.files,
    skillTargets: skillResult.targets,
    skills: skillResult.files,
  };
}

export function checkAgentSurfaces({ root = ROOT } = {}) {
  const errors = [];
  checkSkills(root, errors);
  checkDirectoryMirror(root, agentSurfaceManifest.hooks, errors);
  checkCodexAgents(root, errors);
  checkCodexRules(root, errors);
  return errors;
}

export function renderCodexAgent(sourceText, sourcePath = "agent.md") {
  const parsed = parseClaudeAgent(sourceText, sourcePath);
  const lines = [
    `# Generated by npm run sync:llm from ${parsed.relativeSource}.`,
    "# Do not edit directly; update the Claude agent source and re-run sync.",
    `name = ${tomlString(parsed.name)}`,
    `description = ${tomlString(parsed.description)}`,
  ];

  const sandboxMode = codexSandboxMode(parsed.tools);
  if (sandboxMode) {
    lines.push(`sandbox_mode = ${tomlString(sandboxMode)}`);
  }

  lines.push(`developer_instructions = ${tomlString(parsed.body.trim())}`);
  return `${lines.join("\n")}\n`;
}

export function renderCodexRule(sourceText, sourcePath = "rule.md") {
  const lines = [
    `# Generated by npm run sync:llm from ${sourcePath}.`,
    "# Do not edit directly; update the Claude rule source and re-run sync.",
    "# Codex .rules files are command-policy programs, so Claude Markdown policy is mirrored as comments.",
    "",
    ...sourceText.split(frontmatterLinePattern).map((line) => `#${line ? ` ${line}` : ""}`),
  ];
  return `${lines.join("\n").trimEnd()}\n`;
}

function syncSkills(root) {
  const { sourceRoot, targetRoots } = agentSurfaceManifest.skills;
  let files = 0;
  let targets = 0;

  for (const targetRoot of targetRoots) {
    const result = syncDirectoryMirror(root, { sourceRoot, targetRoot });
    files = result.files;
    targets += 1;
  }

  return { files, targets };
}

function syncDirectoryMirror(root, surface) {
  const sourceRootPath = path.join(root, surface.sourceRoot);
  const targetRootPath = path.join(root, surface.targetRoot);
  assertDirectory(sourceRootPath, `missing source dir ${surface.sourceRoot}`);
  const sourceFiles = listFiles(sourceRootPath);
  syncCopiedFiles(sourceRootPath, targetRootPath, sourceFiles);
  return { files: sourceFiles.length };
}

function syncCodexAgents(root) {
  const { sourceRoot, targetRoot } = agentSurfaceManifest.agents;
  const sourceRootPath = path.join(root, sourceRoot);
  const targetRootPath = path.join(root, targetRoot);
  assertDirectory(sourceRootPath, `missing source agent dir ${sourceRoot}`);

  const sourceFiles = listFiles(sourceRootPath);
  const renderedFiles = new Map();
  for (const file of sourceFiles) {
    assertMarkdownFile(sourceRoot, file, "agent");
    const sourcePath = path.join(sourceRootPath, file);
    renderedFiles.set(
      codexTargetPath(file, ".toml"),
      renderCodexAgent(fs.readFileSync(sourcePath, "utf8"), display(root, sourcePath))
    );
  }
  syncTextFiles(targetRootPath, renderedFiles);

  return { files: sourceFiles.length };
}

function syncCodexRules(root) {
  const { sourceRoot, targetRoot } = agentSurfaceManifest.rules;
  const sourceRootPath = path.join(root, sourceRoot);
  const targetRootPath = path.join(root, targetRoot);
  assertDirectory(sourceRootPath, `missing source rule dir ${sourceRoot}`);

  const sourceFiles = listFiles(sourceRootPath);
  const renderedFiles = new Map();
  for (const file of sourceFiles) {
    assertMarkdownFile(sourceRoot, file, "rule");
    const sourcePath = path.join(sourceRootPath, file);
    renderedFiles.set(
      codexTargetPath(file, ".rules"),
      renderCodexRule(fs.readFileSync(sourcePath, "utf8"), display(root, sourcePath))
    );
  }
  syncTextFiles(targetRootPath, renderedFiles);

  return { files: sourceFiles.length };
}

function checkSkills(root, errors) {
  const { sourceRoot, targetRoots } = agentSurfaceManifest.skills;
  for (const targetRoot of targetRoots) {
    checkDirectoryMirror(root, { sourceRoot, targetRoot }, errors);
  }
}

function checkDirectoryMirror(root, surface, errors) {
  const sourceRootPath = path.join(root, surface.sourceRoot);
  const targetRootPath = path.join(root, surface.targetRoot);
  if (!fs.existsSync(sourceRootPath)) {
    errors.push(`missing source dir ${surface.sourceRoot}`);
    return;
  }
  if (!fs.existsSync(targetRootPath)) {
    errors.push(`missing mirror dir ${surface.targetRoot}`);
    return;
  }

  const sourceFiles = listFiles(sourceRootPath);
  const targetFiles = listFiles(targetRootPath);
  pushFileSetErrors(surface, sourceFiles, targetFiles, errors);

  for (const file of sourceFiles.filter((item) => targetFiles.includes(item))) {
    const sourceFile = path.join(sourceRootPath, file);
    const targetFile = path.join(targetRootPath, file);
    if (!fs.readFileSync(sourceFile).equals(fs.readFileSync(targetFile))) {
      errors.push(`mirror drifted for ${surface.targetRoot}: ${file}`);
    }
  }
}

function checkCodexAgents(root, errors) {
  const { sourceRoot, targetRoot } = agentSurfaceManifest.agents;
  checkRenderedMirror(
    root,
    { sourceRoot, targetRoot, extension: ".toml" },
    renderCodexAgent,
    errors
  );
}

function checkCodexRules(root, errors) {
  const { sourceRoot, targetRoot } = agentSurfaceManifest.rules;
  checkRenderedMirror(
    root,
    { sourceRoot, targetRoot, extension: ".rules" },
    renderCodexRule,
    errors
  );
}

function checkRenderedMirror(root, surface, render, errors) {
  const sourceRootPath = path.join(root, surface.sourceRoot);
  const targetRootPath = path.join(root, surface.targetRoot);
  if (!fs.existsSync(sourceRootPath)) {
    errors.push(`missing source dir ${surface.sourceRoot}`);
    return;
  }
  if (!fs.existsSync(targetRootPath)) {
    errors.push(`missing rendered mirror dir ${surface.targetRoot}`);
    return;
  }

  const sourceFiles = listFiles(sourceRootPath);
  for (const file of sourceFiles) {
    try {
      assertMarkdownFile(surface.sourceRoot, file, "source");
    } catch (error) {
      errors.push(error instanceof Error ? error.message : String(error));
    }
  }
  const expectedFiles = sourceFiles.map((file) => codexTargetPath(file, surface.extension));
  const targetFiles = listFiles(targetRootPath);
  pushFileSetErrors(surface, expectedFiles, targetFiles, errors);

  for (const file of sourceFiles) {
    const targetFile = codexTargetPath(file, surface.extension);
    if (!targetFiles.includes(targetFile)) {
      continue;
    }
    const sourcePath = path.join(sourceRootPath, file);
    const expected = render(fs.readFileSync(sourcePath, "utf8"), display(root, sourcePath));
    const actual = fs.readFileSync(path.join(targetRootPath, targetFile), "utf8");
    if (actual !== expected) {
      errors.push(`rendered mirror drifted for ${surface.targetRoot}: ${targetFile}`);
    }
  }
}

function pushFileSetErrors(surface, expectedFiles, actualFiles, errors) {
  const missing = expectedFiles.filter((file) => !actualFiles.includes(file));
  const extra = actualFiles.filter((file) => !expectedFiles.includes(file));
  if (missing.length > 0) {
    errors.push(`mirror ${surface.targetRoot} missing files: ${missing.join(", ")}`);
  }
  if (extra.length > 0) {
    errors.push(`mirror ${surface.targetRoot} has unmanaged files: ${extra.join(", ")}`);
  }
}

function parseClaudeAgent(sourceText, sourcePath) {
  const { body, frontmatter } = parseFrontmatter(sourceText, sourcePath);
  const name = scalar(frontmatter, "name");
  const description = scalar(frontmatter, "description");
  if (!name) {
    throw new Error(`missing agent name in ${sourcePath}`);
  }
  if (!description) {
    throw new Error(`missing agent description in ${sourcePath}`);
  }
  return {
    body,
    description,
    name,
    relativeSource: sourcePath,
    tools: splitTools(scalar(frontmatter, "tools")),
  };
}

function parseFrontmatter(text, sourcePath) {
  const lines = text.split(frontmatterLinePattern);
  if (lines[0] !== "---") {
    throw new Error(`agent source must start with frontmatter: ${sourcePath}`);
  }
  const frontmatter = new Map();
  let currentList;
  for (let index = 1; index < lines.length; index += 1) {
    const line = lines[index] ?? "";
    if (line === "---") {
      return {
        body: lines.slice(index + 1).join("\n"),
        frontmatter,
      };
    }

    const parsed = readFrontmatterLine(lines, index, frontmatter, currentList);
    currentList = parsed.currentList;
    index = parsed.index;
  }
  throw new Error(`agent frontmatter is not closed: ${sourcePath}`);
}

function readFrontmatterLine(lines, index, frontmatter, currentList) {
  const line = lines[index] ?? "";
  const listItem = line.match(listItemPattern);
  if (currentList && listItem) {
    frontmatter.get(currentList).push(unquote(listItem[1] ?? ""));
    return { currentList, index };
  }

  const scalarLine = line.match(scalarLinePattern);
  if (scalarLine) {
    return readFrontmatterScalar(lines, index, frontmatter, scalarLine);
  }

  const listStart = line.match(listStartPattern);
  if (listStart) {
    const nextList = listStart[1];
    frontmatter.set(nextList, []);
    return { currentList: nextList, index };
  }

  return { currentList, index };
}

function readFrontmatterScalar(lines, index, frontmatter, scalarLine) {
  const key = scalarLine[1] ?? "";
  const value = scalarLine[2] ?? "";
  if (value === "|") {
    const block = readBlockScalar(lines, index + 1);
    frontmatter.set(key, block.value);
    return { currentList: undefined, index: block.end - 1 };
  }
  if (value === "") {
    frontmatter.set(key, []);
    return { currentList: key, index };
  }
  frontmatter.set(key, unquote(value));
  return { currentList: undefined, index };
}

function readBlockScalar(lines, start) {
  const block = [];
  let end = start;
  for (; end < lines.length; end += 1) {
    const line = lines[end] ?? "";
    if (line === "---" || (rootScalarStartPattern.test(line) && block.length > 0)) {
      break;
    }
    block.push(line);
  }
  const indent = Math.min(
    ...block
      .filter((line) => line.trim().length > 0)
      .map((line) => line.match(leadingWhitespacePattern)?.[0].length ?? 0)
  );
  const trimIndent = Number.isFinite(indent) ? indent : 0;
  return {
    end,
    value: block
      .map((line) => line.slice(trimIndent))
      .join("\n")
      .trim(),
  };
}

function splitTools(value) {
  if (!value) {
    return [];
  }
  return value
    .split(",")
    .map((item) => item.trim())
    .filter(Boolean);
}

function codexSandboxMode(tools) {
  if (tools.length === 0) {
    return;
  }
  const writeTools = new Set(["Write", "Edit", "MultiEdit", "NotebookEdit", "apply_patch"]);
  return tools.some((tool) => writeTools.has(tool)) ? "workspace-write" : "read-only";
}

function assertDirectory(dir, message) {
  if (!fs.existsSync(dir)) {
    throw new Error(message);
  }
}

function assertMarkdownFile(root, file, kind) {
  if (!file.endsWith(".md")) {
    throw new Error(`${kind} mirror only supports Markdown sources under ${root}: ${file}`);
  }
}

function writeFileIfChanged(file, text) {
  const current = fs.existsSync(file) ? fs.readFileSync(file, "utf8") : undefined;
  if (current === text) {
    return;
  }
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, text);
}

function syncCopiedFiles(sourceRootPath, targetRootPath, sourceFiles) {
  fs.mkdirSync(targetRootPath, { recursive: true });
  for (const file of sourceFiles) {
    copyFileIfChanged(path.join(sourceRootPath, file), path.join(targetRootPath, file));
  }
  removeUnmanagedFiles(targetRootPath, new Set(sourceFiles));
}

function syncTextFiles(targetRootPath, filesToText) {
  fs.mkdirSync(targetRootPath, { recursive: true });
  for (const [file, text] of filesToText) {
    writeFileIfChanged(path.join(targetRootPath, file), text);
  }
  removeUnmanagedFiles(targetRootPath, new Set(filesToText.keys()));
}

function copyFileIfChanged(sourceFile, targetFile) {
  const sourceBytes = fs.readFileSync(sourceFile);
  const currentBytes = fs.existsSync(targetFile) ? fs.readFileSync(targetFile) : undefined;
  if (currentBytes?.equals(sourceBytes)) {
    return;
  }
  fs.mkdirSync(path.dirname(targetFile), { recursive: true });
  fs.copyFileSync(sourceFile, targetFile);
}

function removeUnmanagedFiles(targetRootPath, expectedFiles) {
  for (const file of listFiles(targetRootPath)) {
    if (!expectedFiles.has(file)) {
      fs.rmSync(path.join(targetRootPath, file), { force: true });
    }
  }
  pruneEmptyDirectories(targetRootPath);
  fs.mkdirSync(targetRootPath, { recursive: true });
}

function pruneEmptyDirectories(root) {
  if (!fs.existsSync(root)) {
    return;
  }

  const visit = (dir) => {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      if (entry.isDirectory()) {
        visit(path.join(dir, entry.name));
      }
    }
    if (dir !== root && fs.readdirSync(dir).length === 0) {
      fs.rmdirSync(dir);
    }
  };
  visit(root);
}

function listFiles(root) {
  if (!fs.existsSync(root)) {
    return [];
  }
  const out = [];
  const visit = (dir) => {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const absolute = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        visit(absolute);
      } else if (entry.isFile()) {
        out.push(path.relative(root, absolute).split(path.sep).join("/"));
      }
    }
  };
  visit(root);
  return out.sort();
}

function codexTargetPath(file, extension) {
  return file.replace(markdownExtensionPattern, extension);
}

function scalar(frontmatter, key) {
  const value = frontmatter.get(key);
  return typeof value === "string" && value.length > 0 ? value : undefined;
}

function tomlString(value) {
  return JSON.stringify(stripTomlUnsafeControls(value));
}

function stripTomlUnsafeControls(value) {
  let out = "";
  for (const char of value) {
    const code = char.charCodeAt(0);
    if (code === 0x09 || code === 0x0a || code === 0x0d || code >= 0x20) {
      out += char;
    }
  }
  return out;
}

function unquote(value) {
  return value.trim().replace(/^["']|["']$/g, "");
}

function display(root, file) {
  return path.relative(root, file).split(path.sep).join("/");
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  runCli();
}
