import { exec, execFile } from "node:child_process";
import { existsSync } from "node:fs";
import { chmod, copyFile, mkdir, mkdtemp, readdir, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { basename, dirname, join, resolve, sep } from "node:path";
import { describe, expect, it } from "vitest";
import { hookMatcherMatchesTool } from "../../scripts/lib/hook-matcher.mjs";

const lineageSql =
  "-- Generated by supaschema.\n-- supaschema: lineage from=abc to=def\nSET lock_timeout = '5s';\n";
const handAuthoredSql = "-- reviewed migration\nINSERT INTO t VALUES (1) ON CONFLICT DO NOTHING;\n";
const cliPath = resolve(import.meta.dirname, "../../dist/cli.js");
const fakeMigrationPath = "supabase/migrations/20260613000000_fake.sql";
const hasClaudeSettings = existsSync(resolve(".claude/settings.json"));
const hasClaudeSessionStartHook = existsSync(resolve(".claude/hooks/context-session-start.mjs"));
const hasCodexSessionStartHook = existsSync(resolve(".codex/hooks/context-session-start.mjs"));
const hasClaudePostToolUseFailureHook = existsSync(
  resolve(".claude/hooks/context-post-tool-use-failure.mjs")
);
const codexGitRoot = ["$(", "git rev-parse --show-toplevel", ")"].join("");
const hasPrivateContextHooks = [
  ".claude/hooks/context-post-tool-use.mjs",
  ".claude/hooks/context-pre-tool-use.mjs",
  ".claude/hooks/context-user-prompt-submit.mjs",
].every((file) => existsSync(resolve(file)));

interface HookOutput {
  decision?: string;
  hookSpecificOutput?: {
    additionalContext?: string;
    permissionDecision?: string;
    permissionDecisionReason?: string;
  };
  reason?: string;
  systemMessage?: string;
}

interface RunHookOptions {
  args?: string[];
  cwd?: string;
  env?: NodeJS.ProcessEnv;
  stdin?: string;
}

async function runHook(
  script: string,
  payload: unknown,
  options: RunHookOptions = {}
): Promise<{ code: number; stderr: string; stdout: string }> {
  return await new Promise((resolvePromise) => {
    const cliArgs = script.startsWith("supaschema hook ")
      ? [cliPath, ...script.split(" ").slice(1)]
      : [resolve(script), ...(options.args ?? [])];
    const child = execFile(
      process.execPath,
      cliArgs,
      { cwd: options.cwd, env: options.env },
      (error, stdout, stderr) => {
        const code = errorCode(error);
        resolvePromise({ code, stderr, stdout });
      }
    );
    child.stdin?.end(options.stdin ?? JSON.stringify(payload));
  });
}

async function runHookCommand(
  command: string,
  payload: unknown,
  options: { cwd: string; env: NodeJS.ProcessEnv }
): Promise<{ code: number; stderr: string; stdout: string }> {
  return await new Promise((resolvePromise) => {
    const child = exec(command, options, (error, stdout, stderr) => {
      resolvePromise({ code: errorCode(error), stderr, stdout });
    });
    child.stdin?.end(JSON.stringify(payload));
  });
}

function errorCode(error: unknown): number {
  if (!isRecord(error)) {
    return 0;
  }
  return typeof error.code === "number" ? error.code : 1;
}

function hookAdditionalContext(stdout: string): string {
  const output = hookOutput(stdout);
  return output.hookSpecificOutput?.additionalContext ?? "";
}

function hookOutput(stdout: string): HookOutput {
  const parsed = jsonRecord(stdout);
  const rawHookOutput = isRecord(parsed.hookSpecificOutput) ? parsed.hookSpecificOutput : {};
  return {
    decision: stringValue(parsed.decision),
    hookSpecificOutput: {
      additionalContext: stringValue(rawHookOutput.additionalContext),
      permissionDecision: stringValue(rawHookOutput.permissionDecision),
      permissionDecisionReason: stringValue(rawHookOutput.permissionDecisionReason),
    },
    reason: stringValue(parsed.reason),
    systemMessage: stringValue(parsed.systemMessage),
  };
}

function jsonRecord(text: string): Record<string, unknown> {
  const parsed: unknown = text.trim().length > 0 ? JSON.parse(text) : {};
  return isRecord(parsed) ? parsed : {};
}

function jsonStringArray(text: string): string[] {
  const parsed: unknown = JSON.parse(text);
  return Array.isArray(parsed) ? parsed.filter((item) => typeof item === "string") : [];
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function stringValue(value: unknown): string | undefined {
  return typeof value === "string" ? value : undefined;
}

async function fixtures(): Promise<{
  generated: string;
  handAuthored: string;
}> {
  const directory = await mkdtemp(join(tmpdir(), "supa-agent-hooks-"));
  const generated = join(directory, "20260611000000_generated.sql");
  const handAuthored = join(directory, "20260611000001_hand.sql");
  await writeFile(generated, lineageSql);
  await writeFile(handAuthored, handAuthoredSql);
  return { generated, handAuthored };
}

async function generatedContractFixture(): Promise<{
  project: string;
  typesFile: string;
  zodFile: string;
}> {
  const project = await mkdtemp(join(tmpdir(), "supa-generated-contract-hook-"));
  const typesFile = join(project, "packages", "database", "src", "types.ts");
  const zodFile = join(project, "packages", "database", "src", "zod.ts");
  await mkdir(dirname(typesFile), { recursive: true });
  await writeFile(typesFile, "export interface Database {}\n");
  await writeFile(zodFile, "export const SupaschemaZod = {};\n");
  await writeFile(
    join(project, "supaschema.config.json"),
    JSON.stringify({
      typesFile: "packages/database/src/types.ts",
      zodFile: "packages/database/src/zod.ts",
    })
  );
  return { project, typesFile, zodFile };
}

async function autoDiffFixture(
  schemaPaths: string[],
  fakeSupaschema?: string,
  options: { writeConfig?: boolean } = {}
): Promise<{
  bin: string;
  env: NodeJS.ProcessEnv;
  log: string;
  project: string;
}> {
  const project = await mkdtemp(join(tmpdir(), "supa-auto-diff-hook-"));
  for (const schemaPath of schemaPaths) {
    await mkdir(join(project, schemaPath), { recursive: true });
  }
  if (options.writeConfig !== false) {
    await writeFile(join(project, "supaschema.config.json"), JSON.stringify({ schemaPaths }));
  }
  const env = Object.fromEntries(
    Object.entries(process.env).filter(([key]) => key !== "SUPASCHEMA_DATABASE_URL")
  );
  const log = join(project, "calls.log");
  const bin = join(project, "fake-supaschema.mjs");
  await writeFile(
    bin,
    fakeSupaschema ??
      `#!/usr/bin/env node
import { appendFileSync } from "node:fs";

appendFileSync(process.env.SUPASCHEMA_FAKE_LOG, JSON.stringify(process.argv.slice(2)) + "\\n");
if (process.argv[2] === "diff") {
  process.stdout.write("${fakeMigrationPath}\\n");
  process.exit(0);
}
if (process.argv[2] === "check") {
  process.exit(0);
}
process.exit(1);
`
  );
  await chmod(bin, 0o755);
  return {
    bin,
    env: { ...env, SUPASCHEMA_FAKE_LOG: log, SUPASCHEMA_HOOK_BIN: bin },
    log,
    project,
  };
}

async function syncHookProject(options: { packageName?: string } = {}): Promise<{
  claudeHook: string;
  codexHook: string;
  env: NodeJS.ProcessEnv;
  log: string;
  project: string;
}> {
  const project = await mkdtemp(join(tmpdir(), "supa-llm-sync-hook-"));
  const log = join(project, "sync.log");
  const npmExecPath = join(project, "fake-npm.mjs");
  const claudeHook = join(project, ".claude/hooks/sync-llm-on-claude-surface-change.mjs");
  const codexHook = join(project, ".codex/hooks/sync-llm-on-claude-surface-change.mjs");
  await mkdir(join(project, ".claude/agents"), { recursive: true });
  await mkdir(join(project, ".claude/hooks"), { recursive: true });
  await mkdir(join(project, ".claude/rules"), { recursive: true });
  await mkdir(join(project, ".claude/skills/demo"), { recursive: true });
  await mkdir(join(project, ".codex/hooks"), { recursive: true });
  await copyFile(resolve(".claude/hooks/sync-llm-on-claude-surface-change.mjs"), claudeHook);
  await copyFile(resolve(".claude/hooks/sync-llm-on-claude-surface-change.mjs"), codexHook);
  await writeFile(
    join(project, "package.json"),
    `${JSON.stringify({
      name: options.packageName ?? "supaschema",
      scripts: { "sync:llm": "node sync.mjs" },
    })}\n`
  );
  await writeFile(
    join(project, "sync.mjs"),
    `import { appendFileSync } from "node:fs";
appendFileSync("sync.log", "sync\\n");
`
  );
  await writeFile(
    npmExecPath,
    `#!/usr/bin/env node
import { appendFileSync } from "node:fs";

appendFileSync("sync.log", "sync\\n");
process.stdout.write("SYNC_LLM_OK\\n");
`
  );
  await chmod(npmExecPath, 0o755);
  await writeFile(
    join(project, ".claude/agents/demo.md"),
    `---
name: demo
description: Demo agent
---

# Demo
`
  );
  await writeFile(join(project, ".claude/hooks/example.mjs"), "console.log('hook');\n");
  await writeFile(join(project, ".claude/rules/supaschema.md"), "# rule\n");
  await writeFile(join(project, ".claude/skills/demo/SKILL.md"), "# skill\n");
  return {
    claudeHook,
    codexHook,
    env: { ...process.env, npm_execpath: npmExecPath },
    log,
    project,
  };
}

async function readFakeCalls(log: string): Promise<string[][]> {
  const content = await readFile(log, "utf8").catch((error: unknown) => {
    if (error instanceof Error && "code" in error && error.code === "ENOENT") {
      return "";
    }
    throw error;
  });
  return content.trim().split("\n").filter(Boolean).map(jsonStringArray);
}

function hookJson(stdout: string): Record<string, unknown> {
  return jsonRecord(stdout);
}

function hookHandlers(value: unknown): Record<string, unknown>[] {
  const out: Record<string, unknown>[] = [];
  const visit = (candidate: unknown) => {
    if (Array.isArray(candidate)) {
      for (const item of candidate) {
        visit(item);
      }
      return;
    }
    if (!(candidate && typeof candidate === "object")) {
      return;
    }
    if (typeof candidate.command === "string" && candidate.type === "command") {
      out.push(candidate);
    }
    for (const item of Object.values(candidate)) {
      visit(item);
    }
  };
  visit(value);
  return out;
}

function hookEntries(
  config: Record<string, unknown>,
  eventName: string
): Record<string, unknown>[] {
  if (!isRecord(config.hooks)) {
    return [];
  }
  const entries = config.hooks[eventName];
  return Array.isArray(entries) ? entries.filter(isRecord) : [];
}

function codexPreToolUseCommandsFor(config: Record<string, unknown>, toolName: string): string[] {
  return hookEntries(config, "PreToolUse")
    .filter((entry) => matcherMentionsTool(entry.matcher, toolName))
    .flatMap((entry) =>
      hookHandlers(entry)
        .map((handler) => handler.command)
        .filter((command): command is string => typeof command === "string")
    );
}

function claudePreToolUseCommandsFor(config: Record<string, unknown>, toolName: string): string[] {
  return hookEntries(config, "PreToolUse")
    .filter((entry) => claudeMatcherMentionsTool(entry.matcher, toolName))
    .flatMap((entry) => hookHandlers(entry).map(handlerCommandText));
}

function claudeMatcherMentionsTool(matcher: unknown, toolName: string): boolean {
  if (typeof matcher !== "string" || matcher.length === 0) {
    return true;
  }
  return hookMatcherMatchesTool(matcher, toolName);
}

function handlerCommandText(handler: Record<string, unknown>): string {
  return [
    typeof handler.command === "string" ? handler.command : "",
    ...(Array.isArray(handler.args)
      ? handler.args.filter((arg): arg is string => typeof arg === "string")
      : []),
  ]
    .filter(Boolean)
    .join(" ");
}

function matcherMentionsTool(matcher: unknown, toolName: string): boolean {
  if (typeof matcher !== "string") {
    return false;
  }
  return hookMatcherMatchesTool(matcher, toolName);
}

function workspaceVariable(name: string): string {
  return ["$", "{", name, "}"].join("");
}

function withoutCodexProjectDir(env: NodeJS.ProcessEnv = process.env): NodeJS.ProcessEnv {
  return Object.fromEntries(Object.entries(env).filter(([name]) => name !== "CODEX_PROJECT_DIR"));
}

function codexSessionStartPayload(source: string, sessionId: string): Record<string, unknown> {
  return {
    cwd: process.cwd(),
    hook_event_name: "SessionStart",
    model: "test-model",
    permission_mode: "default",
    session_id: sessionId,
    source,
    transcript_path: null,
  };
}

function codexWindowsProbePayload(
  eventName: string,
  cwd: string,
  sessionId: string
): Record<string, unknown> {
  const common = {
    cwd,
    hook_event_name: eventName,
    model: "test-model",
    permission_mode: "default",
    session_id: sessionId,
    transcript_path: null,
  };
  if (eventName === "SessionStart") {
    return { ...common, source: "startup" };
  }
  if (eventName === "UserPromptSubmit") {
    return { ...common, prompt: "Native Windows hook entrypoint probe." };
  }
  if (eventName === "PreToolUse" || eventName === "PostToolUse") {
    return {
      ...common,
      tool_input: {
        command: "*** Begin Patch\n*** Add File: windows-hook-probe.txt\n+probe\n*** End Patch\n",
      },
      tool_name: "apply_patch",
      ...(eventName === "PostToolUse" ? { tool_response: { exit_code: 0 } } : {}),
    };
  }
  if (eventName === "SubagentStart") {
    return { ...common, agent_id: "windows-probe-agent", agent_type: "worker" };
  }
  if (eventName === "SubagentStop") {
    return {
      ...common,
      agent_id: "windows-probe-agent",
      last_assistant_message: "Windows hook probe finished.",
      stop_hook_active: false,
    };
  }
  if (eventName === "Stop") {
    return {
      ...common,
      last_assistant_message: "Windows hook probe response.",
      stop_hook_active: false,
    };
  }
  return { ...common, reason: "other" };
}

async function sessionState(stateDir: string): Promise<Record<string, unknown>> {
  const files = (await readdir(stateDir)).filter((file) => file.endsWith(".json"));
  expect(files).toHaveLength(1);
  return jsonRecord(await readFile(join(stateDir, files[0]), "utf8"));
}

async function sourceLauncherFailureFixture(): Promise<{
  env: NodeJS.ProcessEnv;
  script: string;
}> {
  const root = await mkdtemp(join(tmpdir(), "supa-source-hook-launcher-"));
  const script = join(root, ".claude", "hooks", "supaschema-source-hook.mjs");
  const hookOutput = join(root, "scripts", "agent-hooks", "hook-output.mjs");
  const fakeNpm = join(root, "fake-npm.mjs");
  await Promise.all([
    mkdir(dirname(script), { recursive: true }),
    mkdir(dirname(hookOutput), { recursive: true }),
  ]);
  await Promise.all([
    copyFile(resolve(".claude/hooks/supaschema-source-hook.mjs"), script),
    copyFile(resolve("scripts/agent-hooks/hook-output.mjs"), hookOutput),
    writeFile(fakeNpm, "process.exitCode = 17;\n"),
  ]);
  const inheritedEnv = Object.fromEntries(
    Object.entries(process.env).filter(([name]) => name.toLowerCase() !== "npm_execpath")
  );
  return {
    env: {
      ...withoutCodexProjectDir(inheritedEnv),
      npm_execpath: fakeNpm,
    },
    script,
  };
}

describe.skipIf(!hasCodexSessionStartHook)("Codex SessionStart input contract", () => {
  const script = ".codex/hooks/context-session-start.mjs";

  it("accepts every upstream source and applies the expected context-epoch transition", {
    timeout: 15_000,
  }, async () => {
    const stateDir = await mkdtemp(join(tmpdir(), "supa-session-start-state-"));
    const env = { ...withoutCodexProjectDir(), STATE_DIR: stateDir };
    const transitions: [string, number][] = [
      ["startup", 0],
      ["resume", 1],
      ["compact", 2],
      ["clear", 0],
    ];

    for (const [source, expectedEpoch] of transitions) {
      const payload = {
        ...codexSessionStartPayload(source, "session-start-contract"),
        ...(source === "startup" ? { future_field: "accepted" } : {}),
      };
      const result = await runHook(script, payload, { env });

      expect(result.code, source).toBe(0);
      expect(result.stderr, source).toBe("");
      expect(hookAdditionalContext(result.stdout), source).toContain("Agent hook layer active");
      expect((await sessionState(stateDir)).contextEpoch, source).toBe(expectedEpoch);
    }
  });

  it("returns structured diagnostics and writes no state for invalid input", async () => {
    const valid = codexSessionStartPayload("startup", "invalid-session-start");
    const missingSession = { ...valid, session_id: undefined };
    const missingModel = { ...valid, model: undefined };
    const cases: [string, string][] = [
      ["empty", ""],
      ["malformed JSON", "{"],
      ["array", "[]"],
      ["scalar", "42"],
      ["missing session_id", JSON.stringify(missingSession)],
      ["missing model", JSON.stringify(missingModel)],
      ["mismatched event", JSON.stringify({ ...valid, hook_event_name: "UserPromptSubmit" })],
      ["invalid source", JSON.stringify({ ...valid, source: "other" })],
      ["Claude-only source", JSON.stringify({ ...valid, source: "fork" })],
      ["invalid permission mode", JSON.stringify({ ...valid, permission_mode: "unsupported" })],
      ["Claude-only permission mode", JSON.stringify({ ...valid, permission_mode: "auto" })],
    ];

    for (const [name, stdin] of cases) {
      const stateDir = await mkdtemp(join(tmpdir(), "supa-invalid-session-start-"));
      const result = await runHook(
        script,
        {},
        {
          env: { ...withoutCodexProjectDir(), STATE_DIR: stateDir },
          stdin,
        }
      );
      const output = hookOutput(result.stdout);

      expect(result.code, name).toBe(0);
      expect(result.stderr, name).toBe("");
      expect(output.systemMessage, name).toContain("Agent hook failed closed.");
      expect(output.systemMessage, name).toContain("runtime=codex");
      expect(output.systemMessage, name).toContain("event=SessionStart");
      expect(output.systemMessage, name).toContain("context-session-start.mjs");
      expect(output.systemMessage, name).toContain("check=hookInput");
      expect(output.systemMessage, name).toContain("source=");
      expect(output.systemMessage, name).toContain("remediation=");
      expect(output.systemMessage, name).not.toContain("stack=");
      expect(await readdir(stateDir), name).toEqual([]);
    }
  });
});

describe.skipIf(!hasClaudeSessionStartHook)("Claude SessionStart input contract", () => {
  it("accepts the upstream fork source, auto mode, optional model, and future fields", async () => {
    const stateDir = await mkdtemp(join(tmpdir(), "supa-claude-session-start-"));
    const env = {
      ...withoutCodexProjectDir(),
      CLAUDE_PROJECT_DIR: process.cwd(),
      STATE_DIR: stateDir,
    };
    const result = await runHook(
      ".claude/hooks/context-session-start.mjs",
      {
        cwd: process.cwd(),
        future_field: "accepted",
        hook_event_name: "SessionStart",
        permission_mode: "auto",
        session_id: "claude-fork-contract",
        source: "fork",
        transcript_path: null,
      },
      { env }
    );

    expect(result.code).toBe(0);
    expect(result.stderr).toBe("");
    expect(hookAdditionalContext(result.stdout)).toContain("Agent hook layer active");
    expect((await sessionState(stateDir)).contextEpoch).toBe(0);
  });

  it("accepts the documented startup payload that omits permission_mode", async () => {
    const stateDir = await mkdtemp(join(tmpdir(), "supa-claude-session-start-startup-"));
    const result = await runHook(
      ".claude/hooks/context-session-start.mjs",
      {
        cwd: process.cwd(),
        hook_event_name: "SessionStart",
        model: "claude-opus-5",
        session_id: "claude-startup-contract",
        source: "startup",
        transcript_path: null,
      },
      {
        env: {
          ...withoutCodexProjectDir(),
          CLAUDE_PROJECT_DIR: process.cwd(),
          STATE_DIR: stateDir,
        },
      }
    );

    expect(result.code).toBe(0);
    expect(result.stderr).toBe("");
    expect(result.stdout).not.toContain("Agent hook failed closed.");
    expect(hookAdditionalContext(result.stdout)).toContain("Agent hook layer active");
  });

  it("still rejects a permission_mode value outside the documented Claude set", async () => {
    const stateDir = await mkdtemp(join(tmpdir(), "supa-claude-session-start-invalid-"));
    const result = await runHook(
      ".claude/hooks/context-session-start.mjs",
      {
        cwd: process.cwd(),
        hook_event_name: "SessionStart",
        permission_mode: "unsupported",
        session_id: "claude-invalid-mode-contract",
        source: "startup",
        transcript_path: null,
      },
      {
        env: {
          ...withoutCodexProjectDir(),
          CLAUDE_PROJECT_DIR: process.cwd(),
          STATE_DIR: stateDir,
        },
      }
    );

    expect(result.code).toBe(0);
    expect(hookOutput(result.stdout).systemMessage).toContain("Agent hook failed closed.");
    expect(await readdir(stateDir)).toEqual([]);
  });
});

describe.skipIf(!hasClaudePostToolUseFailureHook)(
  "Claude PostToolUseFailure input contract",
  () => {
    it("records a failed verification command without requiring a synthetic tool response", async () => {
      const stateDir = await mkdtemp(join(tmpdir(), "supa-claude-tool-failure-"));
      const result = await runHook(
        ".claude/hooks/context-post-tool-use-failure.mjs",
        {
          cwd: process.cwd(),
          hook_event_name: "PostToolUseFailure",
          session_id: "claude-tool-failure",
          tool_input: { command: "npm run guard:agent" },
          tool_name: "Bash",
          transcript_path: null,
        },
        { env: { ...process.env, STATE_DIR: stateDir } }
      );

      expect(result.code).toBe(0);
      expect(result.stderr).toBe("");
      expect(await readFile(join(stateDir, (await readdir(stateDir))[0]), "utf8")).toContain(
        '"kind": "failed-command"'
      );
    });
  }
);

describe("source hook launcher diagnostics", () => {
  it.each([
    {
      args: ["hook", "generated-artifact-edit", "--runtime", "codex"],
      eventName: "PreToolUse",
    },
    {
      args: ["hook", "schema-write", "--runtime", "codex"],
      eventName: "PostToolUse",
    },
  ])("fails closed with event-correct output for $eventName bootstrap errors", async (testCase) => {
    const fixture = await sourceLauncherFailureFixture();
    const result = await runHook(
      fixture.script,
      {},
      {
        args: testCase.args,
        env: fixture.env,
      }
    );
    const output = hookOutput(result.stdout);
    const message =
      testCase.eventName === "PreToolUse"
        ? output.hookSpecificOutput?.permissionDecisionReason
        : output.reason;

    expect(result.code).toBe(0);
    expect(result.stderr).toBe("");
    expect(message).toContain("Agent hook failed closed.");
    expect(message).toContain("runtime=codex");
    expect(message).toContain(`event=${testCase.eventName}`);
    expect(message).toContain("hook=");
    expect(message).toContain("check=sourceHookLauncher");
    expect(message).toContain("source=");
    expect(message).toContain("failed with status 17");
    expect(message).toContain("remediation=");
    expect(message).not.toContain("stack=");
  });
});

describe("agent hook configuration", () => {
  it.skipIf(!hasClaudeSettings)(
    "registers Claude hooks without retired wrapper scripts",
    async () => {
      const settings = jsonRecord(await readFile(".claude/settings.json", "utf8"));
      const text = JSON.stringify(settings);
      const handlers = hookHandlers(settings);

      for (const handler of handlers) {
        expect(stringValue(handler.statusMessage)?.trim().length).toBeGreaterThan(0);
      }
      expect(text).not.toContain(['node "', "$CLAUDE_PROJECT_DIR", '"'].join(""));
      expect(text).not.toContain(`node "${workspaceVariable("CLAUDE_PROJECT_DIR")}`);
      for (const script of [
        "context-session-start.mjs",
        "context-user-prompt-submit.mjs",
        "context-pre-tool-use.mjs",
        "context-post-tool-use.mjs",
        "context-post-tool-use-failure.mjs",
        "context-subagent-start.mjs",
        "context-task-completed.mjs",
        "context-worktree-create.mjs",
        "context-session-end.mjs",
        "sync-llm-on-claude-surface-change.mjs",
      ]) {
        expect(handlers).toContainEqual(
          expect.objectContaining({
            args: [`${workspaceVariable("CLAUDE_PROJECT_DIR")}/.claude/hooks/${script}`],
            command: "node",
            type: "command",
          })
        );
      }
      const sourceClaudeBashCommands = claudePreToolUseCommandsFor(settings, "Bash");
      expect(sourceClaudeBashCommands).toEqual([
        [
          "node",
          `${workspaceVariable("CLAUDE_PROJECT_DIR")}/.claude/hooks/context-pre-tool-use.mjs`,
        ].join(" "),
        [
          "node",
          `${workspaceVariable("CLAUDE_PROJECT_DIR")}/.claude/hooks/supaschema-source-hook.mjs`,
          "hook",
          "generated-artifact-edit",
          "--runtime",
          "claude",
        ].join(" "),
      ]);
      expect(
        hookEntries(settings, "PreToolUse").find((entry) =>
          JSON.stringify(entry).includes("context-pre-tool-use.mjs")
        )
      ).toMatchObject({ matcher: ".*" });
      expect(text).not.toContain("block-generated-migration-edits.mjs");
      expect(text).not.toContain("auto-diff-on-schema-change.mjs");
      expect(text).not.toContain(".claude/hooks/guards/bash-policy-checks.mjs");
      expect(handlers).toContainEqual(
        expect.objectContaining({
          args: [
            `${workspaceVariable("CLAUDE_PROJECT_DIR")}/.claude/hooks/supaschema-source-hook.mjs`,
            "hook",
            "generated-artifact-edit",
            "--runtime",
            "claude",
          ],
          command: "node",
          type: "command",
        })
      );
      expect(handlers).toContainEqual(
        expect.objectContaining({
          args: [
            `${workspaceVariable("CLAUDE_PROJECT_DIR")}/.claude/hooks/supaschema-source-hook.mjs`,
            "hook",
            "schema-write",
          ],
          command: "node",
          type: "command",
        })
      );
      const postToolUseText = JSON.stringify(hookEntries(settings, "PostToolUse"));
      const postToolUseFailureText = JSON.stringify(hookEntries(settings, "PostToolUseFailure"));
      expect(hookEntries(settings, "PostToolUse").map((entry) => entry.matcher)).toEqual([
        "Agent|Bash|Edit|MultiEdit|NotebookEdit|Read|Skill|Task|Write|apply_patch",
        "Bash|Write|Edit|MultiEdit|apply_patch",
        "Bash|Write|Edit|MultiEdit|apply_patch",
      ]);
      expect(postToolUseText).toContain("sync-llm-on-claude-surface-change.mjs");
      expect(postToolUseFailureText).toContain("context-post-tool-use-failure.mjs");
      expect(postToolUseFailureText).toContain("sync-llm-on-claude-surface-change.mjs");
      expect(hookEntries(settings, "PermissionDenied")).toEqual([]);
      expect(hookEntries(settings, "PostToolBatch")).toEqual([]);
      expect(JSON.stringify(hookEntries(settings, "Stop"))).toContain("context-stop.mjs");
      expect(JSON.stringify(hookEntries(settings, "SubagentStop"))).toContain(
        "context-subagent-stop.mjs"
      );
      expect(JSON.stringify(hookEntries(settings, "WorktreeCreate"))).toContain(
        "context-worktree-create.mjs"
      );
    }
  );

  it("uses Codex matchers only on supported tool hook events", async () => {
    const config = jsonRecord(await readFile(".codex/hooks.json", "utf8"));

    for (const eventName of ["PreToolUse", "PostToolUse"]) {
      const entries = hookEntries(config, eventName);
      expect(entries.length).toBeGreaterThan(0);
      for (const entry of entries) {
        expect(entry.matcher, `${eventName} entry missing matcher`).toEqual(expect.any(String));
      }
    }
    const postToolUseText = JSON.stringify(hookEntries(config, "PostToolUse"));
    const preToolUseText = JSON.stringify(hookEntries(config, "PreToolUse"));
    expect(
      hookEntries(config, "PostToolUse").find((entry) =>
        JSON.stringify(entry).includes("context-post-tool-use.mjs")
      )
    ).toMatchObject({
      matcher: "Bash|apply_patch|mcp__.*",
    });
    expect(postToolUseText).toContain("sync-llm-on-claude-surface-change.mjs");
    expect(JSON.stringify(config)).toContain("context-user-prompt-submit.mjs");
    expect(JSON.stringify(config)).toContain("context-pre-tool-use.mjs");
    expect(JSON.stringify(config)).toContain("context-post-tool-use.mjs");
    expect(JSON.stringify(config)).toContain("context-session-end.mjs");
    expect(JSON.stringify(config)).toContain("context-stop.mjs");
    expect(JSON.stringify(config)).toContain("context-subagent-stop.mjs");
    expect(JSON.stringify(config)).not.toContain("scripts/agent-hooks");
    expect(JSON.stringify(config)).not.toContain("general-guard.mjs");
    expect(JSON.stringify(config)).not.toContain("block-generated-migration-edits.mjs");
    expect(JSON.stringify(config)).not.toContain("auto-diff-on-schema-change.mjs");
    expect(JSON.stringify(config)).toContain("supaschema-source-hook.mjs");
    expect(JSON.stringify(config)).not.toContain("/bin/");
    expect(
      hookEntries(config, "PreToolUse").find((entry) =>
        JSON.stringify(entry).includes("context-pre-tool-use.mjs")
      )
    ).toMatchObject({ matcher: ".*" });
    expect(preToolUseText).toContain("apply_patch");
    expect(preToolUseText).not.toContain("exec_command");
    expect(preToolUseText).not.toContain("functions.");
    expect(postToolUseText).not.toContain("exec_command");
    expect(postToolUseText).not.toContain("functions.");
    expect(JSON.stringify(config)).toContain("hook generated-artifact-edit");
    expect(JSON.stringify(config)).toContain("hook schema-write");
    expect(JSON.stringify(config)).not.toContain("npm exec -- supaschema");
    expect(JSON.stringify(config)).not.toContain("pnpm exec supaschema");
    expect(JSON.stringify(config)).not.toContain("npx --no-install supaschema");
    expect(codexPreToolUseCommandsFor(config, "Bash")).toEqual([
      `node "${codexGitRoot}/.codex/hooks/context-pre-tool-use.mjs"`,
      `node "${codexGitRoot}/.codex/hooks/supaschema-source-hook.mjs" hook generated-artifact-edit --runtime codex`,
    ]);
    expect(codexPreToolUseCommandsFor(config, "apply_patch")).toEqual(
      expect.arrayContaining([
        `node "${codexGitRoot}/.codex/hooks/supaschema-source-hook.mjs" hook generated-artifact-edit --runtime codex`,
      ])
    );
    expect(hookEntries(config, "Stop")).toHaveLength(1);
    expect(hookEntries(config, "SubagentStop")).toHaveLength(1);
    expect(hookEntries(config, "SessionEnd")).toHaveLength(1);
    expect(hookEntries(config, "PermissionDenied")).toEqual([]);
    expect(hookEntries(config, "PostToolUseFailure")).toEqual([]);
    expect(hookEntries(config, "TaskCompleted")).toEqual([]);
    expect(hookEntries(config, "WorktreeCreate")).toEqual([]);
    expect(JSON.stringify(config)).not.toContain("CODEX_PROJECT_DIR");
    for (const handler of hookHandlers(config)) {
      expect(stringValue(handler.statusMessage)?.trim().length).toBeGreaterThan(0);
      expect(handler.commandWindows).toEqual(
        expect.stringContaining("git rev-parse --show-toplevel")
      );
      expect(handler.commandWindows).toEqual(expect.stringContaining('do @node "'));
    }
  });

  it("runs generated Codex lifecycle commands from a nested directory without an env root", async () => {
    const config = jsonRecord(await readFile(".codex/hooks.json", "utf8"));
    const commandFor = (eventName: string): string => {
      const commandKey = process.platform === "win32" ? "commandWindows" : "command";
      const command = hookHandlers(hookEntries(config, eventName))[0]?.[commandKey];
      expect(command, eventName).toEqual(expect.any(String));
      return String(command);
    };
    const stateDir = await mkdtemp(join(tmpdir(), "supa-codex-nested-lifecycle-"));
    const env = { ...withoutCodexProjectDir(), STATE_DIR: stateDir };
    const cwd = resolve("scripts/agent-hooks");
    const sessionId = "codex-nested-lifecycle";

    const start = await runHookCommand(
      commandFor("SessionStart"),
      codexSessionStartPayload("startup", sessionId),
      { cwd, env }
    );

    expect(start.code).toBe(0);
    expect(start.stderr).toBe("");
    expect(hookAdditionalContext(start.stdout)).toContain("Agent hook layer active");
    expect(await readdir(stateDir)).toHaveLength(1);

    const end = await runHookCommand(
      commandFor("SessionEnd"),
      {
        cwd,
        hook_event_name: "SessionEnd",
        model: "test-model",
        permission_mode: "default",
        reason: "other",
        session_id: sessionId,
        transcript_path: null,
      },
      { cwd, env }
    );

    expect(end.code).toBe(0);
    expect(end.stderr).toBe("");
    expect(end.stdout).toBe("");
    expect(await readdir(stateDir)).toEqual([]);
  });

  it.skipIf(process.platform !== "win32")(
    "runs every generated commandWindows handler through native cmd from a nested directory",
    async () => {
      const config = jsonRecord(await readFile(".codex/hooks.json", "utf8"));
      const stateDir = await mkdtemp(join(tmpdir(), "supa-codex-windows-state-"));
      const payloadCwd = await mkdtemp(join(tmpdir(), "supa-codex-windows-project-"));
      const env = { ...process.env, STATE_DIR: stateDir };
      env.CLAUDE_PROJECT_DIR = undefined;
      env.CODEX_PROJECT_DIR = undefined;
      env.npm_execpath = undefined;
      const commandCwd = resolve("scripts/agent-hooks");
      const sessionId = "codex-windows-hook-surface";
      const orderedEvents = [
        "SessionStart",
        "UserPromptSubmit",
        "PreToolUse",
        "PostToolUse",
        "SubagentStart",
        "SubagentStop",
        "Stop",
        "SessionEnd",
      ];
      let executed = 0;

      for (const eventName of orderedEvents) {
        const payload = codexWindowsProbePayload(eventName, payloadCwd, sessionId);
        for (const handler of hookHandlers(hookEntries(config, eventName))) {
          const command = stringValue(handler.commandWindows);
          expect(command, eventName).toEqual(expect.any(String));
          const result = await runHookCommand(String(command), payload, {
            cwd: commandCwd,
            env,
          });

          expect(result.code, `${eventName}: ${command}`).toBe(0);
          expect(result.stderr, `${eventName}: ${command}`).toBe("");
          if (result.stdout.trim()) {
            expect(() => JSON.parse(result.stdout), `${eventName}: ${command}`).not.toThrow();
          }
          executed += 1;
        }
      }

      expect(executed).toBe(12);
      expect(await readdir(stateDir)).toEqual([]);
    },
    60_000
  );
});

describe("general Bash blocker policy", () => {
  const claudeScript = ".claude/hooks/guards/bash-policy-checks.mjs";
  const sourceClaudeScript = ".claude/hooks/context-pre-tool-use.mjs";
  const sourceCodexScript = ".codex/hooks/context-pre-tool-use.mjs";
  let bashPolicySessionIndex = 0;
  const nextBashPolicySessionId = (): string => {
    bashPolicySessionIndex += 1;
    return `bash-policy-${bashPolicySessionIndex}`;
  };
  const preToolBash = (command: string) => ({
    hook_event_name: "PreToolUse",
    session_id: nextBashPolicySessionId(),
    tool_input: { command },
    tool_name: "Bash",
  });
  const codexDenial = (stdout: string): string | undefined => {
    const parsed = hookOutput(stdout);
    return parsed.hookSpecificOutput?.permissionDecision === "deny"
      ? parsed.hookSpecificOutput.permissionDecisionReason
      : undefined;
  };

  it("matches Anilize destructive Git and rm behavior", async () => {
    for (const command of [
      "git checkout main",
      "git restore --source=HEAD~1 src/index.ts",
      "rm -rf tmp",
      "rm -fr tmp",
    ]) {
      const result = await runHook(claudeScript, preToolBash(command));
      expect(result.code, command).toBe(2);
    }

    for (const command of ["rm -r tmp", "rm -rg tmp"]) {
      const result = await runHook(claudeScript, preToolBash(command));
      expect(result.code, command).toBe(0);
    }
  });

  it.each([
    "git switch -c feature/demo HEAD",
    "git switch -c main origin/main",
    "git switch -c HEAD origin/main",
    "git switch -c origin/main origin/main",
    "git switch -c refs/heads/feature/demo origin/main",
    "git switch --track upstream/feature/demo",
    "git switch --track origin/main",
    "git switch -C feature/demo origin/main",
    "git switch --discard-changes feature/demo",
    "git switch --merge feature/demo",
    "git switch -m feature/demo",
    "git switch -f feature/demo",
    "git branch feature/demo",
    "git branch --show-current",
    "git branch -D main",
    "git branch -D feature/one feature/two",
    "git worktree add ../demo HEAD",
    "git worktree remove ../demo",
    "git stash",
    "git clean -fd",
    "git clean -xdf",
    "git merge --squash feature/demo",
    "git reset --hard",
    'git commit --no-verify -m "skip"',
    "git push origin main",
    "git push origin HEAD:main",
    "git push origin HEAD:refs/heads/main",
    "git push origin HEAD",
    "git push origin +main",
    "git push origin +refs/heads/main",
    "git push origin +HEAD:main",
    "git push",
    "git push origin",
    "git push --force origin",
    "git push -o ci.skip origin",
    "git push --push-option ci.skip origin",
    "git push --recurse-submodules check origin",
    "git push --recurse-submodules origin",
    "git push --repo origin",
    "git push --force origin main",
    "git push --force origin codex/feature",
    "git push -f origin codex/feature",
    "git push -uf origin codex/feature",
    "git push -fu origin codex/feature",
    "git push -qf origin codex/feature",
    "git push --force-with-lease origin codex/feature",
    "git push --force-if-includes origin codex/feature",
    "git push origin +codex/feature",
    "git push --no-verify origin codex/feature",
    "git push | tail -20",
    "git -C . branch tmp",
    "git -C . clean -fd",
    "git -C . stash",
    "git --git-dir .git branch tmp",
    "git --work-tree . branch tmp",
    "git -c user.email=a@b.c commit --no-verify -m skip",
    "command git checkout main",
    "env git stash",
  ])("blocks stateful git shortcut: %s", async (command) => {
    const result = await runHook(claudeScript, preToolBash(command));
    expect(result.code, command).toBe(2);
  });

  it.each([
    "git switch -c feature/demo origin/main",
    "git switch --track origin/feature/demo",
    "command git switch -c feature/demo origin/main",
    "env git switch --track origin/feature/demo",
  ])("allows transactional topic-branch switch: %s", async (command) => {
    const result = await runHook(claudeScript, preToolBash(command));
    expect(result.code, command).toBe(0);
  });

  it("allows the verified post-merge switch to main", async () => {
    const result = await runHook(claudeScript, preToolBash("git switch main"));
    expect(result.code).toBe(0);
  });

  it.each([
    "git branch -d feature/demo",
    "git branch -D feature/demo",
    "git branch --delete feature/demo",
    "command git branch -D feature/demo",
  ])("allows approved merged topic deletion shape: %s", async (command) => {
    const result = await runHook(claudeScript, preToolBash(command));
    expect(result.code, command).toBe(0);
  });

  it.each([
    "git status --short",
    "git rev-parse --abbrev-ref HEAD",
    "git worktree list --porcelain -z",
    "/usr/bin/git worktree list --porcelain -z",
    "git -c alias.wt=worktree status --short",
    "git -c user.email=a@b.c status --short",
    "git -C . status --short",
    "git --no-pager rev-parse --abbrev-ref HEAD",
    "echo $(command -v git) worktree add ../demo HEAD",
    "git help worktree",
    "man git-worktree",
    "git worktree list --porcelain -z | head",
  ])("allows stateless git diagnostic: %s", async (command) => {
    const result = await runHook(claudeScript, preToolBash(command));
    expect(result.code, command).toBe(0);
  });

  it.each([
    "git worktree list",
    "git worktree list --porcelain",
    "git worktree list --porcelain -z --verbose",
    "git -C . worktree list --porcelain -z",
    "git --no-pager worktree list --porcelain -z",
  ])("blocks noncanonical worktree inventory: %s", async (command) => {
    const result = await runHook(claudeScript, preToolBash(command));
    expect(result.code, command).toBe(2);
  });

  it.each([
    "git worktree lock ../demo",
    "git worktree move ../demo ../moved",
    "git worktree prune",
    "git worktree repair ../demo",
    "git worktree unlock ../demo",
    "/usr/bin/git worktree add ../demo HEAD",
    "command /opt/homebrew/bin/git worktree remove ../demo",
    '"C:/Program Files/Git/cmd/git.exe" worktree add ../demo HEAD',
    "git-worktree add ../demo HEAD",
    "/usr/libexec/git-core/git-worktree remove ../demo",
    "git -c alias.wt=worktree wt add ../demo HEAD",
    "git --config-env=alias.wt=GIT_ALIAS wt add ../demo HEAD",
    "GIT_CONFIG_COUNT=1 GIT_CONFIG_KEY_0=alias.wt GIT_CONFIG_VALUE_0=worktree git wt add ../demo HEAD",
    "git config alias.wt worktree",
    "$(command -v git) worktree add ../demo HEAD",
    '"$(command -v git)" worktree remove ../demo',
    "$GIT worktree add ../demo HEAD",
    "`command -v git` worktree add ../demo HEAD",
    'env -S "git worktree add ../demo HEAD"',
    'env --split-string="git worktree add ../demo HEAD"',
    "sudo git worktree add ../demo HEAD",
    "/bin/bash -lc 'git worktree add ../demo HEAD'",
    Array.from({ length: 4 }).reduce(
      (nested) => `bash -lc ${JSON.stringify(nested)}`,
      "git worktree add ../demo HEAD"
    ),
  ])("blocks worktree policy bypass: %s", async (command) => {
    const result = await runHook(claudeScript, preToolBash(command));
    expect(result.code, command).toBe(2);
  });

  it.each([
    "git push -u origin codex/feature",
    "git push origin HEAD:codex/feature",
    "git push --repo origin codex/feature",
    "git push -of origin codex/feature",
    "git push --recurse-submodules check origin codex/feature",
    "git push --recurse-submodules origin codex/feature",
    "git push --recurse-submodules=on-demand origin codex/feature",
    "git push --dry-run",
    "git push --dry-run origin",
    "git push -h",
    "git push --help",
  ])("allows topic push shape: %s", async (command) => {
    const result = await runHook(claudeScript, preToolBash(command));
    expect(result.code, command).toBe(0);
  });

  it.each([
    "gh pr merge --squash 53",
    "gh pr merge 53 --squash",
    "bash -lc 'gh pr merge 53 --squash'",
    "bash -lc -- 'gh pr merge 53 --squash'",
    "env bash -lc 'gh pr merge 53 --squash'",
    "command gh pr merge 53 --squash",
    "env gh pr merge 53 --squash",
    "gh pr merge --merge 53",
    "gh pr merge 53 --merge",
    "gh pr merge --rebase 53",
    "gh pr merge 53 --rebase",
    "gh pr merge --admin 53 --squash --delete-branch",
    "gh pr merge 53 --admin --squash --delete-branch",
    "gh pr merge --disable-auto 53 --squash --delete-branch",
    "gh pr merge 53 --disable-auto --squash --delete-branch",
  ])("blocks non-policy GitHub PR merge command: %s", async (command) => {
    const result = await runHook(claudeScript, preToolBash(command));
    expect(result.code, command).toBe(2);
  });

  it.each([
    "gh pr merge 53 --squash --delete-branch",
    "bash -lc 'gh pr merge 53 --squash --delete-branch'",
    "command gh pr merge 53 --squash --delete-branch",
    "env bash -lc 'gh pr merge 53 --squash --delete-branch'",
    "gh pr merge --help",
  ])("allows policy GitHub PR merge command: %s", async (command) => {
    const result = await runHook(claudeScript, preToolBash(command));
    expect(result.code, command).toBe(0);
  });

  it("blocks secret argv, env file reads, and raw SQL DDL through Bash", async () => {
    for (const command of [
      "psql postgres://user:verylongpassword123@example.com/db -c 'select 1'",
      "cat .env.local",
      "psql -c 'CREATE TABLE demo(id int)'",
      "supabase db execute --sql 'DROP TABLE demo'",
    ]) {
      const result = await runHook(claudeScript, preToolBash(command));
      expect(result.code, command).toBe(2);
    }

    for (const command of [
      "cat .env.example",
      "psql -c 'select * from information_schema.tables'",
    ]) {
      const result = await runHook(claudeScript, preToolBash(command));
      expect(result.code, command).toBe(0);
    }
  });

  it("blocks unsafe Bash through the source Codex context hook path", async () => {
    for (const command of [
      "rm -rf tmp",
      "/usr/bin/git worktree add ../demo HEAD",
      "git -c alias.wt=worktree wt add ../demo HEAD",
      "$(command -v git) worktree add ../demo HEAD",
    ]) {
      const blocked = await runHook(sourceCodexScript, preToolBash(command));
      expect(blocked.code, command).toBe(0);
      expect(codexDenial(blocked.stdout), command).toContain("BLOCKED:");
    }
  });

  it("blocks unsafe Bash through the source Claude context hook path", async () => {
    for (const command of [
      "rm -rf tmp",
      "/usr/bin/git worktree add ../demo HEAD",
      "git -c alias.wt=worktree wt add ../demo HEAD",
      "$(command -v git) worktree add ../demo HEAD",
    ]) {
      const blocked = await runHook(sourceClaudeScript, preToolBash(command));
      expect(blocked.code, command).toBe(0);
      expect(codexDenial(blocked.stdout), command).toContain("BLOCKED:");
    }
  });

  it.each([
    "git submodule add https://example.com/lib.git vendor/lib",
    "git submodule update --init",
    "git submodule update --init --recursive",
    "git submodule update --checkout",
    "git submodule sync",
    "git submodule sync --recursive",
    "git submodule absorbgitdirs",
    "git submodule set-branch -b main vendor/lib",
  ])(
    "blocks submodule checkout-creating or mutating form through the source Codex context hook path: %s",
    async (command) => {
      const blocked = await runHook(sourceCodexScript, preToolBash(command));
      expect(blocked.code, command).toBe(0);
      expect(codexDenial(blocked.stdout), command).toContain("BLOCKED:");
    }
  );

  it.each([
    "git submodule add https://example.com/lib.git vendor/lib",
    "git submodule update --init",
    "git submodule update --init --recursive",
    "git submodule update --checkout",
    "git submodule sync",
    "git submodule sync --recursive",
    "git submodule absorbgitdirs",
    "git submodule set-branch -b main vendor/lib",
  ])(
    "blocks submodule checkout-creating or mutating form through the source Claude context hook path: %s",
    async (command) => {
      const blocked = await runHook(sourceClaudeScript, preToolBash(command));
      expect(blocked.code, command).toBe(0);
      expect(codexDenial(blocked.stdout), command).toContain("BLOCKED:");
    }
  );

  it.each(["git submodule status", "git submodule status --recursive"])(
    "allows read-only git submodule status through the source Codex context hook path: %s",
    async (command) => {
      const allowed = await runHook(sourceCodexScript, preToolBash(command));
      expect(allowed.code, command).toBe(0);
      expect(codexDenial(allowed.stdout), command).toBeUndefined();
    }
  );

  it.each(["git submodule status", "git submodule status --recursive"])(
    "allows read-only git submodule status through the source Claude context hook path: %s",
    async (command) => {
      const allowed = await runHook(sourceClaudeScript, preToolBash(command));
      expect(allowed.code, command).toBe(0);
      expect(codexDenial(allowed.stdout), command).toBeUndefined();
    }
  );

  it("known limitation A7: git newbranch is allowed because a git alias configured in ~/.gitconfig or .git/config outside the invoked command is invisible to this hook", async () => {
    const result = await runHook(
      claudeScript,
      preToolBash("git newbranch feature/demo origin/main")
    );
    expect(result.code).toBe(0);
  });
});

describe("llm surface sync hook", () => {
  it("runs sync:llm after direct edits to Claude-owned skill surfaces", async () => {
    const { claudeHook, env, log, project } = await syncHookProject();

    const result = await runHook(
      claudeHook,
      {
        cwd: project,
        hook_event_name: "PostToolUse",
        tool_input: { file_path: ".claude/skills/demo/SKILL.md" },
        tool_name: "Edit",
      },
      { cwd: project, env }
    );

    expect(result.code).toBe(0);
    expect(hookJson(result.stdout)).toMatchObject({
      hookSpecificOutput: expect.objectContaining({
        additionalContext: "SYNC_LLM_OK",
        hookEventName: "PostToolUse",
      }),
    });
    expect(await readFile(log, "utf8")).toBe("sync\n");
  }, 15_000);

  it("runs sync:llm after direct edits to generated Codex hook registration", async () => {
    const { claudeHook, env, log, project } = await syncHookProject();

    const result = await runHook(
      claudeHook,
      {
        cwd: project,
        hook_event_name: "PostToolUse",
        tool_input: { file_path: ".codex/hooks.json" },
        tool_name: "Edit",
      },
      { cwd: project, env }
    );

    expect(result.code).toBe(0);
    expect(hookJson(result.stdout)).toMatchObject({
      hookSpecificOutput: expect.objectContaining({
        additionalContext: "SYNC_LLM_OK",
        hookEventName: "PostToolUse",
      }),
    });
    expect(await readFile(log, "utf8")).toBe("sync\n");
  });

  it("syncs a canonical direct Claude surface edit", async () => {
    const { claudeHook, env, log, project } = await syncHookProject();
    await writeFile(join(project, ".claude/rules/supaschema.md"), "# changed\n");

    const result = await runHook(
      claudeHook,
      {
        cwd: project,
        hook_event_name: "PostToolUse",
        tool_input: { file_path: ".claude/rules/supaschema.md" },
        tool_name: "Edit",
      },
      { cwd: project, env }
    );

    expect(result.code).toBe(0);
    expect(hookJson(result.stdout)).toMatchObject({
      hookSpecificOutput: expect.objectContaining({
        additionalContext: "SYNC_LLM_OK",
        hookEventName: "PostToolUse",
      }),
    });
    expect(await readFile(log, "utf8")).toBe("sync\n");
  });

  it("resolves the Codex project root from its entrypoint when the tool cwd is nested", async () => {
    const { codexHook, env, log, project } = await syncHookProject();
    const nestedCwd = join(project, "packages/database");
    await mkdir(nestedCwd, { recursive: true });
    const runtimeEnv = withoutCodexProjectDir(env);

    const result = await runHook(
      codexHook,
      {
        cwd: nestedCwd,
        hook_event_name: "PostToolUse",
        tool_input: {
          command: [
            "*** Begin Patch",
            "*** Update File: ../../.claude/rules/supaschema.md",
            "*** End Patch",
            "",
          ].join("\n"),
        },
        tool_name: "apply_patch",
      },
      { cwd: nestedCwd, env: runtimeEnv }
    );

    expect(result.code).toBe(0);
    expect(hookJson(result.stdout)).toMatchObject({
      hookSpecificOutput: expect.objectContaining({
        additionalContext: "SYNC_LLM_OK",
        hookEventName: "PostToolUse",
      }),
    });
    expect(await readFile(log, "utf8")).toBe("sync\n");
  });

  it("no-ops outside the supaschema repo package", async () => {
    const { claudeHook, log, project } = await syncHookProject({ packageName: "consumer" });

    const result = await runHook(
      claudeHook,
      {
        cwd: project,
        hook_event_name: "PostToolUse",
        tool_input: { file_path: ".claude/hooks/example.mjs" },
        tool_name: "Write",
      },
      { cwd: project }
    );

    expect(result.code).toBe(0);
    await expect(readFile(log, "utf8")).rejects.toMatchObject({
      code: "ENOENT",
    });
    await expect(
      readFile(join(project, ".tmp", "sync-llm-on-claude-surface-change.json"), "utf8")
    ).rejects.toMatchObject({ code: "ENOENT" });
  });
});

describe("claude generated-artifact edit hook", () => {
  const script = "supaschema hook generated-artifact-edit --runtime claude";

  it("blocks edits to migrations carrying the lineage marker", async () => {
    const { generated } = await fixtures();
    const result = await runHook(script, {
      tool_input: { file_path: generated },
      tool_name: "Edit",
    });

    expect(result.code).toBe(2);
    expect(result.stderr).toContain("SUPA_GENERATED_ARTIFACT_EDIT");
  });

  it("blocks apply_patch updates to migrations carrying the lineage marker", async () => {
    const { generated } = await fixtures();
    const patch = `*** Begin Patch\n*** Update File: ${generated}\n@@\n-SET lock_timeout = '5s';\n+SET lock_timeout = '1s';\n*** End Patch`;
    const result = await runHook(script, {
      tool_input: { command: patch },
      tool_name: "apply_patch",
    });

    expect(result.code).toBe(2);
    expect(result.stderr).toContain("SUPA_GENERATED_ARTIFACT_EDIT");
  });

  it("allows deleting a stale generated migration", async () => {
    const { generated } = await fixtures();
    const patch = `*** Begin Patch\n*** Delete File: ${generated}\n*** End Patch`;
    const result = await runHook(script, {
      tool_input: { command: patch },
      tool_name: "apply_patch",
    });

    expect(result.code).toBe(0);
  });

  it("blocks writes and deletes to configured generated contracts", async () => {
    const { project, typesFile, zodFile } = await generatedContractFixture();
    const write = await runHook(
      script,
      {
        cwd: project,
        tool_input: { file_path: typesFile },
        tool_name: "Write",
      },
      { cwd: project }
    );
    const patch = `*** Begin Patch\n*** Delete File: ${zodFile}\n*** End Patch`;
    const deletion = await runHook(
      script,
      {
        cwd: project,
        tool_input: { command: patch },
        tool_name: "apply_patch",
      },
      { cwd: project }
    );

    expect(write.code).toBe(2);
    expect(write.stderr).toContain("generated TypeScript contract");
    expect(deletion.code).toBe(2);
    expect(deletion.stderr).toContain("generated Zod contract");
  });

  it("blocks bounded Bash writer forms targeting generated contracts but allows reads", {
    timeout: 20_000,
  }, async () => {
    const { project, typesFile } = await generatedContractFixture();
    const writeCommands = [
      `echo generated > ${typesFile}`,
      `echo generated >| ${typesFile}`,
      `echo generated > ${typesFile.replaceAll("/", "\\")}`,
      `TARGET=${typesFile}; echo generated > "$TARGET"`,
      `export TARGET=${typesFile}; echo generated > "$TARGET"`,
      `cp /tmp/source ${typesFile} > /tmp/cp.log`,
      `cp -t ${dirname(typesFile)} /tmp/source`,
      `mv --target-directory=${dirname(typesFile)} /tmp/source`,
      `prettier --write=${typesFile}`,
    ];
    for (const command of writeCommands) {
      const write = await runHook(
        script,
        {
          cwd: project,
          tool_input: { command },
          tool_name: "Bash",
        },
        { cwd: project }
      );

      expect(write.code, command).toBe(2);
      expect(write.stderr, command).toContain("SUPA_GENERATED_ARTIFACT_EDIT");
    }
    const read = await runHook(
      script,
      {
        cwd: project,
        tool_input: { command: `cat ${typesFile}` },
        tool_name: "Bash",
      },
      { cwd: project }
    );

    expect(read.code).toBe(0);
  });

  it("blocks shell deletion while preserving the reviewed delete-only patch lane", async () => {
    const { generated } = await fixtures();
    const shellDelete = await runHook(script, {
      tool_input: { command: `rm ${generated}` },
      tool_name: "Bash",
    });
    const moveAway = await runHook(script, {
      tool_input: { command: `mv ${generated} /tmp/backup.sql` },
      tool_name: "Bash",
    });
    const patchDelete = await runHook(script, {
      tool_input: {
        command: `*** Begin Patch\n*** Delete File: ${generated}\n*** End Patch`,
      },
      tool_name: "apply_patch",
    });

    expect(shellDelete.code).toBe(2);
    expect(shellDelete.stderr).toContain("SUPA_GENERATED_ARTIFACT_EDIT");
    expect(moveAway.code).toBe(2);
    expect(moveAway.stderr).toContain("SUPA_GENERATED_ARTIFACT_EDIT");
    expect(patchDelete.code).toBe(0);
  });

  it("allows hand-authored migrations, new files, and non-sql edits", {
    timeout: 20_000,
  }, async () => {
    const { handAuthored } = await fixtures();
    for (const payload of [
      { tool_input: { file_path: handAuthored }, tool_name: "Write" },
      {
        tool_input: { file_path: `${handAuthored}.missing.sql` },
        tool_name: "Write",
      },
      { tool_input: { file_path: "src/render/migration.ts" }, tool_name: "Edit" },
      { tool_input: { command: "ls" }, tool_name: "Bash" },
    ]) {
      const result = await runHook(script, payload);
      expect(result.code).toBe(0);
    }
  });
});

describe("codex generated-artifact tool gate", () => {
  const script = "supaschema hook generated-artifact-edit --runtime codex";

  it("fails closed when config or hook input cannot be classified", async () => {
    const project = await mkdtemp(join(tmpdir(), "supa-invalid-artifact-hook-"));
    await writeFile(join(project, "supaschema.config.json"), "{");
    const invalidConfig = await runHook(
      script,
      {
        cwd: project,
        tool_input: { file_path: "generated.ts" },
        tool_name: "Write",
      },
      { cwd: project }
    );
    const invalidPayload = await runHook(script, {}, { cwd: project, stdin: "{" });

    for (const result of [invalidConfig, invalidPayload]) {
      expect(result.code).toBe(0);
      const output = hookOutput(result.stdout);
      expect(output.hookSpecificOutput?.permissionDecision).toBe("deny");
      expect(output.hookSpecificOutput?.permissionDecisionReason).toContain(
        "SUPA_GENERATED_ARTIFACT_GUARD_FAILED"
      );
    }
  });

  it("denies apply_patch updates to migrations carrying the lineage marker", async () => {
    const { generated } = await fixtures();
    const patch = `*** Begin Patch\n*** Update File: ${generated}\n@@\n-SET lock_timeout = '5s';\n+SET lock_timeout = '1s';\n*** End Patch`;
    const result = await runHook(script, {
      tool_input: { command: patch },
      tool_name: "apply_patch",
    });

    expect(result.code).toBe(0);
    const output = hookOutput(result.stdout);
    expect(output.hookSpecificOutput?.permissionDecision).toBe("deny");
    expect(output.hookSpecificOutput?.permissionDecisionReason).toContain(
      "SUPA_GENERATED_ARTIFACT_EDIT"
    );
  });

  it("allows hand-authored targets and emits empty output", async () => {
    const { handAuthored } = await fixtures();
    const patch = `*** Begin Patch\n*** Update File: ${handAuthored}\n@@\n-x\n+y\n*** End Patch`;
    const result = await runHook(script, {
      tool_input: { command: patch },
      tool_name: "apply_patch",
    });

    expect(result.code).toBe(0);
    expect(JSON.parse(result.stdout)).toEqual({});
  });

  it("ignores removed direct file-path aliases", async () => {
    const { generated } = await fixtures();
    const result = await runHook(script, {
      tool_input: { file_path: generated },
      tool_name: "edit_file",
    });

    expect(jsonRecord(result.stdout)).toEqual({});
  });

  it("resolves relative patch targets from the payload cwd", async () => {
    const project = await mkdtemp(join(tmpdir(), "supa-codex-relative-hook-"));
    const generated = join(project, "supabase", "migrations", "20260611000000_generated.sql");
    await mkdir(dirname(generated), { recursive: true });
    await writeFile(generated, lineageSql);
    const patch =
      "*** Begin Patch\n" +
      "*** Update File: supabase/migrations/20260611000000_generated.sql\n" +
      "@@\n" +
      "-SET lock_timeout = '5s';\n" +
      "+SET lock_timeout = '1s';\n" +
      "*** End Patch";
    const result = await runHook(
      script,
      {
        cwd: project,
        tool_input: { command: patch },
        tool_name: "apply_patch",
      },
      { cwd: tmpdir() }
    );

    const output = hookOutput(result.stdout);
    expect(output.hookSpecificOutput?.permissionDecision).toBe("deny");
  });

  it("allows deleting a stale generated migration (the sanctioned recovery lane)", async () => {
    const { generated } = await fixtures();
    const patch = `*** Begin Patch\n*** Delete File: ${generated}\n*** End Patch`;
    const result = await runHook(script, {
      tool_input: { command: patch },
      tool_name: "apply_patch",
    });

    expect(result.code).toBe(0);
    expect(JSON.parse(result.stdout)).toEqual({});
  });

  it("denies delete-and-rewrite patches that replace a generated migration in place", async () => {
    const { generated } = await fixtures();
    const patch = `*** Begin Patch\n*** Delete File: ${generated}\n*** Add File: ${generated}\n+-- hand-written replacement\n*** End Patch`;
    const result = await runHook(script, {
      tool_input: { command: patch },
      tool_name: "apply_patch",
    });

    const output = hookOutput(result.stdout);
    expect(output.hookSpecificOutput?.permissionDecision).toBe("deny");
  });

  it("denies delete-and-rewrite patches even when the two headers spell the path differently", async () => {
    const { generated } = await fixtures();
    const dotSpelled = `${dirname(generated)}${sep}.${sep}${basename(generated)}`;
    const patch = `*** Begin Patch\n*** Delete File: ${dotSpelled}\n*** Add File: ${generated}\n+-- hand-written replacement\n*** End Patch`;
    const result = await runHook(script, {
      tool_input: { command: patch },
      tool_name: "apply_patch",
    });

    const output = hookOutput(result.stdout);
    expect(output.hookSpecificOutput?.permissionDecision).toBe("deny");
  });
});

describe.skipIf(!hasPrivateContextHooks)("agent-hooks PreToolUse subagent downgrade", () => {
  it("hard-denies a gated tool in the main session but only advises inside a subagent", async () => {
    const stateDir = await mkdtemp(join(tmpdir(), "supa-agent-hook-state-"));
    const env = { ...process.env, STATE_DIR: stateDir };
    const session = "subagent-downgrade-test";
    const promptHook = ".claude/hooks/context-user-prompt-submit.mjs";
    const preToolHook = ".claude/hooks/context-pre-tool-use.mjs";

    await runHook(
      promptHook,
      { prompt: "load the supaschema skill now", session_id: session },
      { env }
    );

    const gatedInput = {
      file_path: "src/example-not-a-skill.ts",
      new_string: "b",
      old_string: "a",
    };

    const mainCall = await runHook(
      preToolHook,
      { session_id: session, tool_input: gatedInput, tool_name: "Edit" },
      { env }
    );
    const mainOut = hookOutput(mainCall.stdout);
    expect(mainOut.hookSpecificOutput?.permissionDecision).toBe("deny");
    expect(mainOut.hookSpecificOutput?.permissionDecisionReason).toContain(
      "Required skills are pending"
    );

    const subCall = await runHook(
      preToolHook,
      {
        agent_id: "sub-1",
        session_id: session,
        tool_input: gatedInput,
        tool_name: "Edit",
      },
      { env }
    );
    const subOut = hookOutput(subCall.stdout);
    expect(subOut.hookSpecificOutput?.permissionDecision).toBeUndefined();
    expect(subOut.hookSpecificOutput?.additionalContext ?? "").toContain("subagent");
  });
});

const autoDiffCases = [{ name: "cli", script: "supaschema hook schema-write" }];

describe.each(autoDiffCases)("supaschema auto-diff hook ($name)", ({ script }) => {
  it("runs auto-diff for apply_patch schema deletes", async () => {
    const { env, log, project } = await autoDiffFixture(["supabase/schemas"]);
    const result = await runHook(
      script,
      {
        cwd: project,
        tool_input: {
          command: "*** Begin Patch\n*** Delete File: supabase/schemas/accounts.sql\n*** End Patch",
        },
        tool_name: "apply_patch",
      },
      { cwd: project, env }
    );

    expect(result.code).toBe(0);
    expect(hookAdditionalContext(result.stdout)).toContain("supaschema auto-diff completed");
    expect(hookAdditionalContext(result.stdout)).toContain("supaschema check passed");
    expect(await readFakeCalls(log)).toEqual([
      ["diff", "--to", "dir:supabase/schemas"],
      ["check", fakeMigrationPath],
    ]);
  });

  it("runs auto-diff for apply_patch moves into the schema tree", async () => {
    const { env, log, project } = await autoDiffFixture(["supabase/schemas"]);
    const result = await runHook(
      script,
      {
        cwd: project,
        tool_input: {
          command:
            "*** Begin Patch\n*** Update File: drafts/accounts.sql\n*** Move to: supabase/schemas/accounts.sql\n@@\n-CREATE TABLE app.t (id int);\n+CREATE TABLE app.t (id bigint);\n*** End Patch",
        },
        tool_name: "apply_patch",
      },
      { cwd: project, env }
    );

    expect(result.code).toBe(0);
    expect(await readFakeCalls(log)).toEqual([
      ["diff", "--to", "dir:supabase/schemas"],
      ["check", fakeMigrationPath],
    ]);
  });

  it("skips auto-diff for a single-root edit in a multi-root config", async () => {
    const { env, log, project } = await autoDiffFixture(["schemas/one", "schemas/two"]);
    await writeFile(
      join(project, "schemas", "two", "accounts.sql"),
      "CREATE TABLE app.t (id int);"
    );
    const result = await runHook(
      script,
      {
        cwd: project,
        tool_input: {
          file_path: join(project, "schemas", "two", "accounts.sql"),
        },
        tool_name: "Edit",
      },
      { cwd: project, env }
    );

    expect(result.code).toBe(0);
    expect(result.stdout).toContain("multi-root schemaPaths");
    expect(await readFakeCalls(log)).toEqual([]);
  });

  it("runs auto-diff for direct Edit schema edits", async () => {
    const { env, log, project } = await autoDiffFixture(["supabase/schemas"]);
    await writeFile(
      join(project, "supabase", "schemas", "accounts.sql"),
      "CREATE TABLE app.t (id int);"
    );
    const result = await runHook(
      script,
      {
        cwd: project,
        tool_input: { file_path: join(project, "supabase", "schemas", "accounts.sql") },
        tool_name: "Edit",
      },
      { cwd: project, env }
    );

    expect(result.code).toBe(0);
    expect(await readFakeCalls(log)).toEqual([
      ["diff", "--to", "dir:supabase/schemas"],
      ["check", fakeMigrationPath],
    ]);
  });

  it("skips auto-diff when workflow.schema_diff is manual", async () => {
    const { env, log, project } = await autoDiffFixture(["supabase/schemas"]);
    await writeFile(
      join(project, "supaschema.config.json"),
      JSON.stringify({
        schemaPaths: ["supabase/schemas"],
        workflow: { schema_diff: "manual" },
      })
    );
    await writeFile(
      join(project, "supabase", "schemas", "accounts.sql"),
      "CREATE TABLE app.t (id int);"
    );

    const result = await runHook(
      script,
      {
        cwd: project,
        tool_input: {
          file_path: join(project, "supabase", "schemas", "accounts.sql"),
        },
        tool_name: "Edit",
      },
      { cwd: project, env }
    );

    expect(result.code).toBe(0);
    expect(hookAdditionalContext(result.stdout)).toContain('workflow.schema_diff is "manual"');
    expect(await readFakeCalls(log)).toEqual([]);
  });

  it("skips post-diff check when workflow.migration_check is manual", {
    timeout: 20_000,
  }, async () => {
    const { env, log, project } = await autoDiffFixture(["supabase/schemas"]);
    await writeFile(
      join(project, "supaschema.config.json"),
      JSON.stringify({
        schemaPaths: ["supabase/schemas"],
        workflow: { migration_check: "manual" },
      })
    );
    await writeFile(
      join(project, "supabase", "schemas", "accounts.sql"),
      "CREATE TABLE app.t (id int);"
    );

    const result = await runHook(
      script,
      {
        cwd: project,
        tool_input: {
          file_path: join(project, "supabase", "schemas", "accounts.sql"),
        },
        tool_name: "Edit",
      },
      { cwd: project, env }
    );

    expect(result.code).toBe(0);
    expect(hookAdditionalContext(result.stdout)).toContain('workflow.migration_check is "manual"');
    expect(await readFakeCalls(log)).toEqual([["diff", "--to", "dir:supabase/schemas"]]);
  });

  it("runs config-gated sync instead of diff/check for resolved automatic targets", {
    timeout: 20_000,
  }, async () => {
    const { env, log, project } = await autoDiffFixture(
      ["supabase/schemas"],
      `#!/usr/bin/env node
import { appendFileSync } from "node:fs";

appendFileSync(process.env.SUPASCHEMA_FAKE_LOG, JSON.stringify(process.argv.slice(2)) + "\\n");
if (process.argv[2] === "sync") {
  process.stdout.write("sync ok\\n");
  process.exit(0);
}
process.exit(1);
`
    );
    await writeFile(
      join(project, "supaschema.config.json"),
      JSON.stringify({
        environments: { local: { databaseUrl: "$SUPASCHEMA_HOOK_LOCAL_DATABASE_URL" } },
        schemaPaths: ["supabase/schemas"],
        sync: {
          targets: {
            local: {
              environment: "local",
              historyTable: "supabase_migrations.schema_migrations",
              mode: "auto",
              runner: "direct",
            },
          },
        },
        workflow: { migration_sync: "auto" },
      })
    );
    await writeFile(
      join(project, "supabase", "schemas", "accounts.sql"),
      "CREATE TABLE app.t (id int);"
    );

    const result = await runHook(
      script,
      {
        cwd: project,
        tool_input: { file_path: join(project, "supabase", "schemas", "accounts.sql") },
        tool_name: "Edit",
      },
      {
        cwd: project,
        env: {
          ...env,
          SUPASCHEMA_HOOK_LOCAL_DATABASE_URL: "postgresql://postgres:postgres@localhost/db",
        },
      }
    );

    expect(result.code).toBe(0);
    expect(hookAdditionalContext(result.stdout)).toContain("supaschema auto-sync completed");
    expect(hookAdditionalContext(result.stdout)).toContain(
      "Automatic sync target preflight passed for local"
    );
    expect(await readFakeCalls(log)).toEqual([["sync"]]);
  });

  it("falls back to diff/check when automatic remote approval is absent", {
    timeout: 20_000,
  }, async () => {
    const { env, log, project } = await autoDiffFixture(["supabase/schemas"]);
    await writeFile(
      join(project, "supaschema.config.json"),
      JSON.stringify({
        environments: {
          production: {
            databaseUrl: "$SUPASCHEMA_HOOK_REMOTE_DATABASE_URL",
          },
        },
        schemaPaths: ["supabase/schemas"],
        sync: {
          targets: {
            remote: {
              environment: "production",
              historyTable: "supabase_migrations.schema_migrations",
              mode: "auto",
              remote: true,
              requireApprovalEnv: "SUPASCHEMA_REMOTE_SYNC_APPROVED",
              runner: "direct",
            },
          },
        },
        workflow: { migration_sync: "auto" },
      })
    );
    await writeFile(
      join(project, "supabase", "schemas", "accounts.sql"),
      "CREATE TABLE app.t (id int);"
    );

    const result = await runHook(
      script,
      {
        cwd: project,
        tool_input: {
          file_path: join(project, "supabase", "schemas", "accounts.sql"),
        },
        tool_name: "Edit",
      },
      {
        cwd: project,
        env: {
          ...env,
          SUPASCHEMA_HOOK_REMOTE_DATABASE_URL: "postgresql://postgres:postgres@localhost/db",
        },
      }
    );

    expect(result.code).toBe(0);
    const context = hookAdditionalContext(result.stdout);
    expect(context).toContain(
      "Automatic sync skipped: remote sync target remote requires SUPASCHEMA_REMOTE_SYNC_APPROVED=1"
    );
    expect(await readFakeCalls(log)).toEqual([
      ["diff", "--to", "dir:supabase/schemas"],
      ["check", fakeMigrationPath],
    ]);
  });

  it("runs config-gated sync for approved automatic remote targets", {
    timeout: 20_000,
  }, async () => {
    const { env, log, project } = await autoDiffFixture(
      ["supabase/schemas"],
      `#!/usr/bin/env node
import { appendFileSync } from "node:fs";

appendFileSync(process.env.SUPASCHEMA_FAKE_LOG, JSON.stringify(process.argv.slice(2)) + "\\n");
if (process.argv[2] === "sync") {
  process.stdout.write("remote sync ok\\n");
  process.exit(0);
}
process.exit(1);
`
    );
    await writeFile(
      join(project, "supaschema.config.json"),
      JSON.stringify({
        environments: {
          production: {
            databaseUrl: "$SUPASCHEMA_HOOK_REMOTE_DATABASE_URL",
          },
        },
        schemaPaths: ["supabase/schemas"],
        sync: {
          targets: {
            remote: {
              environment: "production",
              historyTable: "supabase_migrations.schema_migrations",
              mode: "auto",
              remote: true,
              requireApprovalEnv: "SUPASCHEMA_REMOTE_SYNC_APPROVED",
              runner: "direct",
            },
          },
        },
        workflow: { migration_sync: "auto" },
      })
    );
    await writeFile(
      join(project, "supabase", "schemas", "accounts.sql"),
      "CREATE TABLE app.t (id int);"
    );

    const result = await runHook(
      script,
      {
        cwd: project,
        tool_input: {
          file_path: join(project, "supabase", "schemas", "accounts.sql"),
        },
        tool_name: "Edit",
      },
      {
        cwd: project,
        env: {
          ...env,
          SUPASCHEMA_HOOK_REMOTE_DATABASE_URL: "postgresql://postgres:postgres@localhost/db",
          SUPASCHEMA_REMOTE_SYNC_APPROVED: "1",
        },
      }
    );

    expect(result.code).toBe(0);
    expect(hookAdditionalContext(result.stdout)).toContain(
      "Automatic sync target preflight passed for remote"
    );
    expect(await readFakeCalls(log)).toEqual([["sync"]]);
  });

  it("blocks the agent loop when config-gated sync fails", {
    timeout: 20_000,
  }, async () => {
    const { env, log, project } = await autoDiffFixture(
      ["supabase/schemas"],
      `#!/usr/bin/env node
import { appendFileSync } from "node:fs";

appendFileSync(process.env.SUPASCHEMA_FAKE_LOG, JSON.stringify(process.argv.slice(2)) + "\\n");
if (process.argv[2] === "sync") {
  process.stderr.write("ERROR SUPA_RLS_POLICY_UNSAFE: policy exposes rows\\n");
  process.exit(2);
}
process.exit(1);
`
    );
    await writeFile(
      join(project, "supaschema.config.json"),
      JSON.stringify({
        environments: {
          local: { databaseUrl: "$SUPASCHEMA_HOOK_LOCAL_DATABASE_URL" },
        },
        schemaPaths: ["supabase/schemas"],
        sync: {
          targets: {
            local: {
              environment: "local",
              historyTable: "supabase_migrations.schema_migrations",
              mode: "auto",
              runner: "direct",
            },
          },
        },
        workflow: { migration_sync: "auto" },
      })
    );
    await writeFile(
      join(project, "supabase", "schemas", "accounts.sql"),
      "CREATE TABLE app.t (id int);"
    );

    const result = await runHook(
      script,
      {
        cwd: project,
        tool_input: {
          file_path: join(project, "supabase", "schemas", "accounts.sql"),
        },
        tool_name: "Edit",
      },
      {
        cwd: project,
        env: {
          ...env,
          SUPASCHEMA_HOOK_LOCAL_DATABASE_URL: "postgresql://postgres:postgres@localhost/db",
        },
      }
    );
    const output = hookOutput(result.stdout);

    expect(result.code).toBe(0);
    expect(output.decision).toBe("block");
    expect(output.reason).toContain("supaschema sync failed");
    expect(output.reason).toContain("SUPA_RLS_POLICY_UNSAFE");
    expect(output.hookSpecificOutput?.additionalContext).toContain("supaschema auto-sync for");
    expect(await readFakeCalls(log)).toEqual([["sync"]]);
  });

  it("falls back to diff/check when an automatic target URL is unresolved", async () => {
    const { env, log, project } = await autoDiffFixture(["supabase/schemas"]);
    await writeFile(
      join(project, "supaschema.config.json"),
      JSON.stringify({
        environments: {
          local: { databaseUrl: "$SUPASCHEMA_HOOK_MISSING_DATABASE_URL" },
        },
        schemaPaths: ["supabase/schemas"],
        sync: {
          targets: {
            local: {
              environment: "local",
              historyTable: "supabase_migrations.schema_migrations",
              mode: "auto",
              runner: "direct",
            },
          },
        },
        workflow: { migration_sync: "auto" },
      })
    );
    await writeFile(
      join(project, "supabase", "schemas", "accounts.sql"),
      "CREATE TABLE app.t (id int);"
    );

    const result = await runHook(
      script,
      {
        cwd: project,
        tool_input: {
          file_path: join(project, "supabase", "schemas", "accounts.sql"),
        },
        tool_name: "Edit",
      },
      { cwd: project, env }
    );

    expect(result.code).toBe(0);
    expect(hookAdditionalContext(result.stdout)).toContain(
      "Automatic sync skipped: sync target local requires $SUPASCHEMA_HOOK_MISSING_DATABASE_URL"
    );
    expect(await readFakeCalls(log)).toEqual([
      ["diff", "--to", "dir:supabase/schemas"],
      ["check", fakeMigrationPath],
    ]);
  });

  it("continues the agent loop when automatic diff fails", async () => {
    const { env, log, project } = await autoDiffFixture(
      ["supabase/schemas"],
      `#!/usr/bin/env node
import { appendFileSync } from "node:fs";

appendFileSync(process.env.SUPASCHEMA_FAKE_LOG, JSON.stringify(process.argv.slice(2)) + "\\n");
if (process.argv[2] === "diff") {
  process.stderr.write("ERROR SUPA_DIFF_LINEAGE_GAP: generated migration lineage is broken\\n");
  process.exit(2);
}
process.exit(1);
`
    );
    await writeFile(
      join(project, "supabase", "schemas", "accounts.sql"),
      "CREATE TABLE app.t (id int);"
    );

    const result = await runHook(
      script,
      {
        cwd: project,
        tool_input: {
          file_path: join(project, "supabase", "schemas", "accounts.sql"),
        },
        tool_name: "Edit",
      },
      { cwd: project, env }
    );
    const output = hookOutput(result.stdout);

    expect(result.code).toBe(0);
    expect(output.decision).toBe("block");
    expect(output.reason).toContain("supaschema diff failed");
    expect(output.reason).toContain("SUPA_DIFF_LINEAGE_GAP");
    expect(output.hookSpecificOutput?.additionalContext).toContain("supaschema auto-diff for");
    expect(await readFakeCalls(log)).toEqual([["diff", "--to", "dir:supabase/schemas"]]);
  });

  it("continues the agent loop when post-diff check fails", async () => {
    const { env, log, project } = await autoDiffFixture(
      ["supabase/schemas"],
      `#!/usr/bin/env node
import { appendFileSync } from "node:fs";

appendFileSync(process.env.SUPASCHEMA_FAKE_LOG, JSON.stringify(process.argv.slice(2)) + "\\n");
if (process.argv[2] === "diff") {
  process.stdout.write("${fakeMigrationPath}\\n");
  process.exit(0);
}
if (process.argv[2] === "check") {
  process.stderr.write("ERROR SUPA_CHECK_CREATE_TABLE_GUARD: TABLE creation must use IF NOT EXISTS or a catalog guard\\n");
  process.exit(2);
}
process.exit(1);
`
    );
    await writeFile(
      join(project, "supabase", "schemas", "accounts.sql"),
      "CREATE TABLE app.t (id int);"
    );

    const result = await runHook(
      script,
      {
        cwd: project,
        tool_input: {
          file_path: join(project, "supabase", "schemas", "accounts.sql"),
        },
        tool_name: "Edit",
      },
      { cwd: project, env }
    );
    const output = hookOutput(result.stdout);

    expect(result.code).toBe(0);
    expect(output.decision).toBe("block");
    expect(output.reason).toContain("supaschema check failed");
    expect(output.reason).toContain("SUPA_CHECK_CREATE_TABLE_GUARD");
    expect(output.reason).toContain("root source");
    expect(output.reason).toContain("correlated failures");
    expect(output.hookSpecificOutput?.additionalContext).toContain(
      "supaschema check reported diagnostics"
    );
    expect(await readFakeCalls(log)).toEqual([
      ["diff", "--to", "dir:supabase/schemas"],
      ["check", fakeMigrationPath],
    ]);
  });

  it("runs verify when workflow.migration_verify is after_schema_diff", async () => {
    const { env, log, project } = await autoDiffFixture(
      ["supabase/schemas"],
      `#!/usr/bin/env node
import { appendFileSync } from "node:fs";

appendFileSync(process.env.SUPASCHEMA_FAKE_LOG, JSON.stringify(process.argv.slice(2)) + "\\n");
if (process.argv[2] === "diff") {
  process.stdout.write("${fakeMigrationPath}\\n");
  process.exit(0);
}
if (process.argv[2] === "check" || process.argv[2] === "verify") {
  process.exit(0);
}
process.exit(1);
`
    );
    await writeFile(
      join(project, "supaschema.config.json"),
      JSON.stringify({
        schemaPaths: ["supabase/schemas"],
        workflow: { migration_verify: "after_schema_diff" },
      })
    );
    await writeFile(
      join(project, "supabase", "schemas", "accounts.sql"),
      "CREATE TABLE app.t (id int);"
    );

    const result = await runHook(
      script,
      {
        cwd: project,
        tool_input: {
          file_path: join(project, "supabase", "schemas", "accounts.sql"),
        },
        tool_name: "Edit",
      },
      { cwd: project, env }
    );

    expect(result.code).toBe(0);
    expect(hookAdditionalContext(result.stdout)).toContain("supaschema verify passed");
    expect(await readFakeCalls(log)).toEqual([
      ["diff", "--to", "dir:supabase/schemas"],
      ["check", fakeMigrationPath],
      ["verify"],
    ]);
  });

  it("defaults to the generic PostgreSQL schema path when no config exists", async () => {
    const { env, log, project } = await autoDiffFixture(["database/schemas"], undefined, {
      writeConfig: false,
    });
    await writeFile(
      join(project, "database", "schemas", "accounts.sql"),
      "CREATE TABLE app.t (id int);"
    );
    const result = await runHook(
      script,
      {
        cwd: project,
        tool_input: {
          file_path: join(project, "database", "schemas", "accounts.sql"),
        },
        tool_name: "Edit",
      },
      { cwd: project, env }
    );

    expect(result.code).toBe(0);
    expect(await readFakeCalls(log)).toEqual([
      ["diff", "--to", "dir:database/schemas"],
      ["check", fakeMigrationPath],
    ]);
  });

  it("defaults to a detected provider schema path when no config exists", async () => {
    const { env, log, project } = await autoDiffFixture(["neon/schemas"], undefined, {
      writeConfig: false,
    });
    await writeFile(join(project, "neon.toml"), "project_id = 'quiet-waterfall-123456'\n");
    await writeFile(
      join(project, "neon", "schemas", "accounts.sql"),
      "CREATE TABLE app.t (id int);"
    );
    const result = await runHook(
      script,
      {
        cwd: project,
        tool_input: {
          file_path: join(project, "neon", "schemas", "accounts.sql"),
        },
        tool_name: "Edit",
      },
      { cwd: project, env }
    );

    expect(result.code).toBe(0);
    expect(await readFakeCalls(log)).toEqual([
      ["diff", "--to", "dir:neon/schemas"],
      ["check", fakeMigrationPath],
    ]);
  });

  it("skips auto-diff when one edit touches multiple schema paths", async () => {
    const { env, log, project } = await autoDiffFixture(["schemas/one", "schemas/two"]);
    await writeFile(join(project, "schemas", "one", "one.sql"), "CREATE TABLE app.one (id int);");
    await writeFile(join(project, "schemas", "two", "two.sql"), "CREATE TABLE app.two (id int);");
    const result = await runHook(
      script,
      {
        cwd: project,
        tool_input: {
          command:
            "*** Begin Patch\n" +
            "*** Update File: schemas/one/one.sql\n" +
            "@@\n-old\n+new\n" +
            "*** Update File: schemas/two/two.sql\n" +
            "@@\n-old\n+new\n" +
            "*** End Patch",
        },
        tool_name: "apply_patch",
      },
      { cwd: project, env }
    );

    expect(result.code).toBe(0);
    expect(result.stdout).toContain("multi-root schemaPaths");
    expect(await readFakeCalls(log)).toEqual([]);
  });

  it("skips auto-diff while install path confirmation is pending", async () => {
    const { env, log, project } = await autoDiffFixture(["apps/api/schemas"], undefined, {
      writeConfig: false,
    });
    await mkdir(join(project, ".supaschema"), { recursive: true });
    await mkdir(join(project, "packages", "db", "schemas"), {
      recursive: true,
    });
    await writeFile(
      join(project, ".supaschema", "install.json"),
      JSON.stringify({
        candidates: {
          migrationsDirs: ["apps/api/migrations", "packages/db/migrations"],
          schemaPaths: ["apps/api/schemas", "packages/db/schemas"],
        },
        migrationsDir: "apps/api/migrations",
        pathConfirmationNeeded: true,
        schemaPaths: ["apps/api/schemas"],
      })
    );
    await writeFile(
      join(project, "apps", "api", "schemas", "accounts.sql"),
      "CREATE TABLE app.t (id int);"
    );
    const result = await runHook(
      script,
      {
        cwd: project,
        tool_input: {
          file_path: join(project, "apps", "api", "schemas", "accounts.sql"),
        },
        tool_name: "Edit",
      },
      { cwd: project, env }
    );

    expect(result.code).toBe(0);
    expect(result.stdout).toContain("path confirmation is pending");
    expect(result.stdout).toContain(".supaschema/install.json");
    expect(await readFakeCalls(log)).toEqual([]);
  });

  it("resumes auto-diff once config confirms all path fields despite a stale pending flag", async () => {
    const { env, log, project } = await autoDiffFixture(["apps/api/schemas"]);
    await writeFile(
      join(project, "supaschema.config.json"),
      JSON.stringify({
        migrationsDir: "apps/api/migrations",
        schemaPaths: ["apps/api/schemas"],
        sources: { from: "auto" },
      })
    );
    await mkdir(join(project, ".supaschema"), { recursive: true });
    await writeFile(
      join(project, ".supaschema", "install.json"),
      JSON.stringify({
        candidates: {
          migrationsDirs: ["apps/api/migrations", "packages/db/migrations"],
          schemaPaths: ["apps/api/schemas", "packages/db/schemas"],
        },
        migrationsDir: "apps/api/migrations",
        pathConfirmationNeeded: true,
        schemaPaths: ["apps/api/schemas"],
      })
    );
    await writeFile(
      join(project, "apps", "api", "schemas", "accounts.sql"),
      "CREATE TABLE app.t (id int);"
    );
    const result = await runHook(
      script,
      {
        cwd: project,
        tool_input: {
          file_path: join(project, "apps", "api", "schemas", "accounts.sql"),
        },
        tool_name: "Edit",
      },
      { cwd: project, env }
    );

    expect(result.code).toBe(0);
    expect(result.stdout).not.toContain("path confirmation is pending");
    expect(await readFakeCalls(log)).toEqual([
      ["diff", "--to", "dir:apps/api/schemas"],
      ["check", fakeMigrationPath],
    ]);
  });

  it("redacts secrets from raw supaschema output", async () => {
    const jwt = "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIn0.signature";
    const { env, project } = await autoDiffFixture(
      ["supabase/schemas"],
      `#!/usr/bin/env node
import { appendFileSync } from "node:fs";

appendFileSync(process.env.SUPASCHEMA_FAKE_LOG, JSON.stringify(process.argv.slice(2)) + "\\n");
if (process.argv[2] === "diff") {
  process.stderr.write("failed postgresql://postgres:super-secret@localhost/db token=abc123 ${jwt}\\n");
  process.exit(1);
}
process.exit(0);
`
    );
    await writeFile(
      join(project, "supabase", "schemas", "accounts.sql"),
      "CREATE TABLE app.t (id int);"
    );
    const result = await runHook(
      script,
      {
        cwd: project,
        tool_input: {
          file_path: join(project, "supabase", "schemas", "accounts.sql"),
        },
        tool_name: "Edit",
      },
      { cwd: project, env }
    );

    expect(result.code).toBe(0);
    const output = hookOutput(result.stdout);
    const context = output.hookSpecificOutput?.additionalContext ?? "";
    expect(context).toContain("postgresql://postgres:[redacted]@localhost/db");
    expect(context).toContain("token=[redacted]");
    expect(context).toContain("[redacted-jwt]");
    expect(context).not.toContain("super-secret");
    expect(context).not.toContain("abc123");
    expect(context).not.toContain("eyJhbGci");
  });
});
