import { type ExecFileOptions, execFile } from "node:child_process";
import { mkdir, mkdtemp, readdir, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { basename, join } from "node:path";
import { promisify } from "node:util";
import { describe, expect, it } from "vitest";
import { MODEL_FORMAT_VERSION } from "../../src/hash.js";
import { latestLineage, parseLineage } from "../../src/migrations/lineage.js";

const run = promisify(execFile);
const cliPath = join(process.cwd(), "dist/cli.js");

interface CliResult {
  code: number;
  stderr: string;
  stdout: string;
}

async function cli(args: string[], options: ExecFileOptions = {}): Promise<CliResult> {
  try {
    const { stdout, stderr } = await run("node", [cliPath, ...args], options);
    return { code: 0, stderr, stdout };
  } catch (error) {
    const failure = error;
    return { code: failure.code ?? 1, stderr: failure.stderr ?? "", stdout: failure.stdout ?? "" };
  }
}

async function git(cwd: string, args: string[]): Promise<void> {
  await run("git", ["-C", cwd, ...args], {
    env: {
      ...process.env,
      GIT_AUTHOR_EMAIL: "test@supaschema.local",
      GIT_AUTHOR_NAME: "Supaschema Test",
      GIT_COMMITTER_EMAIL: "test@supaschema.local",
      GIT_COMMITTER_NAME: "Supaschema Test",
    },
  });
}

async function writeBasicFixtureConfig(
  directory: string,
  targets: Record<string, Record<string, unknown>> = {}
): Promise<string> {
  const path = join(directory, "supaschema.config.json");
  await writeFile(
    path,
    JSON.stringify({
      hints: { destructive: ["function:app.legacy_ping()"] },
      sync: { targets },
    })
  );
  return path;
}

describe("lineage parsing", () => {
  it("parses the embedded lineage marker", () => {
    const lineage = parseLineage("-- header\n-- supaschema: lineage from=abc123 to=def456\nSET x;");

    expect(lineage).toEqual({ from: "abc123", to: "def456" });
  });

  it("parses model format metadata from new lineage markers", () => {
    const lineage = parseLineage(
      "-- header\n-- supaschema: lineage format=3 from=abc123 to=def456\nSET x;"
    );

    expect(lineage).toEqual({ from: "abc123", modelFormatVersion: 3, to: "def456" });
  });

  it("returns undefined for hand-authored migrations", () => {
    expect(parseLineage("-- migration\nCREATE TABLE t (id int);")).toBeUndefined();
  });

  it("finds the newest lineage-bearing migration by filename order", async () => {
    const directory = await mkdtemp(join(tmpdir(), "supa-lineage-"));
    await writeFile(
      join(directory, "0001_old.sql"),
      "-- supaschema: lineage from=a to=b\nSELECT 1;"
    );
    await writeFile(
      join(directory, "0002_new.sql"),
      "-- supaschema: lineage from=b to=c\nSELECT 1;"
    );
    await writeFile(join(directory, "0003_hand.sql"), "-- hand-authored\nSELECT 1;");

    const latest = await latestLineage(directory);

    expect(latest?.from).toBe("b");
    expect(latest?.to).toBe("c");
    expect(latest?.file).toContain("0002_new.sql");
  });

  it("returns undefined for missing or lineage-free directories", async () => {
    const directory = await mkdtemp(join(tmpdir(), "supa-lineage-empty-"));

    expect(await latestLineage(directory)).toBeUndefined();
    expect(await latestLineage(join(directory, "missing"))).toBeUndefined();
  });
});

describe("diff lineage chain gate", () => {
  const fromArg = "dir:tests/fixtures/basic/from";
  const toArg = "dir:tests/fixtures/basic/to";

  it("--out stdout takes precedence over --name and does not write a migration", {
    timeout: 60_000,
  }, async () => {
    const directory = await mkdtemp(join(tmpdir(), "supa-stdout-"));
    const config = await writeBasicFixtureConfig(await mkdtemp(join(tmpdir(), "supa-config-")));

    const result = await cli([
      "--config",
      config,
      "diff",
      "--from",
      fromArg,
      "--to",
      toArg,
      "--name",
      "named_stdout",
      "--migrations-dir",
      directory,
      "--out",
      "stdout",
    ]);

    expect(result.code, result.stderr).toBe(0);
    expect(result.stdout).toContain("-- Generated by supaschema");
    expect(result.stdout).toContain("CREATE TABLE");
    expect(await readdir(directory)).toEqual([]);
  });

  it("refuses named empty migration writes", { timeout: 60_000 }, async () => {
    const directory = await mkdtemp(join(tmpdir(), "supa-empty-diff-"));
    const config = await writeBasicFixtureConfig(await mkdtemp(join(tmpdir(), "supa-config-")));

    const result = await cli([
      "--config",
      config,
      "diff",
      "--from",
      fromArg,
      "--to",
      fromArg,
      "--name",
      "schema_diff",
      "--migrations-dir",
      directory,
    ]);

    expect(result.code).toBe(2);
    expect(result.stderr).toContain("SUPA_DIFF_EMPTY_PLAN");
    expect(await readdir(directory)).toEqual([]);
  });

  it("replaces generated migrations only from the original lineage baseline", {
    timeout: 60_000,
  }, async () => {
    const directory = await mkdtemp(join(tmpdir(), "supa-replace-"));
    const config = await writeBasicFixtureConfig(await mkdtemp(join(tmpdir(), "supa-config-")));
    const diff = ["--config", config, "diff"];
    const generated = join(directory, "20260101000000_generated.sql");

    const initial = await cli([
      ...diff,
      "--from",
      fromArg,
      "--to",
      toArg,
      "--migrations-dir",
      directory,
      "--out",
      generated,
    ]);
    expect(initial.code, initial.stderr).toBe(0);
    const original = await readFile(generated, "utf8");
    expect(parseLineage(original)).toBeDefined();

    const wrongBaseline = await cli([
      ...diff,
      "--from",
      toArg,
      "--to",
      toArg,
      "--migrations-dir",
      directory,
      "--replace",
      generated,
    ]);
    expect(wrongBaseline.code).toBe(2);
    expect(wrongBaseline.stderr).toContain("SUPA_DIFF_REPLACE_BASELINE_REQUIRED");

    const replaced = await cli([
      ...diff,
      "--from",
      fromArg,
      "--to",
      toArg,
      "--migrations-dir",
      directory,
      "--replace",
      generated,
    ]);
    expect(replaced.code, replaced.stderr).toBe(0);
    expect(replaced.stderr).toContain("SUPA_DIFF_REPLACE_APPLIED_STATE_UNVERIFIED");
    expect(replaced.stdout).toContain(generated);
    expect(parseLineage(await readFile(generated, "utf8"))).toBeDefined();
  });

  it("excludes the replaced migration from a migrations replay baseline", {
    timeout: 60_000,
  }, async () => {
    const root = await mkdtemp(join(tmpdir(), "supa-replace-replay-"));
    const migrationsDir = join(root, "migrations");
    const schemaDir = join(root, "schemas");
    await mkdir(migrationsDir);
    await mkdir(schemaDir);
    const config = join(root, "supaschema.config.json");
    await writeFile(
      config,
      JSON.stringify({
        migrationsDir: "migrations",
        schemaPaths: ["schemas"],
        sources: { from: "migrations:migrations" },
        sync: { targets: {} },
      })
    );
    const schemaFile = join(schemaDir, "app.sql");
    await writeFile(
      schemaFile,
      "CREATE SCHEMA app;\nCREATE TABLE app.accounts (id bigint PRIMARY KEY);\n"
    );
    const generated = join(migrationsDir, "20260101000000_generated.sql");
    const initial = await cli(
      [
        "--config",
        config,
        "diff",
        "--from",
        "empty:",
        "--to",
        "dir:schemas",
        "--migrations-dir",
        "migrations",
        "--out",
        generated,
      ],
      { cwd: root }
    );
    expect(initial.code, initial.stderr).toBe(0);
    const originalLineage = parseLineage(await readFile(generated, "utf8"));
    expect(originalLineage).toBeDefined();
    await writeFile(
      schemaFile,
      "CREATE SCHEMA app;\nCREATE TABLE app.accounts (id bigint PRIMARY KEY, name text);\n"
    );

    const replaced = await cli(
      [
        "--config",
        config,
        "diff",
        "--from",
        "migrations:migrations",
        "--to",
        "dir:schemas",
        "--migrations-dir",
        "migrations",
        "--replace",
        generated,
      ],
      { cwd: root }
    );

    expect(replaced.code, replaced.stderr).toBe(0);
    expect(replaced.stderr).not.toContain("SUPA_DIFF_REPLACE_BASELINE_REQUIRED");
    const replacedSql = await readFile(generated, "utf8");
    expect(replacedSql).toContain("CREATE TABLE");
    expect(replacedSql).not.toContain('ADD COLUMN IF NOT EXISTS "name"');
    expect(parseLineage(replacedSql)?.from).toBe(originalLineage?.from);
  });

  it("uses an ambient database URL to gate a URL-less replacement target", {
    timeout: 60_000,
  }, async () => {
    const directory = await mkdtemp(join(tmpdir(), "supa-replace-explicit-target-"));
    const config = await writeBasicFixtureConfig(await mkdtemp(join(tmpdir(), "supa-config-")), {
      local: {
        historyTable: "supabase_migrations.schema_migrations",
        mode: "manual",
        runner: "direct",
      },
    });
    const generated = join(directory, "20260101000000_generated.sql");
    const diff = [
      "--config",
      config,
      "diff",
      "--from",
      fromArg,
      "--to",
      toArg,
      "--migrations-dir",
      directory,
    ];

    const initial = await cli([...diff, "--out", generated]);
    expect(initial.code, initial.stderr).toBe(0);

    const replaced = await cli([...diff, "--replace", generated], {
      env: {
        ...process.env,
        SUPASCHEMA_DATABASE_URL:
          "postgresql://postgres:postgres@127.0.0.1:1/postgres?connect_timeout=1",
      },
    });

    expect(replaced.code).toBe(2);
    expect(replaced.stderr).toContain("SUPA_MIGRATIONS_TARGET_UNAVAILABLE");
    expect(replaced.stderr).not.toContain("SUPA_DIFF_REPLACE_APPLIED_STATE_UNVERIFIED");
  });

  it("refuses to replace generated migrations older than the migration tip", {
    timeout: 60_000,
  }, async () => {
    const directory = await mkdtemp(join(tmpdir(), "supa-replace-tip-"));
    const config = await writeBasicFixtureConfig(await mkdtemp(join(tmpdir(), "supa-config-")));
    const diff = ["--config", config, "diff"];
    const generated = join(directory, "20260101000000_generated.sql");

    const initial = await cli([
      ...diff,
      "--from",
      fromArg,
      "--to",
      toArg,
      "--migrations-dir",
      directory,
      "--out",
      generated,
    ]);
    expect(initial.code, initial.stderr).toBe(0);
    await writeFile(
      join(directory, "20260102000000_later.sql"),
      "-- supaschema: lineage from=abc to=def\nSELECT 1;\n"
    );

    const replaced = await cli([
      ...diff,
      "--from",
      fromArg,
      "--to",
      toArg,
      "--migrations-dir",
      directory,
      "--replace",
      generated,
    ]);
    expect(replaced.code).toBe(2);
    expect(replaced.stderr).toContain("SUPA_DIFF_REPLACE_NOT_LATEST");
  });

  it("replaces generated git-baseline migrations from the original lineage baseline", {
    timeout: 60_000,
  }, async () => {
    const repo = await mkdtemp(join(tmpdir(), "supa-replace-git-"));
    const schemaDir = join(repo, "schemas");
    const migrationsDir = join(repo, "migrations");
    await mkdir(schemaDir, { recursive: true });
    await mkdir(migrationsDir, { recursive: true });
    const config = join(repo, "supaschema.config.json");
    await writeFile(
      config,
      JSON.stringify({
        migrationsDir: "migrations",
        schemaPaths: ["schemas"],
        sources: { from: "auto" },
        sync: { targets: {} },
      })
    );
    const schemaFile = join(schemaDir, "app.sql");
    await writeFile(
      schemaFile,
      "CREATE SCHEMA app;\nCREATE TABLE app.accounts (\n  id bigint PRIMARY KEY\n);\n"
    );
    await git(repo, ["init"]);
    await git(repo, ["add", "schemas", "supaschema.config.json"]);
    await git(repo, ["commit", "-m", "initial"]);
    await writeFile(
      schemaFile,
      "CREATE SCHEMA app;\nCREATE TABLE app.accounts (\n  id bigint PRIMARY KEY,\n  name text\n);\n"
    );
    await git(repo, ["add", "schemas/app.sql"]);
    await git(repo, ["commit", "-m", "target"]);

    const generated = join(migrationsDir, "20260101000000_generated.sql");
    const diff = [
      "--config",
      config,
      "diff",
      "--from",
      "git:HEAD^",
      "--to",
      "dir:schemas",
      "--migrations-dir",
      "migrations",
    ];
    const initial = await cli([...diff, "--out", generated], { cwd: repo });
    expect(initial.code, initial.stderr).toBe(0);
    await writeFile(join(migrationsDir, "20250101000000_hand_authored.sql"), "SELECT 1;\n");

    const replaced = await cli([...diff, "--replace", generated], { cwd: repo });
    expect(replaced.code, replaced.stderr).toBe(0);
    expect(replaced.stderr).not.toContain("SUPA_MIGRATION_BASELINE_MISMATCH");
    expect(replaced.stderr).not.toContain("SUPA_MIGRATION_BASELINE_UNSUPPORTED");
    expect(replaced.stderr).toContain("SUPA_DIFF_REPLACE_APPLIED_STATE_UNVERIFIED");
    expect(parseLineage(await readFile(generated, "utf8"))).toBeDefined();
  });

  it("removes stale concurrent companions when replacement no longer renders concurrent SQL", {
    timeout: 60_000,
  }, async () => {
    const directory = await mkdtemp(join(tmpdir(), "supa-replace-concurrent-"));
    const config = join(directory, "supaschema.config.json");
    const from = join(directory, "from.sql");
    const migrationsDir = join(directory, "migrations");
    const toConcurrent = join(directory, "to-concurrent.sql");
    const toTransactional = join(directory, "to-transactional.sql");
    const generated = join(migrationsDir, "20260101000000_generated.sql");
    const companion = join(migrationsDir, "20260101000000_generated.concurrent.sql");
    await mkdir(migrationsDir);
    await writeFile(
      config,
      JSON.stringify({ sync: { targets: {} }, transactionMode: "per-statement" })
    );
    await writeFile(from, "CREATE SCHEMA app;\nCREATE TABLE app.items (id integer);\n");
    await writeFile(
      toConcurrent,
      "CREATE SCHEMA app;\nCREATE TABLE app.items (id integer);\nCREATE INDEX CONCURRENTLY items_id_idx ON app.items (id);\n"
    );
    await writeFile(
      toTransactional,
      "CREATE SCHEMA app;\nCREATE TABLE app.items (id integer, name text);\n"
    );

    const initial = await cli([
      "--config",
      config,
      "diff",
      "--from",
      `dump:${from}`,
      "--to",
      `dump:${toConcurrent}`,
      "--migrations-dir",
      migrationsDir,
      "--out",
      generated,
    ]);
    expect(initial.code, initial.stderr).toBe(0);
    expect(await readdir(migrationsDir)).toContain("20260101000000_generated.concurrent.sql");

    const replaced = await cli([
      "--config",
      config,
      "diff",
      "--from",
      `dump:${from}`,
      "--to",
      `dump:${toTransactional}`,
      "--migrations-dir",
      migrationsDir,
      "--replace",
      generated,
    ]);
    expect(replaced.code, replaced.stderr).toBe(0);
    expect(await readdir(migrationsDir)).not.toContain("20260101000000_generated.concurrent.sql");
    await expect(readFile(companion, "utf8")).rejects.toMatchObject({ code: "ENOENT" });
  });

  it("rejects hand-authored replacement migrations", { timeout: 60_000 }, async () => {
    const directory = await mkdtemp(join(tmpdir(), "supa-replace-hand-"));
    const config = await writeBasicFixtureConfig(await mkdtemp(join(tmpdir(), "supa-config-")));
    const handAuthored = join(directory, "0001_hand.sql");
    await writeFile(handAuthored, "CREATE TABLE app.hand_authored (id bigint);\n");

    const result = await cli([
      "--config",
      config,
      "diff",
      "--from",
      fromArg,
      "--to",
      toArg,
      "--migrations-dir",
      directory,
      "--replace",
      handAuthored,
    ]);

    expect(result.code).toBe(2);
    expect(result.stderr).toContain("SUPA_DIFF_REPLACE_HAND_AUTHORED");
  });

  it("allows replacement of legacy-format generated migrations while warning", {
    timeout: 60_000,
  }, async () => {
    const directory = await mkdtemp(join(tmpdir(), "supa-replace-legacy-format-"));
    const config = await writeBasicFixtureConfig(await mkdtemp(join(tmpdir(), "supa-config-")));
    const generated = join(directory, "20260101000000_generated.sql");
    await writeFile(generated, "-- supaschema: lineage from=legacy-from to=legacy-to\nSELECT 1;\n");

    const replaced = await cli([
      "--config",
      config,
      "diff",
      "--from",
      fromArg,
      "--to",
      toArg,
      "--migrations-dir",
      directory,
      "--replace",
      generated,
    ]);

    expect(replaced.code, replaced.stderr).toBe(0);
    expect(replaced.stderr).toContain("SUPA_MIGRATION_BASELINE_FORMAT_DRIFT");
    expect(parseLineage(await readFile(generated, "utf8"))?.modelFormatVersion).toBe(
      MODEL_FORMAT_VERSION
    );
  });

  it("blocks replacement when current-format lineage mismatches the selected baseline", {
    timeout: 60_000,
  }, async () => {
    const directory = await mkdtemp(join(tmpdir(), "supa-replace-current-format-"));
    const config = await writeBasicFixtureConfig(await mkdtemp(join(tmpdir(), "supa-config-")));
    const generated = join(directory, "20260101000000_generated.sql");
    await writeFile(
      generated,
      `-- supaschema: lineage format=${MODEL_FORMAT_VERSION} from=wrong-from to=wrong-to\nSELECT 1;\n`
    );

    const replaced = await cli([
      "--config",
      config,
      "diff",
      "--from",
      fromArg,
      "--to",
      toArg,
      "--migrations-dir",
      directory,
      "--replace",
      generated,
    ]);

    expect(replaced.code).toBe(2);
    expect(replaced.stderr).toContain("SUPA_DIFF_REPLACE_BASELINE_REQUIRED");
  });

  it("warns across legacy generated baselines and re-establishes versioned lineage", {
    timeout: 120_000,
  }, async () => {
    const repo = await mkdtemp(join(tmpdir(), "supa-legacy-baseline-format-"));
    const schemaFile = join(repo, "schemas", "app.sql");
    const migrationsDir = join(repo, "migrations");
    await mkdir(join(repo, "schemas"), { recursive: true });
    await mkdir(migrationsDir, { recursive: true });
    await writeFile(
      join(repo, "supaschema.config.json"),
      JSON.stringify({
        migrationsDir: "migrations",
        schemaPaths: ["schemas"],
        sources: { from: "auto" },
        sync: { targets: {} },
      })
    );
    await writeFile(schemaFile, "CREATE SCHEMA app;\nCREATE TABLE app.accounts (id bigint);\n");
    await git(repo, ["init"]);
    await git(repo, ["add", "."]);
    await git(repo, ["commit", "-m", "v1"]);
    await writeFile(
      join(migrationsDir, "20260101000000_legacy_generated.sql"),
      "-- supaschema: lineage from=legacy-from to=legacy-to\nSELECT 1;\n"
    );
    await git(repo, ["add", "migrations/20260101000000_legacy_generated.sql"]);
    await git(repo, ["commit", "-m", "legacy generated migration"]);
    await writeFile(
      schemaFile,
      "CREATE SCHEMA app;\nCREATE TABLE app.accounts (id bigint, name text);\n"
    );

    const noDbEnv: NodeJS.ProcessEnv = { ...process.env };
    noDbEnv.SUPASCHEMA_DATABASE_URL = undefined;
    const generated = await cli(["diff", "--name", "after_format_change"], {
      cwd: repo,
      env: noDbEnv,
    });

    expect(generated.code, generated.stderr).toBe(0);
    expect(generated.stderr).toContain("SUPA_MIGRATION_BASELINE_FORMAT_DRIFT");
    const lineage = parseLineage(await readFile(generated.stdout.trim(), "utf8"));
    expect(lineage?.modelFormatVersion).toBe(MODEL_FORMAT_VERSION);
  });

  it("warns on dirty trees, blocks stale baselines, classifies them, and recovers by prune + regenerate", {
    timeout: 120_000,
  }, async () => {
    const repo = await mkdtemp(join(tmpdir(), "supa-baseline-incident-"));
    const schemaFile = join(repo, "schemas", "app.sql");
    const migrationsDir = join(repo, "migrations");
    await mkdir(join(repo, "schemas"), { recursive: true });
    await mkdir(migrationsDir, { recursive: true });
    await writeFile(
      join(repo, "supaschema.config.json"),
      JSON.stringify({
        migrationsDir: "migrations",
        schemaPaths: ["schemas"],
        sources: { from: "auto" },
        sync: { targets: {} },
      })
    );
    const noDbEnv: NodeJS.ProcessEnv = { ...process.env };
    noDbEnv.SUPASCHEMA_DATABASE_URL = undefined;
    const runOptions: ExecFileOptions = { cwd: repo, env: noDbEnv };
    const table = (columns: string) =>
      `CREATE SCHEMA app;\nCREATE TABLE app.accounts (\n  id bigint PRIMARY KEY${columns}\n);\n`;

    await writeFile(schemaFile, table(""));
    await git(repo, ["init"]);
    await git(repo, ["add", "."]);
    await git(repo, ["commit", "-m", "v1"]);

    await writeFile(schemaFile, table(",\n  name text"));
    const first = await cli(["diff", "--name", "first"], runOptions);
    expect(first.code, first.stderr).toBe(0);
    expect(first.stderr).toContain("SUPA_DIFF_TREE_UNCOMMITTED");
    const pendingMigration = first.stdout.trim();
    expect(basename(pendingMigration)).toContain("first");

    await writeFile(schemaFile, table(",\n  email text"));
    await git(repo, ["add", "schemas/app.sql"]);
    await git(repo, ["commit", "-m", "v3 without the pending migration"]);

    const blocked = await cli(["diff", "--name", "second"], runOptions);
    expect(blocked.code).toBe(2);
    expect(blocked.stderr).toContain("SUPA_DIFF_MIGRATIONS_DIRTY");

    const report = await cli(["migrations", "--json"], runOptions);
    expect(report.stderr).toContain("SUPA_MIGRATIONS_STALE_BASELINE");
    const parsed: { staleBaseline: string[] } = JSON.parse(report.stdout);
    expect(parsed.staleBaseline).toEqual([basename(pendingMigration)]);

    const prune = await cli(["migrations", "--prune-stale", "--force", "--json"], runOptions);
    expect(prune.code, prune.stderr).toBe(0);
    const pruned: { prunedStaleBaseline: string[] } = JSON.parse(prune.stdout);
    expect(pruned.prunedStaleBaseline).toEqual([basename(pendingMigration)]);
    expect(await readdir(migrationsDir)).not.toContain(basename(pendingMigration));

    await writeFile(schemaFile, table(",\n  email text,\n  phone text"));
    const recovered = await cli(["diff", "--name", "recovered"], runOptions);
    expect(recovered.code, recovered.stderr).toBe(0);
    expect(recovered.stderr).toContain("SUPA_DIFF_TREE_UNCOMMITTED");
    const regenerated = recovered.stdout.trim();

    await git(repo, ["add", "schemas/app.sql", regenerated]);
    await git(repo, ["commit", "-m", "atomic tree + migration commit"]);
    const clean = await cli(["diff"], runOptions);
    expect(clean.code, clean.stderr).toBe(0);
    expect(clean.stderr).not.toContain("SUPA_DIFF_TREE_UNCOMMITTED");
    expect(clean.stderr).toContain("no schema changes");
  });

  it("continues a CLI diff from a proven staged closure", { timeout: 120_000 }, async () => {
    const repo = await mkdtemp(join(tmpdir(), "supa-index-baseline-"));
    const schemaFile = join(repo, "schemas", "app.sql");
    await mkdir(join(repo, "schemas"), { recursive: true });
    await mkdir(join(repo, "migrations"), { recursive: true });
    await writeFile(
      join(repo, "supaschema.config.json"),
      JSON.stringify({
        migrationsDir: "migrations",
        schemaPaths: ["schemas"],
        sources: { from: "auto" },
        sync: { targets: {} },
      })
    );
    await writeFile(schemaFile, "CREATE TABLE public.accounts (id bigint PRIMARY KEY);\n");
    await git(repo, ["init"]);
    await git(repo, ["add", "."]);
    await git(repo, ["commit", "-m", "v1"]);

    await writeFile(
      schemaFile,
      "CREATE TABLE public.accounts (id bigint PRIMARY KEY, name text);\n"
    );
    const first = await cli(["diff", "--name", "first"], { cwd: repo });
    expect(first.code, first.stderr).toBe(0);
    const firstFile = first.stdout.trim();
    const firstLineage = parseLineage(await readFile(firstFile, "utf8"));
    await git(repo, ["add", "schemas/app.sql", firstFile]);

    await writeFile(
      schemaFile,
      "CREATE TABLE public.accounts (id bigint PRIMARY KEY, name text, email text);\n"
    );
    const second = await cli(["diff", "--name", "second"], { cwd: repo });
    expect(second.code, second.stderr).toBe(0);
    expect(second.stderr).not.toContain("SUPA_DIFF_MIGRATIONS_DIRTY");
    const secondLineage = parseLineage(await readFile(second.stdout.trim(), "utf8"));
    expect(secondLineage?.from).toBe(firstLineage?.to);
  });

  it("replays an uncommitted hand-authored tail instead of blocking on it", {
    timeout: 120_000,
  }, async () => {
    const repo = await mkdtemp(join(tmpdir(), "supa-tail-replay-"));
    const schemaFile = join(repo, "schemas", "app.sql");
    await mkdir(join(repo, "schemas"), { recursive: true });
    await mkdir(join(repo, "migrations"), { recursive: true });
    await writeFile(
      join(repo, "supaschema.config.json"),
      JSON.stringify({
        migrationsDir: "migrations",
        schemaPaths: ["schemas"],
        sources: { from: "auto" },
        sync: { targets: {} },
      })
    );
    await git(repo, ["init"]);
    await git(repo, ["add", "."]);
    await git(repo, ["commit", "-m", "v1"]);

    await writeFile(
      schemaFile,
      "CREATE TABLE public.accounts (id bigint PRIMARY KEY, name text);\n"
    );
    const first = await cli(["diff", "--name", "first"], { cwd: repo });
    expect(first.code, first.stderr).toBe(0);
    await git(repo, ["add", "schemas/app.sql", "migrations"]);
    await git(repo, ["commit", "-m", "v2 with generated closure"]);

    await writeFile(
      join(repo, "migrations", "20261231235959_hand.sql"),
      "ALTER TABLE public.accounts ADD COLUMN email text;\n"
    );
    await writeFile(
      schemaFile,
      "CREATE TABLE public.accounts (id bigint PRIMARY KEY, name text, email text, phone text);\n"
    );
    const result = await cli(["diff", "--name", "tail"], { cwd: repo });
    expect(result.stderr).not.toContain("SUPA_DIFF_MIGRATIONS_DIRTY");
    expect(result.stderr).toContain("SUPA_DIFF_LINEAGE_BROKEN");

    const continued = await cli(["diff", "--name", "tail", "--no-check-chain"], { cwd: repo });
    expect(continued.code, continued.stderr).toBe(0);
    expect(continued.stderr).not.toContain("SUPA_DIFF_MIGRATIONS_DIRTY");
    const generated = await readFile(continued.stdout.trim(), "utf8");
    expect(generated).toContain("phone");
    expect(generated).not.toContain("ADD COLUMN email");
  });

  it("replays a staged hand-authored tail instead of choosing the staged closure", {
    timeout: 120_000,
  }, async () => {
    const repo = await mkdtemp(join(tmpdir(), "supa-staged-tail-"));
    const schemaFile = join(repo, "schemas", "app.sql");
    await mkdir(join(repo, "schemas"), { recursive: true });
    await mkdir(join(repo, "migrations"), { recursive: true });
    await writeFile(
      join(repo, "supaschema.config.json"),
      JSON.stringify({
        migrationsDir: "migrations",
        schemaPaths: ["schemas"],
        sources: { from: "auto" },
        sync: { targets: {} },
      })
    );
    await writeFile(schemaFile, "CREATE TABLE public.accounts (id bigint PRIMARY KEY);\n");
    await git(repo, ["init"]);
    await git(repo, ["add", "."]);
    await git(repo, ["commit", "-m", "v1"]);

    await writeFile(
      schemaFile,
      "CREATE TABLE public.accounts (id bigint PRIMARY KEY, name text);\n"
    );
    const first = await cli(["diff", "--name", "first"], { cwd: repo });
    expect(first.code, first.stderr).toBe(0);
    const firstFile = first.stdout.trim();
    await git(repo, ["add", "schemas/app.sql", firstFile]);

    await writeFile(
      join(repo, "migrations", "20261231235959_hand.sql"),
      "ALTER TABLE public.accounts ADD COLUMN email text;\n"
    );
    await git(repo, ["add", "migrations/20261231235959_hand.sql"]);
    await writeFile(
      schemaFile,
      "CREATE TABLE public.accounts (id bigint PRIMARY KEY, name text, email text);\n"
    );

    const result = await cli(["diff", "--name", "tail", "--dry-run"], { cwd: repo });
    expect(result.stderr).toContain("--from migrations:migrations");
    expect(result.stderr).not.toContain("SUPA_MIGRATION_BASELINE_REPLAY_REQUIRED");
  });

  it("keeps the lineage chain continuous across scoped --schema diffs", {
    timeout: 120_000,
  }, async () => {
    const repo = await mkdtemp(join(tmpdir(), "supa-scoped-chain-"));
    const appFile = join(repo, "schemas", "app.sql");
    const billingFile = join(repo, "schemas", "billing.sql");
    await mkdir(join(repo, "schemas"), { recursive: true });
    await mkdir(join(repo, "migrations"), { recursive: true });
    await writeFile(
      join(repo, "supaschema.config.json"),
      JSON.stringify({
        migrationsDir: "migrations",
        schemaPaths: ["schemas"],
        sources: { from: "auto" },
        sync: { targets: {} },
      })
    );
    const noDbEnv: NodeJS.ProcessEnv = { ...process.env };
    noDbEnv.SUPASCHEMA_DATABASE_URL = undefined;
    const runOptions: ExecFileOptions = { cwd: repo, env: noDbEnv };

    await writeFile(
      appFile,
      "CREATE SCHEMA app;\nCREATE TABLE app.accounts (\n  id bigint PRIMARY KEY\n);\n"
    );
    await writeFile(
      billingFile,
      "CREATE SCHEMA billing;\nCREATE TABLE billing.invoices (\n  id bigint PRIMARY KEY\n);\n"
    );
    await git(repo, ["init"]);
    await git(repo, ["add", "."]);
    await git(repo, ["commit", "-m", "v1"]);

    await writeFile(
      appFile,
      "CREATE SCHEMA app;\nCREATE TABLE app.accounts (\n  id bigint PRIMARY KEY,\n  name text\n);\n"
    );

    const scoped = await cli(["diff", "--schema", "app", "--name", "app_change"], runOptions);
    expect(scoped.code, scoped.stderr).toBe(0);
    const scopedPath = scoped.stdout.trim();
    const scopedSql = await readFile(scopedPath, "utf8");
    expect(scopedSql).toContain('"app"."accounts"');
    expect(scopedSql).not.toContain("billing");
    const scopedLineage = parseLineage(scopedSql);
    expect(scopedLineage).toBeDefined();

    await git(repo, ["add", "schemas/app.sql", scopedPath]);
    await git(repo, ["commit", "-m", "scoped atomic commit: app schema + migration"]);

    await writeFile(
      billingFile,
      "CREATE SCHEMA billing;\nCREATE TABLE billing.invoices (\n  id bigint PRIMARY KEY,\n  total numeric\n);\n"
    );
    const remaining = await cli(["diff", "--name", "billing_change"], runOptions);
    expect(remaining.code, remaining.stderr).toBe(0);
    expect(remaining.stderr).not.toContain("ERROR SUPA_MIGRATION_BASELINE_MISMATCH");
    expect(remaining.stderr).not.toContain("ERROR SUPA_DIFF_LINEAGE_BROKEN");
    const remainingSql = await readFile(remaining.stdout.trim(), "utf8");
    expect(remainingSql).toContain('"billing"."invoices"');
    expect(remainingSql).not.toContain('"app"."accounts"');
    const remainingLineage = parseLineage(remainingSql);
    expect(remainingLineage?.from).toBe(scopedLineage?.to);
  });

  it("blocks scoped diffs when another schema is dirty", { timeout: 120_000 }, async () => {
    const repo = await mkdtemp(join(tmpdir(), "supa-scoped-dirty-schema-"));
    await mkdir(join(repo, "schemas"), { recursive: true });
    await mkdir(join(repo, "migrations"), { recursive: true });
    await writeFile(
      join(repo, "supaschema.config.json"),
      JSON.stringify({
        migrationsDir: "migrations",
        schemaPaths: ["schemas"],
        sources: { from: "auto" },
        sync: { targets: {} },
      })
    );
    await writeFile(
      join(repo, "schemas", "app.sql"),
      "CREATE SCHEMA app;\nCREATE TABLE app.accounts (id bigint PRIMARY KEY);\n"
    );
    await writeFile(
      join(repo, "schemas", "billing.sql"),
      "CREATE SCHEMA billing;\nCREATE TABLE billing.invoices (id bigint PRIMARY KEY);\n"
    );
    await git(repo, ["init"]);
    await git(repo, ["add", "."]);
    await git(repo, ["commit", "-m", "v1"]);

    await writeFile(
      join(repo, "schemas", "app.sql"),
      "CREATE SCHEMA app;\nCREATE TABLE app.accounts (id bigint PRIMARY KEY, name text);\n"
    );
    await writeFile(
      join(repo, "schemas", "billing.sql"),
      "CREATE SCHEMA billing;\nCREATE TABLE billing.invoices (id bigint PRIMARY KEY, total numeric);\n"
    );

    const noDbEnv: NodeJS.ProcessEnv = { ...process.env };
    noDbEnv.SUPASCHEMA_DATABASE_URL = undefined;
    const result = await cli(["diff", "--schema", "app", "--name", "app_change"], {
      cwd: repo,
      env: noDbEnv,
    });

    expect(result.code).toBe(2);
    expect(result.stderr).toContain("SUPA_DIFF_SCOPED_DIRTY_SCHEMA");
    expect(await readdir(join(repo, "migrations"))).toEqual([]);
  });

  it("blocks diffs when migration, config, or generated contract closures are already dirty", {
    timeout: 120_000,
  }, async () => {
    const repo = await mkdtemp(join(tmpdir(), "supa-dirty-closure-"));
    await mkdir(join(repo, "schemas"), { recursive: true });
    await mkdir(join(repo, "migrations"), { recursive: true });
    await mkdir(join(repo, "types"), { recursive: true });
    const configPath = join(repo, "supaschema.config.json");
    await writeFile(
      configPath,
      JSON.stringify({
        migrationsDir: "migrations",
        schemaPaths: ["schemas"],
        sources: { from: "auto" },
        sync: { targets: {} },
        typesFile: "types/database.generated.ts",
        zodFile: "types/database.zod.generated.ts",
      })
    );
    await writeFile(
      join(repo, "schemas", "app.sql"),
      "CREATE SCHEMA app;\nCREATE TABLE app.accounts (id bigint PRIMARY KEY);\n"
    );
    await writeFile(join(repo, "types", "database.generated.ts"), "export type Database = {};\n");
    await writeFile(join(repo, "types", "database.zod.generated.ts"), "export const zod = {};\n");
    await git(repo, ["init"]);
    await git(repo, ["add", "."]);
    await git(repo, ["commit", "-m", "v1"]);

    await writeFile(
      configPath,
      `${JSON.stringify({
        migrationsDir: "migrations",
        schemaPaths: ["schemas"],
        sources: { from: "auto" },
        sync: { targets: {} },
        typesFile: "types/database.generated.ts",
        zodFile: "types/database.zod.generated.ts",
      })}\n`
    );
    await writeFile(
      join(repo, "types", "database.generated.ts"),
      "export type Database = { dirty: true };\n"
    );
    await writeFile(
      join(repo, "migrations", "20260101000000_pending.sql"),
      "-- hand-authored pending migration\nSELECT 1;\n"
    );

    const noDbEnv: NodeJS.ProcessEnv = { ...process.env };
    noDbEnv.SUPASCHEMA_DATABASE_URL = undefined;
    const result = await cli(["diff", "--schema", "app", "--name", "blocked"], {
      cwd: repo,
      env: noDbEnv,
    });

    expect(result.code).toBe(2);
    expect(result.stderr).toContain("SUPA_DIFF_CONFIG_DIRTY");
    expect(result.stderr).toContain("SUPA_DIFF_GENERATED_CONTRACT_DIRTY");
    expect(result.stderr).toContain("SUPA_DIFF_MIGRATIONS_DIRTY");
  });

  it("blocks duplicate transitions, broken chains, and overwrites; --no-check-chain bypasses", {
    timeout: 60_000,
  }, async () => {
    const directory = await mkdtemp(join(tmpdir(), "supa-chain-"));
    const config = await writeBasicFixtureConfig(await mkdtemp(join(tmpdir(), "supa-config-")));
    const diff = ["--config", config, "diff"];
    const first = join(directory, "0001_first.sql");

    const initial = await cli([...diff, "--from", fromArg, "--to", toArg, "--out", first]);
    expect(initial.code).toBe(0);
    expect(parseLineage(await readFile(first, "utf8"))).toBeDefined();

    const duplicate = await cli([
      ...diff,
      "--from",
      fromArg,
      "--to",
      toArg,
      "--out",
      join(directory, "0002_dup.sql"),
    ]);
    expect(duplicate.code).toBe(2);
    expect(duplicate.stderr).toContain("SUPA_DIFF_LINEAGE_DUPLICATE");

    const broken = await cli([
      ...diff,
      "--from",
      fromArg,
      "--to",
      fromArg,
      "--out",
      join(directory, "0003_broken.sql"),
    ]);
    expect(broken.code).toBe(2);
    expect(broken.stderr).toContain("SUPA_DIFF_LINEAGE_BROKEN");

    const continued = await cli([
      ...diff,
      "--from",
      toArg,
      "--to",
      toArg,
      "--out",
      join(directory, "0004_next.sql"),
    ]);
    expect(continued.code).toBe(2);
    expect(continued.stderr).toContain("SUPA_DIFF_EMPTY_PLAN");

    const bypassed = await cli([
      ...diff,
      "--from",
      fromArg,
      "--to",
      toArg,
      "--no-check-chain",
      "--out",
      join(directory, "0005_bypass.sql"),
    ]);
    expect(bypassed.code).toBe(0);

    const clobber = await cli([
      ...diff,
      "--from",
      fromArg,
      "--to",
      toArg,
      "--fail-on-diff",
      "--no-check-chain",
      "--out",
      first,
    ]);
    expect(clobber.code).toBe(2);
    expect(clobber.stderr).toContain("SUPA_DIFF_OUTPUT_EXISTS");
    expect(parseLineage(await readFile(first, "utf8"))).toBeDefined();
  });
});
