import { readdir, readFile } from "node:fs/promises";
import { join } from "node:path";
import { Client } from "pg";
import type { Diagnostic } from "./core.js";
import { diagnostic } from "./diagnostics.js";
import type { MigrationLineage } from "./lineage.js";
import { parseLineage } from "./lineage.js";
import { quoteIdent } from "./sql/identifiers.js";

export interface MigrationsStatusOptions {
  databaseUrl?: string;
  directory: string;
  historyTable?: string;
}

export interface MigrationsStatusReport {
  /** Versions present both on disk and in the target's history table. */
  applied: string[];
  /** Disk files whose version the target has not applied yet. */
  pending: string[];
  /** Versions in the target's history with no file on disk. */
  ghosts: string[];
  /** Pending files older than the target's newest applied version. */
  outOfOrder: string[];
  /** Pending files generated by supaschema, with their lineage markers. */
  pendingLineage: MigrationLineage[];
  files: string[];
  historyTable: string;
  target?: string;
}

const defaultHistoryTable = "supabase_migrations.schema_migrations";
const versionPattern = /^(\d{8,})/u;
const lineageScanBytes = 4096;

/**
 * Three states can diverge independently: migration files in the worktree,
 * the history table on one database (local), and the history table on
 * another (remote/linked). This report reconciles the worktree against one
 * target; run it once per target to see all three. Ghost versions and
 * out-of-order pending files are integrity defects, not normal pending work.
 */
export async function migrationsStatus(
  options: MigrationsStatusOptions,
): Promise<{ diagnostics: Diagnostic[]; report: MigrationsStatusReport }> {
  const diagnostics: Diagnostic[] = [];
  const historyTable = options.historyTable ?? defaultHistoryTable;
  const files = (await readdir(options.directory))
    .filter((name) => name.endsWith(".sql") && versionPattern.test(name))
    .sort((left, right) => left.localeCompare(right));
  const versionsByFile = new Map(files.map((name) => [name, versionPattern.exec(name)?.[1] ?? ""]));
  const report: MigrationsStatusReport = {
    applied: [],
    files,
    ghosts: [],
    historyTable,
    outOfOrder: [],
    pending: [],
    pendingLineage: [],
  };
  if (!options.databaseUrl) {
    report.pending = files;
    diagnostics.push(
      diagnostic(
        "SUPA_MIGRATIONS_NO_TARGET",
        "warning",
        "no database URL resolved; reporting disk files only",
        { hint: "Pass --database-url or set SUPASCHEMA_DATABASE_URL to compare against a target." },
      ),
    );
    await annotateLineage(options.directory, report);
    return { diagnostics, report };
  }
  report.target = redactUrl(options.databaseUrl);
  const appliedVersions = await readHistory(options.databaseUrl, historyTable, diagnostics);
  if (appliedVersions === undefined) {
    return { diagnostics, report };
  }
  const diskVersions = new Set(versionsByFile.values());
  const newestApplied = [...appliedVersions].sort().at(-1) ?? "";
  for (const file of files) {
    const version = versionsByFile.get(file) ?? "";
    if (appliedVersions.has(version)) {
      report.applied.push(file);
      continue;
    }
    report.pending.push(file);
    if (version < newestApplied) {
      report.outOfOrder.push(file);
    }
  }
  report.ghosts = [...appliedVersions].filter((version) => !diskVersions.has(version)).sort();
  await annotateLineage(options.directory, report);
  if (report.ghosts.length > 0) {
    diagnostics.push(
      diagnostic(
        "SUPA_MIGRATIONS_GHOST_VERSIONS",
        "error",
        `${report.ghosts.length} applied version(s) have no migration file on disk`,
        { hint: `ghost versions: ${report.ghosts.slice(0, 8).join(", ")}` },
      ),
    );
  }
  if (report.outOfOrder.length > 0) {
    diagnostics.push(
      diagnostic(
        "SUPA_MIGRATIONS_OUT_OF_ORDER",
        "error",
        `${report.outOfOrder.length} pending file(s) are older than the target's newest applied version`,
        { hint: `out-of-order: ${report.outOfOrder.slice(0, 8).join(", ")}` },
      ),
    );
  }
  return { diagnostics, report };
}

export function renderMigrationsStatus(report: MigrationsStatusReport): string {
  const lines: string[] = [];
  lines.push(
    `migrations: ${report.files.length} file(s) on disk vs ${report.target ?? "no target"} (${report.historyTable})`,
  );
  lines.push(
    `  applied: ${report.applied.length}  pending: ${report.pending.length}  ghosts: ${report.ghosts.length}  out-of-order: ${report.outOfOrder.length}`,
  );
  for (const file of report.pending) {
    const lineage = report.pendingLineage.find((item) => item.file === file);
    lines.push(`  pending: ${file}${lineage ? " (supaschema lineage)" : ""}`);
  }
  for (const version of report.ghosts) {
    lines.push(`  ghost: ${version} (applied on target, no file on disk)`);
  }
  for (const file of report.outOfOrder) {
    lines.push(`  out-of-order: ${file}`);
  }
  return `${lines.join("\n")}\n`;
}

async function readHistory(
  databaseUrl: string,
  historyTable: string,
  diagnostics: Diagnostic[],
): Promise<Set<string> | undefined> {
  const parts = historyTable.split(".");
  if (parts.length !== 2 || parts.some((part) => part.length === 0)) {
    diagnostics.push(
      diagnostic(
        "SUPA_MIGRATIONS_HISTORY_TABLE",
        "error",
        `history table "${historyTable}" must be schema-qualified`,
      ),
    );
    return undefined;
  }
  const client = new Client({ connectionString: databaseUrl });
  try {
    await client.connect();
    const exists = await client.query<{ found: boolean }>(
      "select exists (select 1 from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid = c.relnamespace where n.nspname = $1 and c.relname = $2) as found",
      [parts[0], parts[1]],
    );
    if (exists.rows[0]?.found !== true) {
      diagnostics.push(
        diagnostic(
          "SUPA_MIGRATIONS_HISTORY_TABLE",
          "error",
          `history table ${historyTable} does not exist on the target`,
          { hint: "Pass --history-table for runners that record history elsewhere." },
        ),
      );
      return undefined;
    }
    const result = await client.query<{ version: string }>(
      `select version::text as version from ${quoteIdent(parts[0] ?? "")}.${quoteIdent(parts[1] ?? "")}`,
    );
    return new Set(result.rows.map((row) => row.version));
  } catch (error) {
    diagnostics.push(
      diagnostic(
        "SUPA_MIGRATIONS_TARGET_UNAVAILABLE",
        "error",
        error instanceof Error ? error.message : String(error),
        { hint: "Confirm the database URL is reachable." },
      ),
    );
    return undefined;
  } finally {
    await client.end().catch(() => undefined);
  }
}

async function annotateLineage(directory: string, report: MigrationsStatusReport): Promise<void> {
  for (const file of report.pending) {
    const handle = await readFile(join(directory, file), "utf8").catch(() => undefined);
    if (handle === undefined) {
      continue;
    }
    const lineage = parseLineage(handle.slice(0, lineageScanBytes));
    if (lineage) {
      report.pendingLineage.push({ file, ...lineage });
    }
  }
}

function redactUrl(value: string): string {
  try {
    const url = new URL(value);
    if (url.password) {
      url.password = "***";
    }
    return url.toString();
  } catch {
    return "<database>";
  }
}
