CREATE SCHEMA app;

CREATE TABLE app.accounts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL
);

ALTER TABLE app.accounts ENABLE ROW LEVEL SECURITY;

CREATE POLICY accounts_select ON app.accounts
  FOR SELECT
  TO public
  USING (true);

CREATE INDEX accounts_name_idx ON app.accounts (name);

CREATE OR REPLACE FUNCTION app.greeting()
RETURNS text
LANGUAGE sql
STABLE
AS $$
  SELECT 'hello'::text
$$;

CREATE OR REPLACE FUNCTION app.legacy_ping()
RETURNS text
LANGUAGE sql
AS $$
  SELECT 'pong'::text
$$;

CREATE VIEW app.account_names AS
SELECT name FROM app.accounts;

COMMENT ON TABLE app.accounts IS 'Accounts';
